### ISSUE TITLE
Lister les FANTOIR erronés

### ISSUE THREAD

**Issue by vdct** [osm-fr/osm-vs-fantoir#10]
cf. http://forum.openstreetmap.fr/viewtopic.php?f=2&t=1187&start=120#p7349 et suivants
Avoir une liste des codes FANTOIR inconnus de la base Fantoir, mais référencés par OSM
Avoir le moyen d'éditer les objets OSM correspondants
Accéder au listing Fantoir des communes correspondantes pour recherche / comparaison

**Comment by the-knife** [comment]
Savoir si un FANTOIR est "périmé".
https://lists.openstreetmap.org/pipermail/talk-fr/2014-December/073736.html

**Comment by vdct** [comment]
https://github.com/osm-fr/osm-vs-fantoir/commit/c285348cb293c1918ac3587d00df2f67761922be

**Comment by vdct** [comment]
http://cadastre.openstreetmap.fr/fantoir/fantoir_errone.html
