### ISSUE TITLE
rendre la "liste des emprises inconnues de Fantoir" plus stricte

### ISSUE THREAD

**Issue by niconil** [osm-fr/osm-vs-fantoir#105]
Dans mon cas la "Route de Bouloc" (voie de Villaudric - village voisin) est identifiée dans la liste des emprises inconnues de Fantoir sur la page de Bouloc

lorsqu'on regarde effectivement le way ne tombe pas pile (mais s'achève 2m environ au delà de la séparation des communes) et donc est considéré comme existant aussi à Bouloc

plusieurs questions :
le way doit-il s'arréter exactement sur un noeud de la séparation entre communes ?
peut-il légèrement dépasser ?
si oui quelle est la tolérance ?
est-il possible d'éviter ces "faux positifs" ?

Les références vers le cas que je cite :
https://www.openstreetmap.org/#map=19/43.82026/1.42541
Bouloc : code INSEE 31079
et voir que la "route de Bouloc" est listée ici :
http://dev.cadastre.openstreetmap.fr/fantoir/#insee=31079&tab=6

**Comment by vdct** [comment]
> le way doit-il s'arréter exactement sur un noeud de la séparation entre communes ?
Oui. Le nom est celui valable dans la commune. Plus généralement : le way s'arrête là où au moins une de ses propriétés n'est plus valable, que ce soit son nom, une limite de vitesse, ou n'importe quoi d'autre. Il n'est pas forcément facile d'être précis quand ça intervient n'importe où le long d'une voie. Dans le cas d'une info qui change parce qu'on change de commune, ça doit être plus simple

> peut-il légèrement dépasser ?
Non

> si oui quelle est la tolérance ?
Donc 0 :)

> est-il possible d'éviter ces "faux positifs" ?
Tout l'objet des pages Fantoir c'est au contraire de dénicher ce genre de soucis de cohérence. Ca vaut pour l'orthographe, l'exactitude d'un code Fantoir, mais aussi pour la géométrie
