### ISSUE TITLE
Connaître les parcelles qui font référence à une voie FANTOIR

### ISSUE THREAD

**Issue by niconil** [osm-fr/osm-vs-fantoir#106]
Dans le code, à la lecture de cette phrase, j'ai imaginé que dans certains cas connaitre les numéros de parcelles référençant une voie parfois introuvable sur le terrain pourrait aider à qualifier certains cas. La phrase est la suivante :
https://github.com/osm-fr/osm-vs-fantoir/blob/91dc8e529e35506f3415d5e036035289658fef25/index.html#L854

maintenant tout dépend comment on récupère ces données et si cette demande est simple à réaliser ...

**Comment by vdct** [comment]
Je suis entièrement d'accord sur l'intérêt d'avoir le lien parcelle <=> numéro d'adresse. Malheureusement c'est une info qu'on avait grâce à l'extraction des adresses des PDFs DGFiP, méthode abandonnée avec BANO v2. Je ne lui connais pas de remplaçant disponible.
