### ISSUE TITLE
Certaines adresses semblent manquantes

### ISSUE THREAD

**Issue by niconil** [osm-fr/osm-vs-fantoir#107]
Sur la commune de Fronton (31202), je souhaite intégrer les adresses de l'Avenue de Grisolles (312020075C) [avec environ 70 adresses à intégrer ... miam]
je me rends donc sur : 
http://dev.cadastre.openstreetmap.fr/fantoir/#insee=31202&tab=1
et je clique sur le lien 'relation' pour avoir dans JOSM la proposition à contrôler avant intégration

si je pars du début de la voie les premières adresses proposées sont
15, 25, 45A, 55, ...

mais 
avec le module cadastre de Vincent les numéros extraits sont:
15, 25, **35**, 45 A, **45 B**, 55
c'est ce que l'on voit aussi sur les tuiles WMS du Cadastre

pourquoi ces numéros (le 35 et le 45 B) ne remontent-ils pas dans la proposition d'adresses à intégrer ?
Du coup je ne touche à rien en attendant

**Comment by vdct** [comment]
La source n'est pas la même. 
- celle de l'outil BANO est https://adresse.data.gouv.fr/data/adresses-cadastre/latest/ de septembre 2019
- celle du plugin JOSM est https://cadastre.data.gouv.fr/data/dgfip-pci-vecteur/latest/edigeo/ de fin fevrier.

Celle de BANO basculera (date à défiinir) sur le produit Adresses de https://adresse.data.gouv.fr/donnees-nationales. D'ici là tu peux je penses faire confiance plutôt à l'actualité des données via le plugin, en économisant des clics via les outils d’intégration

**Comment by niconil** [comment]
j'ai pris le cas du 35 Avenue de Grisolles à Fronton (31202) : ref 31202_0075_00035

ok je savais pour bano que la source était figée à septembre 2019 mais je peux garantir l'existence de longue date du numéro 35. Les 8 huit mois d'ancienneté de la source n'explique pas cette absence.

En regardant le fichier csv en colonne 'destination_principale' cette adresse a le statut de 'dependance' c'est cela qui fait qu'elle est écartée ?
Par rapport au terrain un contributeur observera une maison aux volets clos à cette adresse, et sera donc tenté de rajouter l'adresse

Dans le référentiel de mon entreprise cette adresse est dite 'désactivée' confirmant probablement qu'il n'y a pas d'occupant actuellement. 

Pour autant cette adresse a toujours une existence physique sur le terrain et je serai tenté de la laisser car de toute façon il ne s'agit pas dans openstreetmap de vérifier l'occupation réelle de chaque habitation. est-ce bien cela la raison de la non présentation de ce numéro 35 ?

**Comment by vdct** [comment]
La bascule vers le produit Adresses de la BAN est faite, on a maintenant bien les n° 35 et 45 B dans les adresses proposées en intégration
![Capture d’écran de 2020-11-13 23-24-32](https://user-images.githubusercontent.com/2237260/99126971-7c7b1600-2607-11eb-8fd6-60c9722f22e7.png)
