### ISSUE TITLE
Pas de BAN lorsque l'on clic sur les liens dans adresses à intégrer

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#110]
Le clic sur les liens dans "adresses à intégrer" sur les differentes pages ne récupèrent pas les adresses de la BAN.
La bascule cadastre -> ban n'est pas terminé :)
Je pense qu'il faut modifier les source = 'CADASTRE' dans numeros_hors_osm_par_fantoir.sql.

Il y a des références au cadastre sur plusieurs pages :
"Voies connues du Cadastre mais pas d'OSM, avec beaucoup d'adresses" dans top_adresses_manquantes.html
"Voies récentes selon FANTOIR, connues du Cadastre mais pas d'OSM" dans voies_recentes_manquantes.html
"Cadastre récupéré le" sur la page des communes

**Comment by Olyon** [comment]
@vdct

**Comment by vdct** [comment]
> 
> 
> Le clic sur les liens dans "adresses à intégrer" sur les differentes pages ne récupèrent pas les adresses de la BAN.
> La bascule cadastre -> ban n'est pas terminé :)

Non en effet :)

> Je pense qu'il faut modifier les source = 'CADASTRE' dans numeros_hors_osm_par_fantoir.sql.
> 
> Il y a des références au cadastre sur plusieurs pages :
> "Voies connues du Cadastre mais pas d'OSM, avec beaucoup d'adresses" dans top_adresses_manquantes.html
> "Voies récentes selon FANTOIR, connues du Cadastre mais pas d'OSM" dans voies_recentes_manquantes.html
> "Cadastre récupéré le" sur la page des communes

Oui il reste à passer en revue le code et "traquer" les références au Cadastre. Merci pour le pointeur sur les adresses

**Comment by Olyon** [comment]
La sortie sous forme de relation ne fonctionne pas pour des voies sans rapprochement osm.
Je vois qu'il y a besoin de name_and_positions_OSM_as_GeoJSON.sql lorsqu'on demande une relaltion donc peut être du à la presence de voie_cadastre au lieu de voie_autre ?

**Comment by vdct** [comment]
Merci @Olyon pour ton inspection méticuleuse 👍  
Je regarde ça dès que possible

**Comment by vdct** [comment]
@Olyon c'est normalement corrigé, merci
