### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#117]
Dans la page http://bano.openstreetmap.fr/fantoir/stats_dept.html, en bas du point d'interrogation, le lien vers la doc Fantoir est mort.

Le bon lien est celui-ci:
https://www.collectivites-locales.gouv.fr/files/files/finances_locales/fantoir/Descriptif_FANTOIR_2016.pdf

**Comment by Olyon** [comment]
problème réglé #123
