### ISSUE TITLE
Lien mort 2

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#119]
Hello,

Dans les outils Fantoir, la page http://bano.openstreetmap.fr/fantoir/stats_dept.html
les codes Insee communes renvoient vers http://cadastre.openstreetmap.fr/fantoir/#insee=54001 d'où erreur 404.

Il serait pertinent de renvoyer vers http://bano.openstreetmap.fr/fantoir/#insee=54001&tab=0

**Comment by Olyon** [comment]
problème réglé #123
