### ISSUE TITLE
Bilan par département

### ISSUE THREAD

**Issue by vdct** [osm-fr/osm-vs-fantoir#12]
Avoir par département un état synthétique de l'avancement des rapprochements par commune.
Amorcé avec https://github.com/osm-fr/osm-vs-fantoir/commit/6a4c228312eea46f512949a7d7229e3dcbb77359

**Comment by niconil** [comment]
oui dans le cas d'un groupe d'utilisateurs locaux ce serait intéressant de pouvoir suivre facilement l'avancée (le nbre de voies en écart par Départments)

on peut peut-etre démarrer simplement en reprenant un mécanisme du rendu bano ou on a le nbre de voies d'écart par commune
je ne sais pas comment est fait ce calcul mais est-il faisable à l'achelle département ?

en tout cas ce serait suffisant dans un premier temps
