### ISSUE TITLE
Rendu inutile

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#120]
Dans toutes les pages des outils Fantoir, il y a plusieurs liens vers plusieurs rendus dont:

- un vers FR http://tile.openstreetmap.fr/?zoom=18&lat=49.392224&lon=5.760928
- un vers Bano http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/49.39300/5.76107

Il me semblerait judicieux de débrancher FR car il n'apporte rien de plus que le fond Bano et ne permet pas le contrôle à distance. Ca permettrait d'alléger tout le truc.
Il me semble qu'à l'origine sur le fond FR, il y avait un rendu avec Bano, mais il a dû être désactivé

**Comment by Marc-marc-marc** [comment]
en effet avoir 2 liens est un peu redondant, d'autant que le lien bano utilise le fond FR
j'ai proposé de [rétablir la couche bano sur layers](https://github.com/osm-fr/presentoir-carte/issues/11) et ouvert un autre [ticket](https://github.com/osm-fr/infrastructure/issues/258) pour l'incohérence entre tile et layers et la pertinence ou non d'avoir 3 présentoirs.
restera alors le bouton "éditer osm : iD<>josm", je suppose que tu parles du fait que le lien actuel ne permet pas d'ouvrir dans josm si ton profil utilisateur est définit pour utiliser iD par défaut (modifiable dans ton profil osm.org, Éditeur préféré)

**Comment by gendy54** [comment]
Mon éditeur par défaut est Josm.
Mais sinon tu as bien cerné le pb.

**Comment by vdct** [comment]
Globalement pris en compte en v3
