### ISSUE TITLE
top_adresses_manquantes sans adresses

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#121]
Il y a beaucoup de lignes des pages top_adresses_manquantes qui indiquent un nombres important d'adresses mais qui en ont zero lorsque l'on appuis sur "x points" ou "relation".
Je pense qu'il manque un tri sur la source dans top_adresses_manquantes.sql
un where source in (BAN,BAL) dans cumul_adresses pour ne pas avoir les source=cadastre
ou alors supprimer toutes les adresses avec source=cadastre dans cumul_adresses vu qu'elles ne servent plus à rien.

**Comment by vdct** [comment]
Merci encore @Olyon 
J'ai choisi la dernière option, en supprimant les 19851038 (!) lignes de cumul_adresses avec une source='CADASTRE' car en effet elles sont inutilisées et leur alimentation est coupée. En testant la page top_adresses_manquantes ensuite, ça semblkait bien mieux fonctionner, avec moins de volume mais de vraies données derrière les clics d'intégration

**Comment by Olyon** [comment]
Merci,
oui ça va plus vite !
