### ISSUE TITLE
Recollement d'adresses

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osm-vs-fantoir#126]
Il arrive que les contributeurs mettent des points adresses avec des numéros sans rue. Très bien.
Sauf que sans ure associée... Osmose râle avec raison.
Par contre un super-outil^^ pourrait les utiliser pour créer la relation.

Exemple ici : https://bano.openstreetmap.fr/fantoir/#insee=29233&tab=1

Par défaut on fabriquerait des doublons.
La réponse peut être : on laisse tomber, celui qui intégrera verra bien... à condition qu'il pense à charger les données de la zone.

**Comment by vdct** [comment]
C'est très hasardeux de demander à un algo de décider qu'un point d'adresse sans rue appartient à une rue plutôt qu'une autre. Ici rien ne peut égaler la jugeote des contributeurs, donc comme tu dis : on laisse tomber :)
