### ISSUE TITLE
Fantoir annulés non mis à jour

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#127]
Il y a des codes fantoir sur la page des Fantoir annulés que j'ai supprimé d'osm mais qui sont toujours presents dans la liste. (Normalement j'ai supprimé tous les premiers, departement de l'Ain 01.)
J'ai l'impression que ceux qui n'ont pas disparu se sont les codes liés à des communes qui n'existent plus.
Par exemple, Châtillon-en-Michaille https://bano.openstreetmap.fr/fantoir/index.html#insee=01091&tab=1 commune supprimée en janvier 2019.
Dans cumul_voies il doit y avoir des entrées avec insee_com=01091 mais ces entrées ne  doivent plus être mise à jour vu qu'il n'y a plus de commune 01091 ?
Je ne sais pas comment régler le problème : supprimer les entrées avec insee_com parmis une liste des commune qui n'existent plus mais est ce que les ref fantoir sont aussi lié à la nouvelle commune ? insee_com est obtenu grace à la position ou c'est seulement les 5 premiers caractères du fantoir ?

**Comment by vdct** [comment]
> J'ai l'impression que ceux qui n'ont pas disparu se sont les codes liés à des communes qui n'existent plus.
> Par exemple, Châtillon-en-Michaille https://bano.openstreetmap.fr/fantoir/index.html#insee=01091&tab=1 commune supprimée en janvier 2019.
> Dans cumul_voies il doit y avoir des entrées avec insee_com=01091 mais ces entrées ne doivent plus être mise à jour vu qu'il n'y a plus de commune 01091 ?

Oui bien vu, c'est bien ce qui se passe. Le process quotidien fonctionne commune par commune, et efface le contenu correspondant au moment d'injecter le contenu mis à jour. Les communes déléguées ne sont plus traitées, donc il n'y a pas d'occasion d'effacer le contenu lié.

> Je ne sais pas comment régler le problème : supprimer les entrées avec insee_com parmis une liste des commune qui n'existent plus mais est ce que les ref fantoir sont aussi lié à la nouvelle commune ? insee_com est obtenu grace à la position ou c'est seulement les 5 premiers caractères du fantoir ?

Aujourd'hui la liste des communes traitées par département n'est (vraisemblablement) pas prise au bon endroit. Pour des raisons historiques elle est constituée en prenant la liste des communes consultables sur cadastre.gouv.fr. Ca avait du sens tant qu'on s'appuyait sur les PDFs du cadastre, on se devait d'être cohérent entre communes disponibles et communes traitées. Désormais il faudrait s'appuyer sur la liste des communes du COG (qu'on a en base, ça tombe bien) en filtrant au moins les communes déléguées (typecom = 'COMD')

Par ailleurs je vais faire un ménage (manuel) des entrées de voies et adresses de source 'OSM' se référant aux communes déléguées, ça devrait fortement faire baisser la liste des FANTOIR annulés

**Comment by vdct** [comment]
J'ai purgé la BD des adresses liées à une commune déléguée. Il y a aussi maintenant un avertissement quand on arrive sur la page d'une commune déléguée, avec suggestion de bascule sur la page de sa commune parente (https://github.com/osm-fr/osm-vs-fantoir/issues/128)
