### ISSUE TITLE
commune sans date de rapprochement

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osm-vs-fantoir#13]
http://cadastre.openstreetmap.fr/fantoir/#insee=49018
pas de rapprochement ?
c'est surement lié mais la colonne "b" pour cette commune est a 0 ... alors la valeur de la colonne "a" est 135
http://cadastre.openstreetmap.fr/fantoir/stats_dept.html#dept=49

**Comment by vdct** [comment]
Résolu indirectement en corrigeant un nom de maison, qui faisait planter le traitement BANO sur la commune : 
http://www.openstreetmap.org/changeset/31419843
