### ISSUE TITLE
ref:FR:FANTOIR non rapprochés sur way et relations : pb de màj ?

### ISSUE THREAD

**Issue by thibdrev** [osm-fr/osm-vs-fantoir#130]
Hello, sur le tableau de synthèse des rapprochements FANTOIR de la commune de Lège-Cap-Ferret ([33236](http://bano.openstreetmap.fr/fantoir/#insee=33236&tab=1)) j'ai identifié des comportements bizarres  :

1. la voie "AV DE L OCEAN CAP FERRET" (332361215M) par exemple : sa [relation associatedStreet 12171725](https://www.openstreetmap.org/relation/12171725) existe depuis 4 jours mais n'est pas rapprochée.
2. la voie "ALL CHANTECLERC GRAND PIQUEY" (332360425D) est bien rapprochée, mais son "Libellé OSM" indiqué dans le tableau (Allée Chanteclerc PIQUEY) est différent de celui de son [way 34776192](https://www.openstreetmap.org/way/34776192) qui existe depuis 3 ans (Allée Chanteclerc). Par ailleurs ce way n'a jamais porté ce nom (Allée Chanteclerc PIQUEY) dans son historique OSM, du coup je suis paumé :) c'est un libellé BAN ?

Pour info l'entête de la page indique bien : 
- Dernier rapprochement BAN le | 15-01-2021 02:22:34
- Données OSM en date du | 15-01-2021 00:26:07

Any idea ?

**Comment by vdct** [comment]
bonjour @thibdrev 
Pour l'avenue de l'Océan elle n'est pas prise en compte car sa relation n'inclut aucun numéro d'adresse avec le rôle "house", or c'est par les numéros que l'on utilise les infos de la relation.
Pour l'allée Chanteclerc c'est en effet un bug d'affichage, le mot clé PIQUEY est utilisé dans les traitements et ne devrait pas être stocké dans le résultat. Merci du signalement, j'ouvre un [ticket dédié ](https://github.com/osm-fr/bano/issues/225)

**Comment by thibdrev** [comment]
Merci Vincent. 
Flûte, j'ai pris l'habitude de mettre le ref:FR:FANTOIR directement sur le way quand il n'y en a qu'un ou deux. Et de créer une relation dès qu'il y a plusieurs way ou que le name est susceptible d'être modifié par la suite. De mémoire c'est ce que recommande cquest.
J'ai également vu le lien "relation" du tableau de synthèse FANTOIR qui permet d'ajouter les adresses facilement avec JOSM, mais celui-ci créé systématiquement une nouvelle relation. Est-ce que j'ouvre un ticket pour proposer une amélioration afin que l'outil reparte de la relation le même ref:FR:FANTOIR si elle existe ? Sinon ça impose d'ajouter des points addr:housenumber à la main sans réelle valeur ajoutée (sauf quand les portails sont bien visibles et décalés des points BAN/cadastre).

**Comment by vdct** [comment]
Je t'invite à regarder la doc d'[associatedStreet](https://wiki.openstreetmap.org/wiki/FR:Relation:associatedStreet). Une relation sans rôle(s) "house" n'est pas valide, et c'est simplement pour ça que je n'en tiens pas compte dans BANO. Pour tes relations associatedStreet sans rôle house, tu peux :
- soit leur ajouter au moins 1 numéro de rue, et à partir de là l'outil d'intégration du tableau FANTOIR les reconnaîtra
- soit les supprimer et laisser l'outil te proposer leur création complète.

**Comment by thibdrev** [comment]
Ok c'est clair, merci. Le validateur de JOSM renvoie en effet une erreur lorsque le rôle house est manquant. J'avais pensé à l'astuce d'ajouter un seul point addr:housenumber pour contourner, mais ça ne me paraissait pas propre-propre. Mais si ça ne pose pas de problème aux outils de rapprochement FANTOIR alors pourquoi pas.
