### ISSUE TITLE
Rendu/onglet expérimental : supprimer les old_name

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#134]
Hello,

Sur le rendu (et dans l'onglet "dans osm/inconnu de FANTOIR), les old_name apparaissent (en "erreur" vert turquoise sur le rendu). Exemple pour https://www.openstreetmap.org/way/583758206

![Screenshot_2021-01-31 https tile openstreetmap fr](https://user-images.githubusercontent.com/36087963/106381823-caf4b100-63bb-11eb-9d50-10123fc7ae9d.png)

Il y a facilement moyen de les retirer du rendu (et de l'onglet) ?

Merci pour les réponses, quelles qu'elles soient.

**Comment by vdct** [comment]
Je comprends l'inconvénient, malheureusement je n'ai pas de solution dans le sens de ce que tu demandes. 
L'idée de départ des exports BANO c'est de fournir la liste la plus exhaustive possible des adresses au numéro mais aussi à la rue, pour notamment le géocodage. Hors il arrive que l'adresse qu'on cherche soit connue avec un ancien nom, c'est pourquoi on propose dans BANO les anciens noms, et aussi les noms alternatifs (Place Charles de Gaulle/Place de l'Etoile par exemple, à Paris VIII) quand OSM en dispose. 
Cependant dans BANO on perd le lien vers les objets OSM (on ne garde pas leurs identifiants) et on perd aussi la nature du nom (alternatif, old, etc). Donc au moment d'identifier les noms non rapprochés il n'est plus possible de lier à l'objet initial d'OSM (ici Avenue du Général De Gaulle via le way 583758206) pour dire : "alors j'ai l'Avenue de la Gare en non rapproché mais en fait ça compte pas car c'est le old_name d'une voie rapprochée". Et comme on ne garde pas les identifiants il est aussi impossible pour l'instant d'organiser la liste des noms de cet onglet avec les statuts comme sur les autres onglets. Ca permettrait de griser et donc visuellement de ne plus se demander si on a déjà analysé le cas qu'on observe.
En te répondant je réalise que c'est pas forcément compliqué finalement (je m'étais toujours figuré le contraire) donc [nouveau ticket](https://github.com/osm-fr/osm-vs-fantoir/issues/133)

**Comment by deuzeffe** [comment]
Hello @vdct 

(je lague).

Merci pour tes claires explications. Et merci pour le grisage à venir des "trucs déjà vus à ne pas prendre en compte" dans l'onglet expérimental.

Toujours dans cet onglet, les emprises des écoles ce sont des doigts qui ont fourché, ou bien ?

**Comment by vdct** [comment]
Jamais les doigts ne fourchent, parbleuuuu ! :smile:
 
FANTOIR est une compilation parfois un peu à la Prévert, et dans certaines communes les écoles & groupes scolaires en font partie. On les retrouve donc comme candidats à rapprochement, comme parfois les stations de metro, les parkings ou les centres commerciaux. Comme l'idée générale c'est de confronter OSM à cet inventaire et s'en rapprocher le plus possible, les écoles font partie des entités candidates au rapprochement. Donc se retrouvent possiblement dans le dernier onglet quand rien dans le FANTOIR de la commune ne permet de les rapprocher. Mais ça n'est pas le cas partout, par exemple à Cergy : https://bano.openstreetmap.fr/fantoir/#insee=95127&tab=3

**Comment by deuzeffe** [comment]
Ooops :D

Vu, merci !

On feeerme !
