### ISSUE TITLE
Numéros avec bis et ter marqués comme manquants et suggérés sous la forme N b et N t

### ISSUE THREAD

**Issue by arnaud-jacquemin** [osm-fr/osm-vs-fantoir#135]
Bonjour,

Sur le wiki j’ai trouvé ce tableau de normalisation des numéros pour les adresses : https://wiki.openstreetmap.org/wiki/FR:Adresses#Normalisation_du_suffixe_des_n.C2.B0_de_rue.5B1.5D  qui recommande la notation "1 bis" et "1 ter".

Pourtant, quand je saisis des adresses sous la forme "1 bis", donc en respectant cette norme, FANTOIR continue à me les signaler comme manquantes et la télécommande JOSM me les rajoute en "1 b". Un détail m’échapperait-il ?  J’ai laissé passer plusieurs nuits après mes modifications.

Le premier cas que j’ai constaté est le 143 bis, Rue Flament Reboux, Lambersart, saisi il y a un mois : https://www.openstreetmap.org/node/8287457477
Pourtant, via FANTOIR à l’adresse https://bano.openstreetmap.fr/fantoir/#insee=59328&tab=1, si je clique sur le lien de la colonne "adresses à intégrer", un point "143 b" m’est suggéré.

Un autre exemple avec une saisie qui n’est pas de moi : l’adresse 2 bis Rue Roure à Lambersart aurait 6 ans si je comprends bien : https://www.openstreetmap.org/node/3177813217  
Pourtant les liens "adresses à intégrer" pour la rue Roure me poussent à nouveau une adresse "2 b" (ainsi que "20 b" alors que le 20 bis existe, idem pour 20 ter).

Le problème semble aussi se poser si l’espace n’est pas saisi entre le chiffre et le bis. Par exemple, un 2bis dans la même commune : https://www.openstreetmap.org/way/249228469 => la télécommande pousse aussi un "2 b" dans ce cas.

Il me semble que les adresses saisies en "bis" sont systématiquement ignorées lors de la comparaison OSM / FANTOIR.

J’espère que ce signalement vous sera utile, et vous remercie pour cet outil bien pratique !

**Comment by vdct** [comment]
Bonjour Arnaud et merci pour cette analyse poussée. 

> Il me semble que les adresses saisies en "bis" sont systématiquement ignorées lors de la comparaison OSM / FANTOIR.

Malheureusement le constat qui peut être fait sur Lambersart ne peut pas être généralisé. Les adresses proposées pour l'intégration sont issues de la BAN, dans laquelle on trouve aussi bien des "bis" que des "b", des "ter" comme des "t". Il est donc impossible a priori de décider qu'il y a une équivalence entre un "143 b" et un "143 bis". 
Une autre approche du sujet consiste à permettre une qualification des adresses, par exemple pour indiquer qu'un "143 b" est en fait un doublon d'un "143 bis" et par suite éviter de le proposer à l'intégration. C'est l'objet de [ce ticket](https://github.com/osm-fr/osm-vs-fantoir/issues/74) qui mériterait un peu de dépoussiérage

**Comment by vdct** [comment]
@arnaud-jacquemin 
 
> Malheureusement le constat qui peut être fait sur Lambersart ne peut pas être généralisé. Les adresses proposées pour l'intégration sont issues de la BAN, dans laquelle on trouve aussi bien des "bis" que des "b", des "ter" comme des "t". Il est donc impossible a priori de décider qu'il y a une équivalence entre un "143 b" et un "143 bis".

En y re-réflechissant j'ai changé d'approche et tenté de traiter le souci à la source, dès la prise en compte des adresses BAN en entrée des processus BANO. Je vous laisse tester sur Lambersart, où la mise à jour est effective. Si vous testez avant demain lundi sur une autre commune, il vous faudra d'abord lancer manuellement la mise à jour BANO sur la commune, via le 2e bouton en partant de la gauche, en haut à gauche de la page https://bano.openstreetmap.fr/fantoir/
Merci pour vos retours

**Comment by arnaud-jacquemin** [comment]
Bonjour vdct, désolé pour le délai de réponse ! Merci pour l'attention portée à ma demande !

Je confirme que OSM vs. FANTOIR ne me propose plus de "bis" doublons pour les voies Rue Flament Reboux et Rue Roure, alors que c'était le cas avant !

Le problème me semble donc résolu, merci !
