### ISSUE TITLE
Fuseau horaire UTC+1

### ISSUE THREAD

**Issue by py-b** [osm-fr/osm-vs-fantoir#138]
Mettre les heures figurant sur les pages au fuseau horaire de Paris (UTC+1) ?

**Comment by vdct** [comment]
Ca me paraît plus simple, plus permanent (en fonction des heures d'hiver et d'été) et plus universel (il y a des contributions ultra-marines) de mentionner que les heures sont en UTC comme sur le site osm.org, notamment pour l'horodatage des changesets

**Comment by py-b** [comment]
Effectivement l'argument se tient. Merci pour ta réponse.
