### ISSUE TITLE
osm-vs-BAN

### ISSUE THREAD

**Issue by operon** [osm-fr/osm-vs-fantoir#14]
Dans cetains endroits, la BAN semble en avance sur dgfip

En effet le calque BANO affiche des N° en gris alors que rien en rouge ou bleu
https://www.openstreetmap.org/#map=17/46.67760547055098/-1.3006454698615557

sur http://cadastre.openstreetmap.fr/fantoir/#insee=85046 onflet sans rapprochement et sans N° les rues sont presentes mais sans coordonnées pour passer en édition.

Il pourrait être interessant pour ces voies, recuperer les coordonnées dans la BAN pour pour pouvoir faire des liens d'édition et ainsi completer OSM

**Comment by operon** [comment]
autre endroit il y a de l'avance : https://www.openstreetmap.org/#map=18/47.514721/-0.583685

**Comment by vdct** [comment]
Clos par le remplacement de la source Cadastre par la source BAN fin 2020
