### ISSUE TITLE
ajout lieu-dit sans devoir faire des copier/coller

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#141]
avec l'outil précédent (cadastre.openstreetnap.fr) il était possible d'importer une couche avec les lieux-dit, pratique pour éviter de devoir copier/coller ceux-ci
est-il possible de prévoir cela un peu comme on a un lien pour ajouter le calque d'une rue ?
je n'ai pas d'avis si ce serrait mieux un lien par place=* ou un par catégorie (par ex tous les lieux habités) ou pour tous

**Comment by vdct** [comment]
Rendu possible par #151 via un export CSV
