### ISSUE TITLE
associatedStreet sans street

### ISSUE THREAD

**Issue by Bibi56** [osm-fr/osm-vs-fantoir#145]
Sur Lanester, j'ai voulu ajouter le 

  | Square Georges Bizet
-- | --

https://bano.openstreetmap.fr/fantoir/index.html#insee=56098&tab=1

Un clic plus tard je me retrouvais avec une relation associatedStreet (normal), avec un point d'adresse (normal).
Mais 0 street.

Comme je n'ai pas compris (la voie existe bien et c'est une highway=residential, pas une place), je ne corrige pas histoire de laisser investiguer.

**Comment by vdct** [comment]
Joli cas limite, merci :)
Il y a une heuristique pour trouver les filaires de voie à ajouter à la relation. Je pars du principe que l'emprise de ces voies intersecte l'emprise formée par le nuage de points d'adresse de ladite voie. Hors dans le cas du Square Bizet, on n'a qu'un seul point d'adresse (maigre nuage) et en plus il n'est pas inclus dans la bbox formée par le way highway. Donc voie non trouvée...
J'ai modulé l'heuristique en fabriquant artificiellement une petite zone autour de chaque point d'adresse, ce qui donnera un peu plus de chance de trouver un peu de surface commune entre numéros et filaire. Sur ton exemple désormais ça fonctionne

**Comment by Bibi56** [comment]
Oui, on va avoir du mal à trouver plus limite, merci pour la correction.
