### ISSUE TITLE
Voie rapprochée et validée mais numéros non importés

### ISSUE THREAD

**Issue by FredericBourgeon** [osm-fr/osm-vs-fantoir#149]
Dans la commune de Lampaul-Ploudalmézeau (code INSEE 29099), certaines voies à adresses numérotées sont indiquées comme rapprochées dans l'outil FANTOIR-OSM tandis que les numéros de rue ne sont pas importés.

Une vérification de l'import des noeuds d'adresse ne devrait-elle pas être menée avant de confirmer le rapprochement d'une voie ?

Exemple, place du bourg à Lampaul-Ploudalmézeau :
- https://www.openstreetmap.org/#map=19/48.56087/-4.65436
- http://bano.openstreetmap.fr/fantoir/#insee=29099&tab=1

**Comment by vdct** [comment]
Ce qu'on appelle "rapproché" ne concerne que les noms de rue. Le but initial de l'outil était d'avoir une vision simple & rapide des noms de rues manquants dans OSM. Le distingo rues avec adresses/ rues sans adresses permettait de mettre plus d'énergie sur les 1ers fin de booster le contenu Adresses exporté par BANO. Donc pas de bug ici, juste un vocabulaire historique qui peut prêter à confusion. Suggestions bienvenues pour le faire évoluer !
