### ISSUE TITLE
URL vers le cadastre?

### ISSUE THREAD

**Issue by bagage** [osm-fr/osm-vs-fantoir#15]
À la manière de celles déjà présentes (ORG, FR, BANO, JOSM, ID, P2), avoir un lien directement vers la voie sur le cadastre. L'équivalent de :

* se rendre sur http://cadastre.gouv.fr
* rentrer le nom de la voie
* rentrer la ville + code postale
* sélectionner Rechercher
* sélectionner le premier (?) résultat de la liste.

Je sais pas si c'est possible (dans l'absolu, tout est possible... ;-)) ?

**Comment by vdct** [comment]
http://cadastre.gouv.fr a une logique de session, avec cookie associé, expiration... Il faudrait au moment du clic avoir une session active pour que ça fonctionne. Beaucoup plus complexe que ce qui est déjà permis par l'existant, via le lien JOSM : il suffit d'avoir en fond de plan le Cadastre pour avoir un résultat quasi identique à ta demande.
Pour ajouter le Cadastre dans JOSM, voir ce message : https://lists.openstreetmap.org/pipermail/talk-fr/2015-February/075223.html

**Comment by bagage** [comment]
La piste JOSM est intéressante, je l'ai explorée plusieurs fois mais malheureusement elle ne me convient pas suffisamment, principalement parce que j'utilise beaucoup le bouton "S'informer" sur les maisons, pour vérifier le nom de la rue lorsque celui-ci n'est pas affiché... puis j'aime vraiment bien iD ;-). 
Bon, en attendant je vais continuer avec mes onglets ; si tu veux fermer le ticket je t'en prie, sinon j'y reviendrai (peut-être) plus tard.

**Comment by bagage** [comment]
Une solution intermédiaire pourrait être d'utiliser le rendu WMS du cadastre tms.cadastre.openstreetmap.fr ? Si on peut lui donner un zoom / latitude / longitude, ça serait super !

**Comment by vdct** [comment]
Il faudrait adapter le code de la page tms.cadastre.openstreetmap.fr pour qu'elle soit bien centrée & zoomée. Rien d'impossible, mais fonctionnellement, ça ne t'apporte pas plus que le même calque dans JOSM (toujours lui :) ) car on ne peut pas plus interroger les infos de parcelles.

**Comment by bagage** [comment]
Oui, c'est pas une solution 100% satisfaisante, mais :+1: 
* Plus il y a d'outils à disposition des contributeurs, plus ils trouveront chaussure à leur pied
* Je sais que beaucoup de gens utilisent JOSM, mais pour moi c'est simplement pas possible - je préfère de très loin iD et j'y suis bien plus efficace ;)
* On ne peut pas interroger les parcelles, mais finalement selon les communes ça peut ne pas être nécessaire (certaines communes "labelisent" correctement toutes les voies nommées) - quand on corrige une telle commune entièrement, se passer du cadastre c'est top !
* Le site du cadastre est, d'un point de vue ergonomie, catastrophique (gestion du zoom, limité à une seule commune...), donc avoir une alternative "web" un peu plus moderne ferait gagner un paquet de temps (pour ceux qui n'utilisent pas JOSM bien sûr).

Après je n'ai pas du tout idée du travail nécessaire pour faire fonctionner le centrage & zoomage, mais ça me paraît plus simple que d'utiliser le site officiel du cadastre

**Comment by tyndare** [comment]
Si tu a juste besoins du fond de carte du cadastre tu peux l'afficher directement dans iD:
Dans les icônes sur la droite, il faut cliquer sur "Paramètres du fond de carte"
Choisir l'option "Personnalisé"
Et rentrer l'url suivante: http://tms.cadastre.openstreetmap.fr/*/tout/{z}/{x}/{y}.png
Par contre je n'ai pas trouvé comment faire pour enregistrer cette configuration pour qu'elle reste activée par défaut pour mon profile, il faut peut être ouvrir un ticket iD ;-)

**Comment by bagage** [comment]
Ça pourrait... mais non plus :-). Avoir tous les objets qui s'affichent au dessus du fond de carte fait que les noms de voies sont non lisibles. Et comme de toute manière il faut l'imagerie satellite pour compléter les chemins manquants et autre, pour moi le plus utile c'est d'avoir 3 fenêtres : 
* le site web osm-vs-fantoir, avec la liste des erreurs pour une commune
* l'éditeur iD avec l'imagerie satellite, centrée sur une erreur
* le cadastre centrée sur la même erreur (si iD boug alors, je bouge aussi le cadastre, et réciproquement.)
L’intérêt (pour moi) c'est que tout est visible à l'écran en même temps à tout moment. J'ai un grand écran, autant en profiter ;-).

**Comment by tyndare** [comment]
Tu pourrais aussi masquer les éléments OSM pour avoir le fond de carte bien visible et afficher autant d'iD que tu veux.

**Comment by bagage** [comment]
En effet, c'est une solution qui a le mérite d'exister, merci pour l'astuce. Mais je sais pas si osm-vs-fantoir serait capable d'avoir deux sessions iD en simultanné (une pour l'édition, l'autre pour le cadastre sans éléments affichés).

**Comment by bagage** [comment]
Après quelque temps d'utilisation, je me rend compte que cette solution convient à 99% de mes besoins : une seule fenêtre avec le cadastre en fond, le raccourci "W" pour alterner le rendu filaire / semi-plein des formes ... et [bientôt le raccourci "s"](https://github.com/openstreetmap/iD/pull/2854) pour alterner rapidement entre Bing et le rendu du cadastre !
