### ISSUE TITLE
Ajouter les coordonnées dans l'export csv

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#151]
Avoir des coordonnées dans l'export csv des communes permettrait de le donner à JOSM, mettre les points dans le plugin todo pour les passer en revue.
J'ai l'impression en regardant requete_fantoir.py et les requètes sql comme voies_adresses_non_rapprochees_insee.sql que les coordonnées d'une adresse sont déjà présentes dans le résultat de la requête sql et donc qu'il suffit d'ajouter les colonnes dans l'export.
Cela permettrait de répondre à #141 en permettant l'export des lieux dit avec des coordonnées. On aurait nom et coordonnées approximatives, à l'utilisateur de revoir les coordonnées et de choisir le bon place=*

Les coordonnées dans le nouveau csv des voies récentes manquantes peuvent être utiles aussi. Et un csv avec coordonnées dans le top adresses manquantes aussi :)

**Comment by vdct** [comment]
J'ai amorcé avec l'ajout dans les 6 onglets des communes. Bémol pour celui des voies non rapprochées sans adresses : on n'a pas de géométrie à proposer, donc "None,None" sort à la place

**Comment by Olyon** [comment]
Super, ça marche par contre JOSM ne veut pas de csv avec des tab comme séparateurs... mais accepte les , ou ;
donc une petite modification pour remplacer les \t par des ; simplifierait la vie :)

Les colonnes du csv n'ont pas toujours le bon nom, ça dépend de l'onglet exporté.
Pour ce problème et pour le problème des None, la fonction format_csv() pourrait être modifiée en ajoutant tab comme argument et faire un export différent suivant la valeur de tab.

(Je n'ai pas testé)

comme ça :
def format_csv(tab, fetch):
    if tab == 0 :
        return ('Code FANTOIR;Date création;Libellé FANTOIR;Libellé BAN;Lon;Lat\n'+'\n'.join([f"{c[0]};{c[1]};{c[2]};{c[3]};{c[4]};{c[5]}" for c in fetch]))
    elif tab == 1 or tab == 3 :
        return ('Code FANTOIR;Date création;Libellé FANTOIR;Libellé OSM;Lon;Lat\n'+'\n'.join([f"{c[0]};{c[1]};{c[2]};{c[3]};{c[4]};{c[5]}" for c in fetch]))
    elif tab == 2 :
        return ('Code FANTOIR;Date création;Libellé FANTOIR\n'+'\n'.join([f"{c[0]};{c[1]};{c[2]}" for c in fetch]))
    elif tab == 4 :
        return ('Code FANTOIR;Date création;Libellé FANTOIR;Libellé Cadastre;Lon;Lat\n'+'\n'.join([f"{c[0]};{c[1]};{c[2]};{c[3]};{c[4]};{c[5]}" for c in fetch]))
    elif tab == 5 :
        return ('Code FANTOIR;Date création;Libellé FANTOIR;Type OSM : Libellé OSM;Lon;Lat\n'+'\n'.join([f"{c[0]};{c[1]};{c[2]};{c[3]};{c[4]};{c[5]}" for c in fetch]))
    elif tab == 6 :
        return ('Libellé OSM;Lon;Lat\n'+'\n'.join([f"{c[3]};{c[4]};{c[5]}" for c in fetch]))

Il faut modifier l'appel à la fonction : 
print(format_csv(tab, data_columns[tab]))

**Comment by vdct** [comment]
Merci @Olyon 
J'ai repris ton commentaire façon Pull Request tel que et ça fonctionne :+1: 
Je te laisse tester

**Comment by Olyon** [comment]
ça marche très bien !
Il n'y a que des colonnes pleines.

Je m'en sers comme j'ai mis dans le 1er message : Dans josm, remplacer "Libellé BAN" par "name", je mets tout les points dans une relation sans tag, plugin todo, copier coller des noms et à la fin je selectionne les membres de la relation créée au depart et je supprime le tout.
