### ISSUE TITLE
Qualification des anomalies des numéros d'adresse : adresse de la commune adjacente

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osm-vs-fantoir#152]
Cas exemple : https://bano.openstreetmap.fr/fantoir/numeros.html?insee=69381&fantoir=693812005Y&source=BAN&tab=1

les numéros impairs du boulevard de la croix rouge à Lyon sont dans le 4ème arondissement (code insee 69384) pourtant fantoir les référence dans 69381.

Je suggère d'ajouter ce type d'anomalie dans la liste déroulante

**Comment by vdct** [comment]
Joli cas :)
Merci @nuxper , je viens de rajouter un item "Adresse en dehors de la commune", volontairement un peu générique.

**Comment by nuxper** [comment]
Merci !
