### ISSUE TITLE
Rapprochement 6 a -> 6A (ignorer espaces et casse)

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osm-vs-fantoir#154]
Cas observé à Lyon par exemple https://bano.openstreetmap.fr/fantoir/#insee=69382&tab=1 pour le Cours Bayard

FANTOIR contient "6 a", "6 b" et "6 c" et openstreetmap contient "6A", "6B" et "6C".
Le contenu d'openstreetmap semble respecter les conventions établies dans https://wiki.openstreetmap.org/wiki/FR:Adresses#Normalisation_du_suffixe_des_n.C2.B0_de_rue.5B1.5D

Comportement actuel : l'algorithme propose d'intégrer "6 a", "6 b" et "6 c"
Comportement attendu : l'algorithme détecte la correspondance et ne propose pas d'intégration.

**Comment by vdct** [comment]
C'est normalement corrigé désormais, il y avait pas mal de cas de test dans l'arrondissement :+1:

**Comment by nuxper** [comment]
Génial c'est bon !
merci !
