### ISSUE TITLE
requete_fantoir.py répond avec erreur 500

### ISSUE THREAD

**Issue by ray66** [osm-fr/osm-vs-fantoir#156]
De temps en temps, la page [Correspondance entre FANTOIR et OSM](https://bano.openstreetmap.fr/fantoir-pr/index.html) ne répond pas quand on entre le code INSEE d'une commune. Le problème persiste pendant plusieurs heures voir jours puis se débloque sans raison apparente. Une analyse du traffic réseau montre que `requete_fantoir.py` répond avec une erreur HTTP 500, par ex. :

    https://bano.openstreetmap.fr/fantoir-pr/requete_fantoir.py?insee=66172

 Le problème a été constaté avec les communes du département 66, mais semble concerner toutes les communes.

Environnement: 

    Linux Debian Bookworm
    Firefox 91.4.0esr / Chromium 93.0.4577.82

**Comment by vdct** [comment]
Ca a l'air lié à la requête que tu utilises dont l'URL contient fantoir **-pr**. C'est une vieille URL de travail, qui n'a pas vocation à être utilisée en temps normal. Si tu lances https://bano.openstreetmap.fr/fantoir/requete_fantoir.py?insee=66172 à la place (sans le '-pr'), à l'instant ça fonctionne

**Comment by ray66** [comment]
En effet. Je m m'excuse pour le bruit.
