### ISSUE TITLE
place de l'église non rapprochée

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#167]
le comparateur bano osm<>fantoir ne fait pas un rapprochement automatique Place de l'Église <> PL DE L'EGLISE ?
https://www.openstreetmap.org/way/52171587 https://bano.openstreetmap.fr/pifometre/#insee=86111&tab=2
il y a [PLACE PL](https://github.com/osm-fr/bano/blob/master/bano/dictionnaires/abrev_type_voie.txt#L226) dans le dictionnaire
faut-il ajouter PLACE PL. (avec un point comme dans le libellé fantoir) ? c'est l'accent de l'église ?
tes lumières sont les bienvenues :)

**Comment by Olyon** [comment]
https://bano.openstreetmap.fr/pifometre/#insee=86279&tab=1
Dans la bonne commune il y a rapprochement :)

**Comment by vdct** [comment]
> faut-il ajouter PLACE PL. (avec un point comme dans le libellé fantoir) ? c'est l'accent de l'église ?

Non, les 2 sont gérés. Comme vu par @Olyon le rapprochement est ok, je ferme
