### ISSUE TITLE
lien clicable vers l'objet osm "inconnu de fantoir"

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#168]
dans l'onglet des objets osm inconnu de fantoir, actuellement on a un lien vers osm.org oü ensuite on clique sur editer, puis on zoom et clique sur l'objet
puisqu'une fois sur 2 cela conduit à éditer cet objet, il serrait pratique d'avoir un lien vers l'objet sur son libellé
dans celui des onglets rapprochés éventuellement aussi même si je ne vois par contre pas de cas d'usage pour le lien dans ces onglets

**Comment by vdct** [comment]
On ne garde pas dans BANO de lien vers les objets OSM via leur identifiant, qui peuvent être multiples pour un même nom qu'on tente de rapprocher. Donc impossible de dire à JOSM quel objet sélectionner. Cependant à l'arrivée dans JOSM la vue est centrée sur les objets portant le nom en question, l'effort à faire pour trouver de quoi on parle est donc minime

**Comment by deuzeffe** [comment]
Et on rappellera que l'onglet 6 est expérimental/fourre-tout (ce n'est pas une critique !) et qu'il prend en compte plein de trucs (dont les old_name). Enfin, de ce que j'ai observé dans ma zone de confort. J'ai bon @vdct ?

**Comment by Marc-marc-marc** [comment]
si tu n'as pas l'id dans la base, tu ne peux évidement pas l'afficher en lien.
bien évidement il peux y avoir plusieurs id, mais en avoir un id aurait été pratique
ex "Route Nationale" https://bano.openstreetmap.fr/pifometre/#insee=86111&tab=6 introuvable avec name="Route Nationale"
mais si cela ne cherche pas que les name, alors j'ai trouvé.... un addr:street sur un POI

**Comment by vdct** [comment]
> expérimental/fourre-tout

Tout à fait !

> bien évidement il peux y avoir plusieurs id, mais en avoir un id aurait été pratique

Je comprends que ça aurait été pratique. Faute de cette possibilité, le moteur de recherche de JOSM permet de finir le job
