### ISSUE TITLE
Lieux-dits nord/sud/est/ouest

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#170]
Hello,

Encore moi qui viens tenter de pourrir l'été des chefs du code BANO ^^

J'ai lu il y a longtemps (https://forum.openstreetmap.fr/t/adresses-lieux-dits-cadastre/2112/4), que les appellations nord/sud/est/ouest n'avaient aucune signification sur le terrain et avaient été (ré)introduites par les ancêtres successifs de la DGFiP "pour raisons internes" (en gros). Et qu'il ne fallait donc pas les intégrer à osm. Soit, faut faire avec.

Elles sont donc dans FANTOIR (*) et bien sûr à peu près introuvables sur le terrain. Donc, ma tendance est de les marquer comme "Ancien nom supprimé sur le terrain"; Certes, ça va supprimer la tentative de rapprochement (je suppose...) mais ce n'est qu'un reflet éloigné de la réalité. Est-ce que je continue à les marquer comme ça ?

D'un autre côté, effectivement, la liste du Statut FANTOIR n'est pas optimale pour les lieux-dits, cf https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO#Cas_des_lieux-dits. L'améliorer ? Supprimer ces appellations des voies à rapprocher (au risque de faux -)? Autre ?

Merci pour les réponses.

(*) qui est censé vivre ses derniers jours sous cette forme, d'après un des chefs d'ici, si j'ai bien tout lu et tout compris.

**Comment by vdct** [comment]
(hop hop téléportation de l'issue :rocket:  )

> Donc, ma tendance est de les marquer comme "Ancien nom supprimé sur le terrain"; Certes, ça va supprimer la tentative de rapprochement (je suppose...) mais ce n'est qu'un reflet éloigné de la réalité. Est-ce que je continue à les marquer comme ça ?
> 

Les marquer ne va pas les exclure des tentatives de rapprochement. Le premier but du marquage c'est le repos des yeux : une ligne grisée indique avant tout par sa couleur que quelqu'un s'est déjà cassé la tête à identifier un problème lié à cette voie/ce lieu-dit, inutile donc d'y revenir

> D'un autre côté, effectivement, la liste du Statut FANTOIR n'est pas optimale pour les lieux-dits, cf https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO#Cas_des_lieux-dits. L'améliorer ? Supprimer ces appellations des voies à rapprocher (au risque de faux -)? Autre ?
> 

C'est tout simple de rajouter par exemple une nouvelle catégorie "point cardinal superflu" (ou tout autre libellé un peu mieux inspiré) dans la liste des anomalies.

> (*) qui est censé vivre ses derniers jours sous cette forme, d'après un des chefs d'ici, si j'ai bien tout lu et tout compris.

Y a un peu de répit : https://www.data.gouv.fr/fr/datasets/objet-disparition-des-fichiers-fantoir-fimoca-et-fimoct-en-fevrier-2023-mise-en-place-des-fichiers-topo-structures-uamissions-competences-et-acheminement/ mais je commence à regarder le remplaçant ("TOPO")

**Comment by deuzeffe** [comment]
> (hop hop téléportation de l'issue :rocket: )

Oooops. A promis, a ref'rai pu.

> Les marquer ne va pas les exclure des tentatives de rapprochement. Le premier but du marquage c'est le repos des yeux : une ligne grisée indique avant tout par sa couleur que quelqu'un s'est déjà cassé la tête à identifier un problème lié à cette voie/ce lieu-dit, inutile donc d'y revenir

Compris, chef !

> C'est tout simple de rajouter par exemple une nouvelle catégorie "point cardinal superflu" (ou tout autre libellé un peu mieux inspiré) dans la liste des anomalies.

Yep. Je manque d'inspiration, là :( 

> Y a un peu de répit : https://www.data.gouv.fr/fr/datasets/objet-disparition-des-fichiers-fantoir-fimoca-et-fimoct-en-fevrier-2023-mise-en-place-des-fichiers-topo-structures-uamissions-competences-et-acheminement/ mais je commence à regarder le remplaçant ("TOPO")

Bon, j'ai donc encore un peu de "taf" jusqu'en 2023. Ce qui te laisse le temps de regarder l'aspect du nouveau fichier...

Encore une fois, merci pour ta patience et ta pédagogie ;)

**Comment by vdct** [comment]
@deuzeffe j'ai ajouté le libellé, en fin de liste. Yapluka :)

**Comment by deuzeffe** [comment]
Vu ! Marfi M'sieur :+1:
