### ISSUE TITLE
Voies numérotés absentes de FANTOIR et BANO présentes dans la BAN et la BD Topo

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#172]
Hello,

Je rebondis <BoingBoing> sur un vieux sujet https://github.com/osm-fr/osm-vs-fantoir/issues/95

Soit la commune 87104

Le FANTOIR T2 2022 donne https://bano.openstreetmap.fr/pifometre/index.html#insee=87104&tab=0 soit pas grand chose.

Mais si on regarde la BAL de la commune en ligne, https://adresse.data.gouv.fr/base-adresse-nationale/87104#11.61/45.716/1.8315 on voit qu'elle est plus que fournie (avec certification commune > 90 %).

Hypothèses explicatives : 

- la déclaration des voies par la commune auprès de la DGFiP sera prise en compte dans le FANTOIR T3 2022 ;
- la commune n'a rien déclaré à la DGFiP (1) et compte sur le fichier de la BAN pour faire connaître ses voies (2) ;
- BANO a un périmètre de récolte des données qui m'échappe ;
- les réponses D

Question subsidiaire (et rhétorique) : comment je fais pour dégommer du rouge invisible et nommer correctement les voies de la commune ? (hint: fichier bal et choisir la bonne projection...)

(1) L'évolution de FANTOIR en TOPO risque de ne rien changer puisque tout vient de la DGFiP

(2) curieusement, la commune n'a pas de BAL mais a certifié des adresses qui sont sourcées "commune" dans le fichier de bal https://plateforme.adresse.data.gouv.fr/ban/communes/87104/download/csv-bal/adresses

**Comment by vdct** [comment]
Je penche pour un ~~retard~~ délai dans la remontée vers la DGFIP. De là à parier pour T3 2022, c'est aventureux. Wait & see.
D'ici là, si pas de noms de voie dans FANTOIR, alors pas de présence dans Pifomètre. C'est bancal mais c'est comme ça, FANTOiR nous sert de dorsale pour l'instant.
En attendant, pour intégrer tes adresses, tu peux t'aider aussi du rendu BANO (https://tile.openstreetmap.fr/~cquest/leaflet/bano.html#19/45.71919/1.83143)

**Comment by deuzeffe** [comment]
J'ai pris le fichier csv de la commune : c'est plus simple pour mes yeux... Et le rendu BANO a toujours des pb de lenteur :(

RdV en octobre pour la fin du suspense; Ou pas;

**Comment by deuzeffe** [comment]
> * la déclaration des voies par la commune auprès de la DGFiP sera prise en compte dans le FANTOIR T3 2022 ;

C'était bien ça : déclarations de fin octobre 2022, prises en compte dans la situation de novembre (fin d'fils).

Et Nedde a récupéré de vrais FANTOIR à la place des "voie sans FANTOIR" : ça maaarche !

Encore énormément merci pour le boulot, @vdct !
