### ISSUE TITLE
Même voie numérotée-sans FANTOIR/non numérotée-avec FANTOIR

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#180]
Hello,

Bizarrerie (pour debug ?)

Soit la commune : https://bano.openstreetmap.fr/pifometre/index.html#insee=87181&tab=3
Onglet 0 : Voie sans FANTOIR		CHE BELLE VUE	Chemin de Belle Vue
Onglet 3 : 871810002G	1990-10-29	CHE DE BELLEVUE	Chemin de Bellevue
(la vue JOSM pour les 2 renvoie bien au même way)

Est-ce la divergence d'orthographe qui empêche le "rapprochement" ? Est-ce le fait qu'il y a actuellement des numéros ? Même pb (et remède) que https://lists.openstreetmap.org/pipermail/talk-fr/2022-September/105791.html ? Autre ?

**Comment by vdct** [comment]
Oui la divergence d'orthographe suffit à empêcher le rapprochement. Reste à savoir quelle orthographe est la bonne :
- si c'est celle de la BAN, alors l'intégrer comme nom de voie avec un ref:FR:FANTOIR va tout raccorder. C'est le cas qu'on a discuté sur talk-fr
- si c'est celle de FANTOIR, alors pas de magie. Pas besoin ici de ref:FR:FANTOIR, juste les ways OSM avec la meêm orthographe et le rapprochement se fera. Mais comme ça ne collera pas avec la BAN, la voie sera considérée "sans adresses" donc dans l'onglet 3, et subsistera dans l'onglet 0 le "doublon" BAN mal orthographié. Ca mériterait un type "Voie sans FANTOIR mal orthographiée"...si on pouvait qualifier les voies sans FANTOIR, ce qui n'est pas le cas. Ca n'empêche pas d'ajouter les n° d'adresse histoire que la voie reconnue passe de l'onglet 3 à l'onglet 1 ;)

**Comment by deuzeffe** [comment]
J'ai fait ça.:
> * si c'est celle de la BAN, alors l'intégrer comme nom de voie avec un ref:FR:FANTOIR va tout raccorder. C'est le cas qu'on a discuté sur talk-fr

Et ça : 
> * Ca n'empêche pas d'ajouter les n° d'adresse histoire que la voie reconnue passe de l'onglet 3 à l'onglet 1 ;)

C'est donc à peu près d'équerre :)
Merci pour ton avis !
