### ISSUE TITLE
Folles (87067) : rapprochements hasardeux ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#181]
Hello,

Pour https://bano.openstreetmap.fr/pifometre/index.html#insee=87067&tab=3, il y a des rapprochements bizarres : 
- AUVERGNE	Rue de la Garde
- LE PRE MERLE	Rue de la Petite Garde
- LE VIADUC	Place de l'Église
- PONT MAZERAS	La Petite Rue

Alors que dans l'onglet 0, on a (avait) : 
- AUVERGNE	Auvergne
- PONT MAZERAS	Pont de Mazeras

Et dans l'onglet 1 : 
- PL EGLISE	Place de l'Église
- RUE GARDE	Rue de la Garde
- RUE PETITE GARDE	Rue de la Petite Garde

Quelle est donc cette sorcellerie ?

**Comment by vdct** [comment]
> Quelle est donc cette sorcellerie ?

Une influence du nom de commune ? (c'érait faciiiiiiile). 
Ce que tu as observé est typique d'une étape de rapprochement qui s'est mal passée,  où d'anciens pseudo-Fantoir restent référencés à tort. Je viens de forcer le rapprochement et tout a l'air d'équerre.

**Comment by deuzeffe** [comment]
> Une influence du nom de commune ? (c'érait faciiiiiiile).

Hihi.



> Je viens de forcer le rapprochement et tout a l'air d'équerre.

Impec, merci !
