### ISSUE TITLE
"Souci lors de la mise à jour du statut" pour les rapprochements BAN sans FANTOIR

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osm-vs-fantoir#185]
J'ai un souci lorsque je veux changer le statut d'un rapprochement présent dans BAN mais pas FANTOIR : 

Exemple sur Lyon 2 : https://bano.openstreetmap.fr/pifometre/#insee=69382&tab=0

**Observé :** 
- "Rue Delandine" est dans l'onglet "voies sans rapprochement OSM". Le nom complet de la rue est "Rue Antoine Delandine" dans OSM et dans FANTOIR (693822120U)
- Je change donc le statut à "divergence d'orthographe"
- Le message d'erreur suivant apparait : 
![image](https://user-images.githubusercontent.com/7891262/197859979-3547c962-4b56-4677-bc43-cf9351dee85d.png)

**Attendu :**
Le staut est changé à "divergence d'orthographe" sans message d'erreur

**Comment by vdct** [comment]
C'est un fonctionnement voulu. Les statuts reposent sur les codes FANTOIR (pérennes), aussi en l'absence de code FANTOIR pour une voie on ne sait pas gérer son statut dans le temps, car on s'appuie sur de pseudo codes FANTOIR non pérennes.
C'est pas bien joli avec l'actuelle pop-up, il faudrait la rendre plus explicite pour ces cas là.
