### ISSUE TITLE
Type FANTOIR pour les rues en devenir

### ISSUE THREAD

**Issue by nuxper** [osm-fr/osm-vs-fantoir#187]
Exemple sur Lyon 2 : https://bano.openstreetmap.fr/pifometre/#insee=69382&tab=0

La Place Jacques Truphemus a déjà un nom mais n'est pas encore construite. Le chantier du bloc n'est  même pas suffisamment avancé pour que je crée un highway au statut construction.

Est-ce qu'il n'y aurait pas un statut à trouver pour ce type de voie, pour que je puisse les mettre de coté pendant un temps (quelques mois) ?

![image](https://user-images.githubusercontent.com/7891262/197862652-0e8b4439-ae16-40fa-9861-44446e599642.png)

**Comment by vdct** [comment]
J'ai ajouté le cas "Voie en projet"
