### ISSUE TITLE
Voie présente dans BAL mais manquante dans pifomètre

### ISSUE THREAD

**Issue by LySioS** [osm-fr/osm-vs-fantoir#191]
commune : La Cabanasse (n° INSEE 66027)
voie concernée : Rue Moffre
adresses associées à la rue : oui

**Comment by LySioS** [comment]
Oui, le problème vient pour moi du fait, que Pifomètre ne me permettait pas de renseigner ces toponymes. Ils n'apparaissaient pas dans l'interface avant que je les rajoute dans OSM (grâce à la BAL source).

Je vais essayer d'être plus clair. Étant donné que ces infos font partie du fichier BAL; je trouve ça important que Pifomètre le fasse remonter, d'autant plus que dans le cas précis de La Llagonne, ces infos sont renseignées dans la colonne "voie_nom"

**Comment by Olyon** [comment]
Le problème avec ces adresses liés à des lieux dits c'est que si ils étaient dans Pifomètre avec les autres, ils seraient possible de les intégrés soit avec une relation associatedStreet soit sous forme de points avec comme tag addr:street=* et ces 2 façons ne conviennent pas car il n'y a pas de "street".
Donc il faut modifier pas mal Pifomètre pour gérer ces adresses et ce n'est pas encore fait.

**Comment by Olyon** [comment]
@LySioS 
Le nombre d'adresses de la BAN liées aux lieux dits est maintenant affiché sur la page des lieux dit sans rapprochement.
exemple :
https://bano.openstreetmap.fr/pifometre/index.html#insee=15108&tab=4
On ne peut pas les intégrer comme les voies mais ça permet de savoir quels lieux dits sont surement plus important à ajouter à OSM.
