### ISSUE TITLE
Ancien nom de commune dans Statistiques communes

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#193]
Dans les tables Statistiques communes, les noms de communes ne sont pas à jour.
Par exemple, dans le Cantal (https://bano.openstreetmap.fr/pifometre/stats_dept.html#dept=15), Neuvéglise est devenue Neuvéglise-sur-Truyère en 2017 suite à sa fusion avec des voisines. 
Pas de problème sur la page des communes.
Si je comprends bien, les mauvais noms proviennent de la table code_cadastre qui ne doit pas être à jour.

**Comment by vdct** [comment]
Merci @Olyon 
La table code_cadastre continue d'être mise à jour chaque nuit mais elle a perdu de son intérêt depuis qu'on arrive à 99% de communes vectorisées, et aussi parce qu'on utilise le COG comme référence pour la liste (et le nom) des communes
