### ISSUE TITLE
Voie non-FANTOIR: prendre en compte les Lieu-dits

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osm-vs-fantoir#201]
A ma connaissance, les lieux-dits non-FANTOIR apparaissent comme voies manquantes dans les outils Pifomètre (top voies manquantes, voies recentes manquantes..) même s'ils sont renseignés dans un Lieu-dit OSM. Ils ne peuvent être retirés des listes qu'en les renseignant dans des routes, ce qui est un contournement plutôt crade. (et qui peut entrer en conflit avec le vrai nom des routes)

Exemples:  "Lieu-dit Er" à Donges(44052)  , "Kernava" à Herbignac(44072) ...

**Comment by vdct** [comment]
Les lieux-dits & voies "non FANTOIR" ne sont pas grisables de manière pérenne. On peut les griser, mais il suffit de recharger la page pour voir leur statut à nouveau à OK. C'est une limite fonctionnelle liée justement à l'absence de code FANTOIR.

**Comment by iiitomo** [comment]
Merci pour la réponse, mais j'ai du mal m'exprimer. Peut-etre que je n'aurais pas du dire 'grisé' mais plutot 'retiré des listes de voies manquantes', car à ma connaissance, on peut retirer une voie non-FANTOIR des voies manquantes, de façon pérenne, en la renseignant dans une route. Par contre, ça ne marche pas si on la renseigne dans un lieu-dit.

**Comment by vdct** [comment]
Sur le principe, les voies non FANTOIR de la BAN peuvent être rapprochées des lieux-dits OSM
![Capture d’écran de 2023-07-02 23-26-51](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/a1ee674d-d9d8-43d1-a631-62a71103417e)
![Capture d’écran de 2023-07-02 23-48-20](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/566671cb-94af-4d54-8bf8-f429de826add)
