### ISSUE TITLE
Supprimer automatiquement les FANTOIR erronés

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osm-vs-fantoir#202]
Bonjour,
je suggère de créer une routine (tournant par exemple une fois par mois) qui supprime automatiquement les FANTOIR erronés des objets OSM mentionnés dans https://bano.openstreetmap.fr/pifometre/fantoir_errone.html
et les pages de type https://bano.openstreetmap.fr/pifometre/anomalies_fantoir.html#dept=44

**Comment by vdct** [comment]
Bonjour
merci pour la suggestion, mais ce n'est pas la vocation des outils autour de Pifomètre (et BANO par extension) que de supprimer du contenu d'OSM. L'idée de Pifomètre est de faciliter la contribution par des vrais gens, sans se substituer à eux pour les interactions avec OSM.
