### ISSUE TITLE
alt_name des lieux-dits pas pris en compte

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osm-vs-fantoir#206]
bonjour
https://www.openstreetmap.org/node/4786125478 et https://www.openstreetmap.org/node/10258041614 sont toujours dans https://bano.openstreetmap.fr/pifometre/top_adresses_manquantes.html#dept=37 , alors qu'ils ont été ajoutés en alt_name dans OSM il y a 5 ou 6 jours.

**Comment by vdct** [comment]
bonjour,
ça n'est pas un problème de alt_name ici mais de nature du rattachement : les adresses proposées par la BAN sont associées dans OSM à un lieu-dit, et pour l'instant BANO (donc Pifomètre) ne tiennent pas compte des adresses dans les lieux-dits

**Comment by vdct** [comment]
La nouvelle version de Pifomètre corrige le problème :
https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=37248

![Capture d’écran de 2023-07-02 23-19-40](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/f99edd37-06f1-47f2-ba29-73e4593dcd64)
