### ISSUE TITLE
En-têtes colonnes : "voies FANTOIR ou BAN"

### ISSUE THREAD

**Issue by Khomille** [osm-fr/osm-vs-fantoir#209]
Un petit détail facile à résoudre :)

Dans l'en-tête de la colonne : "X voies FANTOIR sans rapprochement OSM" et dans ses copines, il faudrait ajouter "ou BAN" puisque la liste est désormais alimentée par les deux sources.

**Comment by gendy54** [comment]
Du coup, ca fait le lien avec #272

**Comment by vdct** [comment]
Résolu en v3 avec l'intitulé "Libellé BAN ou CADASTRE"
