### ISSUE TITLE
export csv  - % adresses certifiées BAN non exporté

### ISSUE THREAD

**Issue by benoit-dd** [osm-fr/osm-vs-fantoir#210]
la colonne "% adresses certifiées BAN" n'est pas exportée dans l'export csv depuis la page suivante:
https://bano.openstreetmap.fr/pifometre/stats_dept.html#dept=37

**Comment by Olyon** [comment]
il doit juste falloir modifier le début de la ligne https://github.com/osm-fr/osm-vs-fantoir/blob/master/stats_dept.py#L24
A la place de "return ('Format\tCode INSEE\tCommune\tVoies avec adresses rapprochées (a)"...
il faut "return ('Code INSEE\tCommune\t% addresses certifiées BAN\tVoies avec adresses rapprochées (a)"..

**Comment by vdct** [comment]
Oui c'est l'idée. On peut faire le fix mais je ne peux pas déployer avant quelques jours encore
