### ISSUE TITLE
Afficher tous les lieux-dits dans l'onglet "lieux-dits non rapprochés"

### ISSUE THREAD

**Issue by JPapir** [osm-fr/osm-vs-fantoir#217]
Voir la discussion sur le forum OSM : https://forum.openstreetmap.fr/t/bano-ban-lieux-dits/13908/6

# Comportement observé

Les lieux-dits dont le nom est complexe (plus de deux mots) sont présentés avec une virgule dans le cadastre. Ex : `Limouzin, Au` pour `Au Limouzin`. **Ces lieux-dits ne sont pas affichés dans l'onglet `lieux-dits FANTOIR non rapprochés`**

En revanche, dans FANTOIR brut, ces lieux dits apparaissent bien, avec la valeur "NON" dans la colonne rapprochement. Une fois qu'un lieu dit est ajouté à OSM, il est rapproché et devient visible dans l'onglet `lieux-dits FANTOIR rapprochés`

# Comportement attendu

Faire apparaître tous les lieux-dits non rapprochés dans l'onglet `lieux-dits FANTOIR non rapprochés`, y compris avec une écriture en plusieurs mots. Pour ce faire, lors de la comparaison avec le cadastre, si la forme du cadastre comporte une virgule, restituer la forme attendue (par ex : `Limouzin, Au` -> `Au Limouzin`)

**Comment by vdct** [comment]
C'est maintenant géré dans la v3 de Pifomètre : https://bano.openstreetmap.fr/pifometre_v3/index.html
