### ISSUE TITLE
entête de colone fixe

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#218]
sur https://bano.openstreetmap.fr/pifometre/stats_dept.html#dept=01
quand on fait défiler la page vers le bas, la ligne d'entête disparait.
il serrait agréable d'avoir une ligne d'entête fixe qui ne défile pas avec les lignes de données

**Comment by vdct** [comment]
C'est intégré dans la nouvelle version, pour tous les onglets
Voir par exemple https://bano.openstreetmap.fr/pifometre_v3/stats_dept.html#dept=01
