### ISSUE TITLE
La modification du statut des voies sans FANTOIR n'a pas besoin d'être proposée

### ISSUE THREAD

**Issue by lenny31** [osm-fr/osm-vs-fantoir#239]
Lorsqu'on essaye de modifier le statut des « Voies sans FANTOIR » le message 
![image](https://github.com/osm-fr/bano/assets/7862384/36d8ab77-ae41-4a00-b8cd-fdfe2aea36d5)
n'est pas explicite, en fait il n'est pas possible de stocker le statut car il est stocké associé au code FANTOIR, 

Il vaudrait mieux modifier le message ou ce qui parait plus simple ne pas proposer la modification du statut pour ces voies là évoqué sur le forum : https://forum.openstreetmap.fr/t/pifometre-souci-lors-de-la-mise-a-jour-du-statut/15016

**Comment by vdct** [comment]
![Capture d’écran de 2023-06-16 16-44-21](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/27f10320-dd3d-49a8-b16e-23039b224bad)
C'est pris en compte dans la v3 en cours de finalisation et déjà utilisable à https://bano.openstreetmap.fr/pifometre_v3/
