### ISSUE TITLE
v3 : supprimer liens null/null

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osm-vs-fantoir#242]
Bonjour,
Quand une rue a uniquement un libellé Topo, le lien "carte" est http://www.openstreetmap.org/#map=18/null/null et envoie n'importe où. Il serait mieux dans ce cas de le supprimer.
ex ici "rue des ajoncs" ou "rte de belleville": https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=85178
merci.

**Comment by vdct** [comment]
C'est corrigé, merci à @Khomille pour le fix :)
![Capture d’écran de 2023-06-16 16-41-40](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/77daa6eb-b2de-4a95-b434-c1f0687be89d)
