### ISSUE TITLE
V3 : Impossible d'attribuer un statut à une voie sans Fantoir

### ISSUE THREAD

**Issue by ray66** [osm-fr/osm-vs-fantoir#245]
En V2, il était possible d'attribuer un statut à une voie sans FANTOIR. Ce n'est plus possible en V3. Je propose de créer cette possibilité.

**Comment by vdct** [comment]
Il y a peut-être erreur car cette fonctionnalité n'était pas présente, et a occasionné le ticket https://github.com/osm-fr/osm-vs-fantoir/issues/239

**Comment by ray66** [comment]
En effet, ce n'était pas possible en V2 non plus. Il y avait le sélecteur mais  on ne pouvait pass attribuer un statut. Donc ce n'est pas un problème spécifique V3.
