### ISSUE TITLE
Pré-remplir les commentaires et sources dans JOSM

### ISSUE THREAD

**Issue by overflorian** [osm-fr/osm-vs-fantoir#248]
Hello,
Ça serait bien si Pifomètre pré-remplissait les champs "commentaire" et "source" des changesets lorsque Pifomètre intègre adresses et/ou relations.

_Le tasking manager de HOT fait déjà ça et ça permet de gagner du temps + expliciter les changesets + permettre de les retrouver plus facilement._

### Reproduire
1. Pifomètre ouvre JOSM en cliquant sur "X points" ou "Relation"
![image](https://github.com/osm-fr/bano/assets/11553211/3bc87925-3cea-4cd1-9af6-5513be4619c1)

2. Le contributeur vérifie la cohérence des données créées dans JOSM

3. Le contributeur envoie les données.
Aujourd'hui : il doit commenter cette intégration manuellement.
Demain : Les deux champs sont déjà complétés. Ma proposition :
![image](https://github.com/osm-fr/bano/assets/11553211/fed4010a-4467-441a-849e-e80324c013f0)

**Commentaire :** Intégration adresses issues de la Base d'Adresses Nationale #BANO
(le hashtag peut être utile pour retrouver tous ces changesets)
**Source :** URL (stable !) de l'outil où recliquer pour intégrer les données

**Comment by gendy54** [comment]
Il me semble que ca le fait déjà. ou alors c'était sur la V2

**Comment by vdct** [comment]
Non ça n'a jamais été implémenté mais déjà évoqué par @Bibi56 (https://github.com/osm-fr/osm-vs-fantoir/issues/125) et @gendy54 tu avais participé au ticket.

On a différentes infos, lesquelles utiliser et lesquelles ranger où ?
- l'URL de la page Pifomètre y compris le code INSEE de la commune
- le texte générique "Intégration d'adresses"
- le nom de la commune voire son code INSEE ou son numéro département
- le nom de la voie ou du lieu-dit
On a 3 tags de changeset à disposition d'après https://josm.openstreetmap.de/wiki/Help/RemoteControlCommands#load_and_zoom
Je propose :
- commentaire : "Intégration d'adresses - <ville (code département)> - <nom de la voie ou du lieu-dit>
- source : l'URL
- hashtag : #BANO

**Comment by overflorian** [comment]
- Pour le commentaire, autant être le plus précis et le moins ambigu possible :
"Intégration des adresses issues de la Base d'Adresses Nationale sur la voie < NOM DE LA VOIE > dans la commune de < NOM COMMUNE > (code INSEE : < CODE INSEE COMMUNE >), < NOM DÉPARTEMENT > (< NUMÉRO DÉPARTEMENT >)
- source : l'URL => oui
- Pour les hashtags, on peut en rajouter autant que l'on veut, autant se faire plaisir : #BANO #Adresse #Integration
Je crois me souvenir qu'il est utile de mettre ces hashtags dans le commentaire principal, me trompe-je @PanierAvide ?

On avait discuté du sujet pour _Projet du mois_ et @PanierAvide avait des idées (et des perspectives !) plus détaillées que moi.

- Also : nouvelle idée : indiquer l'URL de la documentation. Dans notre cas : https://wiki.openstreetmap.org/wiki/FR:France/Base_Adresses_Nationale_Ouverte_(BANO)
Peut-être en créant un nouveau champ dédié ? (je n'ai rien trouvé dans la doc https://wiki.openstreetmap.org/wiki/Changeset)

**Comment by gendy54** [comment]
Pour compléter ce que dit @overflorian, le nom de la voie ne serait possible que dans le cas où tu n'importes des adresses que sur une voie et tu envoies le changeset. SI tu envoies plusieurs voies, il faudra restreindre l'info uniquement à la commune.
Je ne sais pas si c'est techniquement possible, sinon se limiter à l'info de la commune, ce sera déjà pas mal.

[Edit 18/07] En suivant la visio Pifomètre, je me suis rendu compte que nous avions 2 usages différents Vincent et moi. Vincent qui envoyait un changeset par relation AssociatedStreet créée directement du calque de la relation généré par Pifomètre et moi qui envoyait plusieurs relations en fusionnant les calques de rues dans la calque actif avant d'envoyer le changeset. Pour les petites communes jusqu'à un changeset par commune.

**Comment by vdct** [comment]
@overflorian @gendy54 une première version est dispo

**Comment by overflorian** [comment]
Yeees, c'est bon ça.
Testé et approuvé.

Le messages est "Samoëns (74258) - Intégration d'adresses #BANO #Pifometre"

Tu assumes le hashatag sans l'accent pour #Pifometre ? (lis-le à l'oral, ça fait bizarre ^^)
Et sinon, c'est un détail mais je suggère d'écrire en premier l'action et non le lieu : "Intégration d'adresses - Samoëns (74258) #BANO #Pifometre"

À part cela, pour moi le sujet est clôt (bravo !)

**Comment by vdct** [comment]
merci pour le retour
J'ai mis le texte fixe au début, le nom de commune ensuite. Mais je garde Pifometre (sans l'accent) car ça le vire sinon des hashtags de JOSM, je ne sais pas pourquoi
