### ISSUE TITLE
V3 : colonne date déclaration fantoir disparue ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#255]
Hello,

J'ai attendu d'avoir le temps d'écouter/regarder la présentation de la V3 au SotM 2023. Et sauf gouffre d'attention (et de mémoire), je ne me souviens pas qu'il ait été question de la disparition de la colonne "Date de création Fantoir" sur la page principale "Pifomètre" et je ne la retrouve plus :( 
Je m'en sers pour suivre scrupuleusement la prise en compte des déclarations de mon urbaniste préféré par les services de la DGFiP. 
S'il est possible de rétablir cette colonne, just do it! :-)
Si sa disparition simplifie le codage des pages, since it runs, dont't fix it! ;-)
Bref pas tout casser juste pour ça.

Merci pour la réponse, quelle qu'elle soit.

**Comment by vdct** [comment]
Je ne sais plus pourquoi j'ai considéré que cette info pouvait être zappée. Je me suis rendu compte récemment qu'elle me manquait dans certains cas, et à te lire elle a clairement un usage. Bref, elle va revenir !

**Comment by vdct** [comment]
Voilà c'est revenu via https://github.com/osm-fr/osm-vs-fantoir/pull/261 :rocket:

**Comment by deuzeffe** [comment]
Je vois la colonne \o/ :P 
Merci à toi et à @Khomille 
On feeeerme !
