### ISSUE TITLE
V3 Filtrage intégration d'adresses

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#258]
Hello,

Je rebondis sur l'intégration des adresses par @overflorian sur Samoëns
https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=74258

Il faudrait pouvoir filtrer les adresses intégrées pour ne plus voir que les voies avec adresses à intégrer (colonne intégrer les adresses)
Ce ne sera pas forcément très utile sur les petites communes. Encore que des petites communes sans BAL peuvent créer pas mal de voies.

**Comment by vdct** [comment]
Toutes les colonnes peuvent être triées, ça devrait faire l'affaire non ?

**Comment by gendy54** [comment]
En même temps que je rédigeais cette issue, je me suis aperçu qu'effectivement en tapant "point" ou "relation' ca masquait toutes les adresses intégrées.
Donc pour moi c'est réglé à mon niveau, mais est-ce que des personnes moins à l'aise vont y penser ?
Disons que je m'attendais à voir le filtrage dans le menu Afficher avec le reste.

**Comment by vdct** [comment]
> Disons que je m'attendais à voir le filtrage dans le menu Afficher avec le reste.

Je comprends. Pour l'instant ce n'est pas envisagé, sachant que le tri permet de s'en sortir, et qu'il ne s'agit pas de multiplier les filtres histoire de garder un menu Filtres lisible
