### ISSUE TITLE
Problème d'affichage dans la colonne intégrer les adresses (v3)

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#259]
Dans la commune d'[Auzainvilliers](https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=88022) dans les Vosges
Pour la Rue du Breuil, pifomètre me propose d'intégrer 2 lieux-dits, or c'est bien une rue avec des numéros (lorsque je cliquer sur qualifier, il me liste bien toutes les adresses de la rue)

**Comment by Jean-BaptisteC** [comment]
Ce n'est pas une anomalie, les adresses ont déja été intégré sans les relations, il ne reste que 2 lieux dit à intégrer
Je ferme l'issue

**Comment by vdct** [comment]
Tu soulèves un point : cette ligne devrait proposer une intégration des adresses en tant que voie plutôt que lieu-dit. Il se trouve que le contenu lieux-dits du Cadastre qui nous sert ici comporte un lieu-dit "Rue de Breuil" qui vient mettre le bazar dans la détermination du nomcomme nom de voie plutôt que nom de lieu-dit. Pas sûr qu'on arrive à bien balancer ces cas là...

**Comment by Jean-BaptisteC** [comment]
Est ce qu'on peut ignorer le fait que c'est un lieu-dit dès que le nom contient `rue` ?

**Comment by vdct** [comment]
Dans l'idéal il faudrait ce genre de logique, mais ça demande un peu d'étude avant
