### ISSUE TITLE
Voies récentes inconnues d'osm : ancienneté ? (différence V2-V3)

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#265]
Hello,

Pour le 87 : 

- V2 : la voie la plus ancienne inconnue d'osm a été créée dans FANTOIR le 2017-02-24 ; la plus récente, le 2023-02-22
- V3 : la plus ancienne, le 2022-01-24 ; la plus récente : 2023-02-22.

Au premier coup d’œil, les données pour 2022 et 2023 sont les mêmes pour les deux versions. Mais il manque celles < 2022 pour la V3.

Est-ce gênant ? 
De plus, DEFINE "récentes" ;)

Thx.

**Comment by Olyon** [comment]
Les 2 versions affichent bien 250 valeurs mais le problème ce n'est pas qu'il en manque à la fin pour V3 mais qu'il y a quelques résultats en plus au milieu pour V3.
Petit jeu des 7 erreurs ?, en fait il y en a 15 :)

J'ai regardé en détail ces rues en plus dans V3 :  la majorité est dû à une différence d'orthographe entre Fantoir et BAN : dans OSM, c'est l'orthographe BAN, dans V2 c'est rapproché et pas dans V3. Des types de voies différentes, une lettre qui diffère, un "et" qui devient "&" et un bel "IMP DE FAYES" qui devient "Impasse de Dognon" dans la BAN ! (87049	Coussac-Bonneval).

Les rues concernées :
87002	Ambazac	870020022	Route Cécile & Henry ROL-TANGUY
87002	Ambazac	870020307	Chemin du Grand Royère
87049	Coussac-Bonneval	870490092	Impasse du Dognon
87205	Le Vigen	872050350	Route de Ligoure
87088	Magnac-Bourg	870880312	Chemin des Charbonières
87104	Nedde	871040001	Coteaux des Acacias
87104	Nedde	871040072	route du puy Meisseix
87146	Saint-Germain-les-Belles	871460170	impasse de la gorseis
87188	Saint-Yrieix-sous-Aixe	871880015	venelle du bosguillou
87192	Solignac	871920126	Route de la Plagne

Ça pose un problème vu que c'est le nom BAN qui est affiché sur cette page et que c'est aussi celui qui est proposé lorsque l'on clique sur "x points" ou "relation" sur la page de la commune. J'ai l'impression aussi que dans la V3 en cliquant sur "relation", ça cherche à proximité le nom Fantoir mais ça indique le nom BAN contrairement à la V2 qui ne se servait que du nom BAN ? 

Il y a aussi
87146	Saint-Germain-les-Belles	871460259	Route Nationale
Rue sur la frontière de la commune, détectée par V2 et pas par V3 ?

3 rues sur la même commune qui ont leur Fantoir annulé, ça les fait totalement disparaître pour la V2 alors qu'il y a des adresses dans la BAN :
87146	Saint-Germain-les-Belles	871460186	Impasse de la Grillère
87146	Saint-Germain-les-Belles	871460406	Impasse du Chateau de la Grillère
87146	Saint-Germain-les-Belles	871460187	Route de la Grillère

Le dernier cas, c'est une rue avec un "statut Fantoir" dans Pifomètre :
87192	Solignac	871920149	Chemin des Places
Pas intégrée dans OSM mais un statut qui dit qu"il y a une "erreur de commune", elle ne devrait pas être dans les résultat de cette page comme le fait la V2 ?

**Comment by vdct** [comment]
> DEFINE "récentes" ;)

récentes = les moins vieilles :D
On prend la liste des voies inconnues, on la trie par date de la plus récente à la plus ancienne, et on coupe la liste à 250. Il faudrait dire "voies les moins vieilles" pour mieux refléter ce qu'est cette liste...

**Comment by vdct** [comment]
> J'ai regardé en détail ces rues en plus dans V3 :  la majorité est dû à une différence d'orthographe entre Fantoir et BAN : dans OSM, c'est l'orthographe BAN, dans V2 c'est rapproché et pas dans V3

Oui dans la v3 le pivot de comparaison est vraiment FANTOIR. L'idée est toujours de se demander pourquoi une voie n'est pas rapprochée, et potentiellement de tomber sur une blague d'orthographe. Dans la liste que tu donnes ça m'a permis de constater qu'on ne gérait pas le '&' par exemple.

> Ça pose un problème vu que c'est le nom BAN qui est affiché sur cette page et que c'est aussi celui qui est proposé lorsque l'on clique sur "x points" ou "relation" sur la page de la commune. J'ai l'impression aussi que dans la V3 en cliquant sur "relation", ça cherche à proximité le nom Fantoir mais ça indique le nom BAN contrairement à la V2 qui ne se servait que du nom BAN ?

A ce stade par définition on n'a pas d'autre nom que celui de la BAN donc oui c'est lui qui sert dans les propositions d'intégration. La mécanique en v2 et v3 est la même pour l'option 'Relation', sauf erreur.

**Comment by deuzeffe** [comment]
> et on coupe la liste à 250

Ah voilà ! Les plus récentes dans la limite des dernières 250 créées ;)

Thx!

**Comment by deuzeffe** [comment]
J'y pense : si on dégomme du rouge, la liste devient < 250 lignes, right ? 

Est-ce que les voies qui étaient auparavant plus que 250e intègrent le peloton de tête et la liste reste donc à 250 lignes quel que soit l'âge des plus récentes ?

**Comment by Olyon** [comment]
Toujours 250 lignes sauf si le départements a moins de 250 rues avec Fantoir manquants.

**Comment by deuzeffe** [comment]
@Olyon merci pour ta réponse. 

Donc, il en rentre autant qu'il en sort jusqu'à épuisement des stocks. Ça fait un peu tonneau des Danaïdes inversé \o/
