### ISSUE TITLE
Lien vers page BAN de la commune (V3)

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#266]
Hello,

Super le lien vers la fiche BAN de la commune (adresse.data.gouv.fr/commune/insee) !

Sauf que c'est la fiche (merci Capt'ain Obvious) et non la BAN de la commune (adresse.data.gouv.fr/base-adresse-nationale/insee) à partir de laquelle on peut remonter à la fiche sus-citée.

Y a moyen de moyenner ?
(comme d'hab, pas tout casser pour ça)

**Comment by vdct** [comment]
Y a moyen ! C'est corrigé :)
