### ISSUE TITLE
page Par Département

### ISSUE THREAD

**Issue by niconil** [osm-fr/osm-vs-fantoir#27]
A quelle fréquence sont réalisées les mises à jour ?

je ne comprends pas que le score de la commune 88037 reste à 181
il y a beaucoup plus de 16 lieux dit rapprochés ...

**Comment by vdct** [comment]
La mise à jour se fait à chaque demande de la page.

Mais ce tableau date d'avant la prise en charge des lieux-dits en tant que ponctuels (décembre 2015). Les lieux-dits comptabilisés sont ceux avec des adresses. Il va falloir rajouter des colonnes pour compter les lieux-dits Fantoir rapprochés des lieux OSM (nodes place=*).

**Comment by gendy54** [comment]
J'ai l'impression qu'on peut fermer le ticket.
