### ISSUE TITLE
Adresses sans rue : référence ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#270]
Hello,

J'ai un peu joué avec le nouvel onglet (super idée !) dans le 87. 

9 résultats dont un à Limoges : "Rue Meissonier" (libellé OSM) : 
- libellé Fantoir : RUE MEISSONIER ->rapprochée ;
- libellé page BAN de la commune(merci pour le lien direct) : rue Ernest Meissonier* -> je suppose que c'est ça qui s'affiche dans l'onglet en question donc le pivot c'est la BAN ? Et pourtant, pas de libellé BAN/Cadastre dans la case qui va bien (/me mauvaise élève qui n'a pas tout lu...) Et pourtant rapprochée (via le code Fantoir ?
(*) j'ai corrigé et forcé le rapprochement -> signalement disparu dans l'onglet nouveau

Sinon, trouvé un truc bizarre dans l'affichage V3 : cf ScreenShot ci dessous. (/me incapable de comprendre ce qui est bancal :/)
![Screenshot 2023-07-15 at 14-40-00 Limoges - Pifomètre](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/f0734842-65ab-46d5-a935-c5f5f703bf75)

**Comment by vdct** [comment]
> Sinon, trouvé un truc bizarre dans l'affichage V3 : cf ScreenShot ci dessous. (/me incapable de comprendre ce qui est bancal :/)

Juste pour ce point, le coupable est par là : https://www.openstreetmap.org/way/717960936 (code FANTOIR de la rue du Progrès avec le nom Meissonier)

Pour le reste je regarde un peu plus tard (pas le teeeeemps !)

**Comment by vdct** [comment]
Le pivot est bien le code FANTOIR ici, présent à la fois côté BAN et OSM 

@deuzeffe  c'est mieux comme ça ?

![Capture d’écran de 2023-07-15 17-58-41](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/259a00e3-4652-44e4-b822-fcc10016abad)

**Comment by deuzeffe** [comment]
> Juste pour ce point, le coupable est par là

**LA** coupable (je pense savoir d'où ça vient, j'investigue)
(même pas - trop - honte)
Edit : même pas moi. C'est corrigé, merci pour ton signalement !

**Comment by deuzeffe** [comment]
> c'est mieux comme ça ?

yep, merci chef !
(donc, c'est toujours fantoir le pivot - **ouf**)

**Comment by vdct** [comment]
> Edit : même pas moi. C'est corrigé, merci pour ton signalement !

![Capture d’écran de 2023-07-15 22-44-08](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/55af785f-64e9-48c2-9d0e-f41ae04fe0ad)

Vu ! Ca ramène 2 lignes car le nom est différent sur la voie et dans la relation. Y en a un plus juste que l'autre ?

**Comment by deuzeffe** [comment]
> Y en a un plus juste que l'autre ?

Grmblbl. Nan, j'ai juste fait les choses à moitié :(
"Normalement", maintenant, ça "devrait" être bon.
(merci pour ta patience et ta dispo...)

**Comment by vdct** [comment]
On peut fermer ?

**Comment by deuzeffe** [comment]
Bien sûr ! Fait.
