### ISSUE TITLE
Différencier l'origine du libellé

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#272]
Hello,

Colonne _Libellé BAN ou Cadastre_, ajouter un moyen de discriminer l'origine.
Pastille de couleur comme dans la colonne _Libellé OSM_, police de couleur,... je n'ai pas d'idée particulière

Je ne sais pas s'il y aura besoin de filtrer cette info. Utilité ?

**Comment by vdct** [comment]
> Colonne _Libellé BAN ou Cadastre_, ajouter un moyen de discriminer l'origine.

C'est maintenant le cas pour chaque ligne avec des petits pictos
