### ISSUE TITLE
Discriminer les adresses intégrées ou non

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#273]
Hello,

J'ai repris par hasard une rue où j'ai habité. L'intégration d'adresses avait été fait par quelqu'un d'autre que moi.

![image](https://github.com/osm-fr/osm-vs-fantoir/assets/10323517/f5d725d5-d2ca-4663-896f-896b6c994c0c)
Dans l'exemple, on voit qu'une seule adresse n'a pas été intégrée.

Je me rends dans Qualification de l'adresse pour en savoir plus.

![image](https://github.com/osm-fr/osm-vs-fantoir/assets/10323517/a2a17601-d0e6-449a-9e18-fa92df1cae79)

Et là, douche froide. Rien ne permet de distinguer l'adresse non intégrée afin de voir le problème

Suggestions:
- créer une colonne "Adresses intégrées/non-intégrée" entre _Numéro_ et _Statut de l'adresse_ et comme valeur "intégrée" ou "non-intégrée" ou une pastille de couleur

A investiguer: créer 4 couleurs pour le fond de carte: 
- Adresse ok intégrée/non-intégrée.
- Adresse anomalie intégrée/non-intégrée

**Comment by vdct** [comment]
C'est fait, dans la liste des numéros et sur la carte, un peu différemment de tes suggestions mais l'idée est là
