### ISSUE TITLE
Pifo3 : retard màj données OSM ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#276]
Hello,

Je viens de constater le phénomène suivant en demandant, au même moment, une màj d'une commune avec les données OSM.

**Pifo3 :** 

![pifo3_20230719_222419](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/83c8dace-9a74-431a-83e7-eee9f23b6e91)

**Pifo2** : 

![pifo2_20230719_222344](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/9db389ab-7853-4598-b874-87ba180d6bbd)

Je n'ai rien compris au tuto live de quelques minutes du 18/07 (encore un énorme merci !) ou il y a vraiment un problème ?

Merci pour la réponse, quelle qu'elle soit.

**Comment by vdct** [comment]
La v2 et la v3 ne partagent pas leurs mises à jour. Celles de la v3 étaient bloquées depuis hier soir, je ne sais pas trop pourquoi... J'ai relancé, ça semble ok. Merci du signalement

**Comment by deuzeffe** [comment]
> La v2 et la v3 ne partagent pas leurs mises à jour.

Ça j'avais compris \o/

> Celles de la v3 étaient bloquées depuis hier soir

Voilà, je voulais alerter sur le fait qu'on n'était plus le 18/07 depuis presque 24h.

> bloquées depuis hier soir, je ne sais pas trop pourquoi...

Un effet démo. aka Bonaldi ? ;)

Merci à toi pour la réactivité !

**Comment by deuzeffe** [comment]
C'est moi où c'est encore bloqué ?

![pifo3_20230720_115427](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/24ac3234-2829-411d-8935-267ce84c500f)

**Comment by vdct** [comment]
Oui je l'ai re-débloqué ce matin :/
J'ai du mal à comprendre l'origine du souci, à suivre...

**Comment by deuzeffe** [comment]
Arrêté 21/07/2023 14:15:06 (UTC) :-(

**Comment by vdct** [comment]
Cette fois ci c'est pas arrêté, c'est juste très ralenti, au rythme des màj à la source où BANO puise sa base France. Ça se surveille ici : http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by deuzeffe** [comment]
Ok, vu, merci. Je ferme et je rouvrirai si besoin (espérons que non !)

**Comment by deuzeffe** [comment]
De ce que je comprends de ce que raconte Munin (sans certitude quant à la justesse de mon interprétation), la màj BANO n'est pas ralentie.
Cependant, le 24/07/2023 à 14:04 UTC, c'est arrêté au 23/07/2023, 21:59:14 UTC :(

(ou alors, je n'ai encore rien compris;..)

**Comment by vdct** [comment]
Merci pour le signalement (encore !). C'est très instable en ce moment et ça va un peu continuer, car je ne comprends pas encore d'où vient le souci et l'investigation est fastidieuse.

**Comment by deuzeffe** [comment]
De rien !
Bon, je reste "awake" (woke ? ^^) en fonction de mes dispo...

**Comment by vdct** [comment]
Depuis https://github.com/osm-fr/bano/commit/b439b4ade2815821baf6b28663235fa3eae93ef7 ça semble stable. Je ferme
