### ISSUE TITLE
Pifo3 - Voies récentes manquantes : lignes grisées

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#277]
Hello,

C'est normal que les lignes du tableau des voies récentes manquantes soient toutes sur fond gris ?

![Screenshot 2023-07-20 at 22-22-39 Voies récentes inconnues d'OSM (87)](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/5061c754-249a-4942-8f08-7763d3bd1aaf)

EDIT : idem pour l'onglet Top adresses manquantes

**Comment by vdct** [comment]
Le souci était sur tous les onglets ou presque, c'est corrigé. Merci pour le signalement :)

**Comment by deuzeffe** [comment]
Merci à toi pour la correction !
(oh, des petits carrés oranges pour les non rapprochés <3)
