### ISSUE TITLE
V3 - Statut FANTOIR : diffusion entre onglets

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#278]
Hello,

Je me demande dans quelle mesure il est intéressant* - ou pas - de diffuser un statut FANTOIR (différent de OK) entre l'onglet Pifomètre et (par exemple au hasard hasardeux) l'onglet Voies récentes manquantes (ou Top adresses manquantes).

[*] et facile techniquement - ou pas.

**Comment by vdct** [comment]
Oui c'est intéressant et doucement amorcé avec l'onglet des Adresses sans rue. Les autres vont arriver

**Comment by deuzeffe** [comment]
Rhooo \o/ !
On patientera :)

**Comment by deuzeffe** [comment]
Bin dis-donc, l'a pas fallu patienter trop longtemps. C'est super. Merci tout plein !
