### ISSUE TITLE
V3 : voies récentes inconnues, non rapprochées, avec fantoir et dans osm

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#279]
Hello,

Je tombe sur un truc que je ne comprends pas :(

- commune 87154
- pifomètre : 
  - Fantoir : 871541953	2011-04-26	CHE DES PRADELLE
  - BAN/Cadastre : Chemin des Pradelles Le Mas (sur la même ligne, cela va sans dire et mieux en le disant)
  - non rapprochée
-  voies récentes : 87	Saint-Junien (87154)	871541953	Chemin des Pradelles le Mas	2011-04-26 (je suppose que le code fantoir vient du croisement fantoir/ban-cadastre visible dans l'onglet Pifomètre, même si ça semble un peu de la divination magique pour moi !)
- et last but not least, dans osm, il existe déjà !

![Screenshot_20230722_204252](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/a797a8e4-b58b-4f73-bbb3-7dbd7c92eadd)

Il faut que je nettoie mes besicles, I guess :/

**Comment by vdct** [comment]
C'est un cas typique de "non transitivité" entre BAN et OSM. Vu que le seul pivot en v3 est FANTOIR, et que à la fois :
- on n'a pas ce code FANTOIR dans OSM
- le nom OSM et le nom FANTOIR divergent
alors on n'a pas de rapprochement même si on a l'essentiel : la voie est dans OSM.
Dans mon souvenir c'est fait comme ça car pas mal d'attributions de codes FANTOIR dans la BAN sont farfelus et peuvent mener à de fausses impressions de rapprochement dans OSM. Voilà pour la justification, mais il faut reconnaitre que dans le cas présent c'est plus agaçant que satisfaisant :/

**Comment by deuzeffe** [comment]
Merci pour tes explications.
Oui, c'est agaçant (euphémisme) ;)
Reste plus qu'à forcer le rapprochement via le code FANTOIR, I guess.
