### ISSUE TITLE
Problème de rapprochement sur les iles

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#28]
Bonjour,

Je viens d'aller faire un fix osmose dernièrement sur l'Île d'Aix et par pure curiosité j'ai activé la couche Bano sous JOSM et j'ai l'impression qu'il y a un problème sur le rapprochement...

J'ai levé un lièvre ou c'est un problème de boundary

Jérôme

**Comment by vdct** [comment]
C'est au moins un problème de boundary car la limite communale de l'Île d'Aix a été supprimée il y a quelques jours...je te laisse voir par qui ;)
http://www.openstreetmap.org/api/0.6/relation/113454/12
http://www.openstreetmap.org/relation/113454
Tu fais le revert ? Sinon dis le pour que je m'en charge.
