### ISSUE TITLE
v3 : statut FANTOIR NOK -> actions grisées :(

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#282]
Hello,

Ça a été dit lors de la visio. du 18/07 : lorsque le statut FANTOIR est différent de OK, alors aucune action (ORG/JOSM, points/relation/qualif.) n'est accessible.
Ce n'est pas une bonne idée. Ou alors je ne sais pas me servir de ce statut.

Ex. : l'entrée FANTOIR est "Cchemin Trucmuche". On est bien d'accord qu'il s'agit d'une faute de frappe est que le nom de la voie (comme montré par la BAN) est "Chemin Trucmuche". Des typo. de ce type, il y en a pas mal (un d au lieu d'un t, un seul r au lieu de 2, etc.). Et on devrait pouvoir avoir accès aux actions précitées, àmtttttha.

À voir s'il y a moyen de moyenner (sans que ça soit trop complexe techniquement) ?

**Comment by vdct** [comment]
Je ne me souviens pas d'avoir dit (ou entendu) ça pendant la visio ? En tout cas si tu constates ce fonctionnement, c'est un bug car l'idée n'a jamais été de vouloir empêcher les actions sur une ligne en fonction du statut FANTOIR. 
Une possibilité aussi : il se trouve que le code de Pifomètre est fréquemment mis à jour en ce moment, ça peut causer des blagues lorsque le cache du navigateur joue un peu trop son rôle et ne permet pas la récupération de certains fichiers à jour. Ctrl+F5 au cas où...

**Comment by deuzeffe** [comment]
Autant pour moi, c'est le rouge de la couche BANO qui passe au gris. 

Bon, là, tout de suite (sur une commune jamais ouverte en v3) : 

- la ligne passe en grisé (comme en v2) -> OK ;
- les actions ORG/JOSM/iD (LE RETOUR - j'ai vu passer ton commit) sont possibles -> OK ;
- intégration des adresses points/relation possible **MAIS** le texte reste en gris (comment ça, je chipote !?) ;
- qualifications possibles (et texte en fuschia, comme avant) -> OK.

C'est tout pour le moment ^^

**Comment by Khomille** [comment]
C'est vrai ça. Les liens en gris suggéraient qu'on ne peut plus / doit plus les utiliser quand le statut Fantoir n'est pas "OK"... Alors que c'est indépendant.

Correction du soir : les liens restent désormais colorés quand une ligne est grisée.

**Comment by deuzeffe** [comment]
Mer-ci !
