### ISSUE TITLE
V3 - Numéro en doublon sur la page de qualification

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#284]
<img src="https://github.com/osm-fr/osm-vs-fantoir/assets/87148630/ffaa8a3f-f9f2-48f6-aef9-23a8ac973627" height=400 />

**Comment by vdct** [comment]
Merci, c'est corrigé, je te laisse vérifier

**Comment by poirelpa** [comment]
Bonjour, je pense avoir le même problème, ou un problème similaire, avec cette voie : https://bano.openstreetmap.fr/pifometre_v3/numeros.html?insee=60159&fantoir=601590130&source=BAN&tab=0

![image](https://github.com/osm-fr/osm-vs-fantoir/assets/1129577/7f4c80f5-19a5-4969-b237-b14b092df44e)


Merci pour votre travail :)

Paul

**Comment by vdct** [comment]
Je viens de mettre à jour BANO (bouton en haut a droite) pour Compiègne et tout semble à nouveau ok

**Comment by poirelpa** [comment]
je confirme, merci
