### ISSUE TITLE
V3 - Inverser les colonnes Création Fantoir et Ancienne Commune

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#285]
<img src="https://github.com/osm-fr/osm-vs-fantoir/assets/87148630/5af852b5-fe33-487a-bb88-44f05e087156" width=500 />

Inverser le titre de la colonne ou le contenu de la colonne

**Comment by vdct** [comment]
Merci, c'est corrigé
