### ISSUE TITLE
V3 - Valeur null dans la colonne Libellé Fantoir

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#286]
La valeur null est présente dans la colonne Libellé FANTOIR pour les lignes contenant uniquement les voies et lieux-dits présents dans OSM.

![image](https://github.com/osm-fr/osm-vs-fantoir/assets/87148630/298f6955-e8da-494c-9fa4-4e09f0eeff83)

**Comment by Khomille** [comment]
Je ne reproduis pas le problème.

Vérifier que le cache est bien vidé (il y a eu une mise à jour aujourd'hui) à coups de CTRL + F5...

**Comment by Jean-BaptisteC** [comment]
Je viens de tester sur mon téléphone, j'ai plus le problème.
Je ferme le ticket
