### ISSUE TITLE
V3 - Ligne en double lorsqu'un lieu-dit à un code Fantoir erroné

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#289]
J'ai renseigné plusieurs centaines de lieux dit sur la commune de La Vôge les Bains (88029)
J'ai fais quelques erreurs sur les codes Fantoir, Pifomètre me la signalé avec une ligne en double pour chaque erreur
![image](https://github.com/osm-fr/osm-vs-fantoir/assets/87148630/b5269447-f1a4-4d03-8c52-843c6021a1d1)

**Comment by Jean-BaptisteC** [comment]
En complément, j'ai vu sur le wiki que les lieux-dits présents sur la couche BANO n'étaient à ne pas intégrer, car cela est expérimental.
https://wiki.openstreetmap.org/wiki/FR:France/Base_Adresses_Nationale_Ouverte_(BANO)

```
Lieux-dits dans le rendu BANO
Les lieux-dits extraits à partir du cadastre sont visibles sur le rendu BANO depuis mi-septembre 2014. Ceux-ci sont encore très expérimentaux et n'ont été ajouté au rendu que pour avoir un retour sur cette première extraction.

Il est pour l'instant préférable de ne pas utiliser ceux-ci pour compléter les données OSM.

Les noms en gras correspondent aux lieux-dits considérés comme habités dans le fichier FANTOIR.
```
Est ce que c'est encore le cas ?
Car j'ai intégrer presque 200 lieux dits depuis la couche BANO dont certains sans code FANTOIR, certains en doublon et certains inconnus de pifomètre

**Comment by vdct** [comment]
> J'ai fais quelques erreurs sur les codes Fantoir, Pifomètre me la signalé avec une ligne en double pour chaque erreur

Entre temps tu as dû corriger ces lignes, et je n'arrive pas à reproduire. Tu as un autre cas ?


> Est ce que c'est encore le cas ?

Oui et non : le contenu a changé mais la source n'est pas de super qualité. D'une manière générale c'est bien de ne pas intégrer en aveugle, les noms de lieux-dits sont souvent bien plus nombreux sur le cadastre que sur le terrain. Pour les noms invisibles sur le terrain, il faut une connaissance locale pour s'assurer que le nom est utilisé à défaut d'être affiché en bord de route.

**Comment by deuzeffe** [comment]
J'ai un quadruplet \o/ (je gagne quoi ? :P) mais sans erreur apparente de code FANTOIR :/ (ou mauvaises lunettes ?)

![Screenshot_20230727_154352](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/e155a6e3-a097-4397-8b12-5d7f1317fc09)

**Comment by Jean-BaptisteC** [comment]
Et lorsqu'on clique sur qualifier on a les numéros en double :)

**Comment by vdct** [comment]
> J'ai un quadruplet \o/

![Capture d’écran de 2023-07-27 22-57-49](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/b8314015-1cbf-4d55-91b8-71d41228d652)
J'ai forcé un rafraîchissement de BANO sur la commune et tout est rentré dans l'ordre. J'ai déjà eu ce type de souci (tout en double ou en triple) à cause de rafraîchissements BANO demandés en saccade, c'est un souci javascript en coulisse je pense. Donc si le problème se reproduit : lancer une mise à jour en croisant les doigts pour que le clic ne déclenche qu'une seule mise à jour à la fois :crossed_fingers:

**Comment by vdct** [comment]
> Et lorsqu'on clique sur qualifier on a les numéros en double :)

Je veux bien une URL de ce genre de cas si tu as

**Comment by deuzeffe** [comment]
> J'ai déjà eu ce type de souci (tout en double ou en triple) à cause de rafraîchissements BANO demandés en saccade,

Merci pour ta réponse : compris !

Cémafot : j'ai peut-être forcé le dit rafraîchissement un peu trop souvent dans la journée ^^ On croisera les doigts pour les prochaines communes :p

**Comment by Jean-BaptisteC** [comment]
J'arrive plus à reproduire les lignes en double ni les numéros en double.
Sûrement liée à l'actualisation forcée
