### ISSUE TITLE
URLs indisponibles pour les voies non numérotées 

### ISSUE THREAD

**Issue by bagage** [osm-fr/osm-vs-fantoir#29]
osm-vs-fantoir n'affiche quasi jamais de liens dans la catégorie "voies SANS adresses numérotées", pourtant le rendu BANO est capable de savoir où se situe la voie approximatitvement (exemple [la rue des Lavandes](http://cadastre.openstreetmap.fr/fantoir/#insee=38454&tab=2) se situe [par ici](http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#17/45.15436/5.33623)).
Si osm-vs-fantoir pouvait afficher les liens correspondant aussi pour les voies sans numéros, ça faciliterait beaucoup l'intégration des voies non numérotées à mon avis, pour ceux qui utilisent principalement ton site osm-vs-fantoir.
cadastre.gouv.fr n'est pas capable de trouver les voies non numérotées donc la seule solution que je vois actuellement est de parcourir le rendu BANO jusqu'à trouver la voie recherchée.

**Comment by vdct** [comment]
Pour afficher un lien il faut une géométrie, puisque tous les liens partent du principe qu'ils pointent vers un (x,y). Les lignes sans lien reflètent qu'aucune parcelle de la commune n'est associée à la voie, et donc qu'on n'est incapable de connaître leur localisation, faute de géométrie dispo.
L'exemple de la rue des Lavandes contredit ça, au moyen d'une autre source géométrique : la BAN en version ODbL. C'est donc en effet une piste à creuser.

**Comment by bagage** [comment]
Hello @vdct, pas trop surcharger par la sotm ;-)? Je viens aux nouvelle voir si ce problème est dans ta road map prochainement ? Merci :)

**Comment by vdct** [comment]
Bon, tu as un début de réponse, il me faut 11 jours pour te répondre :(
Clairement BANO dort côté évolutions jusqu'au SOTM, en effet. On en reparle... à Clermont ? ;)

**Comment by bagage** [comment]
À vrai dire ceci est un dupliqué de #14, non ?

**Comment by vdct** [comment]
Oui c'est bien la même idée. C'est représenté côté BANO par https://github.com/osm-fr/bano/issues/93 qui est le prochain morceau en haut de la pile à traiter.

**Comment by bagage** [comment]
OK, je ferme alors. Merci @vdct !
