### ISSUE TITLE
v3 : numéros fictifs en 5xxx - qualifier les adresses intégrées

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#292]
Hello,

- commune : 87110
- voie : Rue du Vignaud 
- v2 : pas de points/relation d'adresse à intégrer (normal) + lien Qualifier montre bien l'anomalie "adresse fictive en 5xxx"
- v3 : mention ✔ Adresses intégrées (?) + lien Qualifier me donne une page blanche :(

Trouver un moyen pour dire "Pas la peine de chercher, le numéro n'existe pas" ?

EDIT : page blanche également si on veut qualifier les adresses pour la commune 87187 pour des lignes avec adresses intégrées, par exemple Rue Jean Ferrat ou Avenue Jules Ferry : parce que les adresses sont intégrées ?

**Comment by Jean-BaptisteC** [comment]
Pourquoi l'adresse Rue du Vignaud n'est pas dans OSM, elle a changé ?
Si c'est le cas, le statut Fantoir devrait aussi mis à jour.

**Comment by deuzeffe** [comment]
@Jean-BaptisteC parce que c'est un cas extrêmement particulier (Village Martyr d'Oradour-sur-Glane) : tant que je ne saurai pas ce qu'il en est en allant sur place, je ne touche rien. WIP, en résumé.

**Comment by vdct** [comment]
> * v3 : mention heavy_check_mark Adresses intégrées (?) + lien Qualifier me donne une page blanche :(

C'est corrigé, merci pour ce cas. Le souci venait des infos calculées pour indiquer en haut à gauche le nombre d'adresses à intégrer, calcul tout récent et pas bien sec

**Comment by deuzeffe** [comment]
Merci et de rien ! Pas de pb pour continuer à passer la serpillière ;)
