### ISSUE TITLE
v3 : hiatus calque josm/calque points adresses

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#294]
Hello,

Soit 

- la commune 87154
- la Voie sans Fantoir	Route des Baisses - Les 3 Bornes	Route des Baisses - les 3 Bornes
- le calque JOSM se cale bien sur la voie en question

![Screenshot_20230727_092718](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/5261d235-7779-4f80-8cb0-ce1175646f1e)

- le calque des points adresses se cale "ailleurs"

![Screenshot_20230727_092957](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/19922504-18bb-4940-99da-d05949236190)

(Je suis allée vérifier sur la page BAN de la commune : et c'est bien la 871542487	2013-07-24	[Voie] RTE DES BAISSES		Route des Baisses qui a été "renommée")

C'est moi ou bien il y a un truc qui diverge de son propre chef ?

**Comment by vdct** [comment]
Je ne reproduis pas :/
En cliquant sur les points d'adresse ils n'ont rien à voir avec la Route de la Bretagne ?
![Capture d’écran de 2023-07-28 10-51-41](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/fb2d532a-5a4c-4f10-af22-449898f62816)

**Comment by deuzeffe** [comment]
Moi non plus, je ne reproduis plus :/ On va dire que c'est la technique, locale ou à distance, qui a eu des vapeurs...
Merci et désolée pour le dérangement.
