### ISSUE TITLE
Voies récentes manquantes : possibilité de naviguer dans une liste plus longue avec du multi-pages

### ISSUE THREAD

**Issue by Ptigrouick** [osm-fr/osm-vs-fantoir#296]
Quand on en veut toujours plus à manger, on aimerait bien que la liste des "voies récentes manquantes" soit plus longue ! Pourquoi pas une petite barre de navigation multi-pages pour pouvoir voir la suite ? ;-)

**Comment by Khomille** [comment]
C'est fait !
