### ISSUE TITLE
v3 : date FANTOIR

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#298]
Hello,

Vu que le fichier FANTOIR est celui de bano/load_fantoir.sh, on est bien d'accord que c'est le pied de page footer.html de la v3 qui n'est pas à jour (données 01/23), spa ?

(dis, dis, monsieur, je peux le mettre à jour !?)
(oui, je sais, ça sera peut-être encore une dernière fois...)

**Comment by vdct** [comment]
Dans BANO v3 le chargement se fait par un autre biais (c'est manuel tant que TOPO n'est pas sorti) mais le résultat est le même : la date n'est pas à jour. Donc oui go go go 😊

**Comment by deuzeffe** [comment]
Hiiiii !

**Comment by deuzeffe** [comment]
Puisque PR mergé, issue fermée. Merci !
