### ISSUE TITLE
Qualification des adresses: affichage

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#300]
Hello,

2 exemples trouvés au pif:

- https://bano.openstreetmap.fr/pifometre_v3/numeros.html?insee=55250&fantoir=552500035&source=BAN&tab=0
- https://bano.openstreetmap.fr/pifometre_v3/numeros.html?insee=34055&fantoir=340550001&source=BAN&tab=0

Est-ce que c'est possible de filtrer n° pairs et impairs pour y voir plus clair ?
Autant dans l’affichage sur la mini-carte que dans la liste de gauche

Ca servirait autant aux longues voies avec plein de numéros qu'au "pâté" de numéros.

Interrogation: 
Est ce qu'on doit asservir l'affichage des numéros de la carte à celui de la liste ou inversement ou pas du tout, je n'ai pas d'avis sur ce qui serait le plus pratique. En fonction évidemment des possibilités techniques et de ce qui parait pertinent.

Les boutons selecteurs

- Pair
- Impair 

pourrait être mis avec Afficher

**Comment by Khomille** [comment]
C'est faiiiiiiit 

Les nouveaux filtres Pair et Impair (et les autres) contrôlent l'affichage des numéros sur la carte uniquement, mais ne changent pas le tableau.

**Comment by gendy54** [comment]
C'est déjà très bien ;)
Merci
