### ISSUE TITLE
v3 - top adresses/voies récentes : affichage nombre

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#301]
Hello,

Est-ce qu'il est possible/facile d'afficher le nb de voies connues/voies récentes, comme s'affiche le nb d'adresses dans l'onglet Adresses sans rue ?

Comme d'hab, pas tout casser, à traiter plus tard si existe davantage urgent.

**Comment by Khomille** [comment]
C'est fait pour Voies récentes !

**Comment by deuzeffe** [comment]
Merci !
(Buzz l'éclair est ton surnom ? :p)

**Comment by vdct** [comment]
Et fait aussi pour les voies avec adresses

**Comment by deuzeffe** [comment]
\o/
Merci à vous deux !
(bon, du coup, le nombre pique, fort, très fort...)
