### ISSUE TITLE
v3 : voie sans Fantoir avec Fantoir non rapprochées

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#304]
Hello,

- commune 87041
- RUE DE L'ADJ GAL DEVERINE (intitulé Fantoir)

![Screenshot_20230731_203250](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/84a816e5-a03f-4293-a328-a0dab970ab0b)

Je suppose que la graphie de la voie dite sans Fantoir est trop éloignée de ce qui existe déjà ou du nom Fantoir pour que la voie sans Fantoir puisse être automagiquement rapprochée par la V3 ? (on passera sous silence mes fautes de frappe - 2r comme 2f ^^)
(en V2, c'est pareil :/)

**Comment by vdct** [comment]
Oui clairement les orthographes sont trop divergentes. C'est d'ailleurs un des critères pour identifier les "voies sans Fantoir"

**Comment by deuzeffe** [comment]
On est donc bien d'accord.
Est-ce que les champs alt_name ou old_name ou official_name sont pris en compte pour le rapprochement ?
(ou les indiquer ne ça sert pas à ça ?)

**Comment by vdct** [comment]
> alt_name ou old_name ou official_name

alt_name et old_name sont gérés, mais pas official_name
:point_right:  https://github.com/osm-fr/bano/blob/7554a7d8f8cbb851bc7342f7375aaa8f7e270ff2/bano/sql/charge_noms_voies_lieux-dits_OSM.sql#L10

**Comment by deuzeffe** [comment]
Ok, merci. Pour official_name, pas grave, puisqu'on peut passer par le code Fantoir, pour forcer le rapprochement, il me semble.
