### ISSUE TITLE
v3 : rapprochements bloqués ?

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#306]
Hello,

Au 02/08, la v3 annonce que le dernier rapprochement est du 30-07-2023 23:33:43 (UTC) (j'ai regardé pour pas mal de communes du 87) :/ (c'est OK pour la v2, obviously)
(je ne sais pas si je suis dans le bon "dépôt" pour ce ticket...)

**Comment by vdct** [comment]
Oui il y a de gros soucis de plantage Postgres lors des batchs nocturnes de rapprochement. Pas encore pris le temps de regarder, sachant que les rapprochements commune par commune fonctionnent

**Comment by deuzeffe** [comment]
Je ne sais pas si tu lui a forcé la main, mais le 03/08 ça a l'air reparti. Bon courage pour le debug !

**Comment by deuzeffe** [comment]
@vdct on attend de voir si https://github.com/osm-fr/infrastructure/issues/533 a fait son effet ou on peut fermer ?

**Comment by vdct** [comment]
C'est globalement mieux oui, je ferme.
