### ISSUE TITLE
Pas d'adresse sur commune de Nangis

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osm-vs-fantoir#31]
tout est dans le titre:
http://cadastre.openstreetmap.fr/fantoir/#insee=77327&tab=2
http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#15/48.5544848869276/3.0088997462008

**Comment by vdct** [comment]
@didier2020 merci
Le cache du cadastre était complètement absent pour Nangis, sans vraiment d'explication. Va comprendre.
