### ISSUE TITLE
Doublon voie rapprochée

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#310]
Hello,

https://bano.openstreetmap.fr/pifometre_v3/index.html#insee=54526
https://www.openstreetmap.org/way/392679548#map=19/48.68390/6.21387

Rue des Dames Laboureur
Rue des Laboureurs

Cette voie s'appelait avant Rue des Laboureurs, mais le conseil municipal a changé de nom suite à des recherches historiques un peu plus poussées (un copain habite cette rue).
Du coup, le _old_name_ apparaît en filtre bleu alors qu'il ne devrait pas, puisqu'il fait partie de la nouvelle voir déjà rapprochée.

je ne sais pas si c'est très clair ce que je dis.

**Comment by vdct** [comment]
Ce qu'on rapproche ce n'est pas la voie mais le nom de la voie. Ici on a 2 noms, mais un seul qui matche, d'où le second dans les noms OSM sans correspondance. Pas grand chose à y faire, c'est très bien d'avoir le old_name d'après ce que tu expliques
