### ISSUE TITLE
v3 : liste bleue

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#313]
Hello,

Voilà la liste de ce que je trouve dans la liste bleue de ma commune (87001, mappée avec mes petites mimines) : 

- amenity=parking
- amenity=school
- old_name=* (comprends pas pourquoi)
- landuse=cemetery
- place=neighbourhood (pe que Fantoir/Topo en contient ?)
(+ des voies pas encore prises en compte dans Fantoir/Topo/Ban - logique)

Si un jour il y a du temps pour du ménage à faire...

**Comment by gendy54** [comment]
Je rajouterai également plus généralement des name descriptifs qui remontent, genre _name=voie de service_ ou _name=voie privée_

**Comment by vdct** [comment]
> Si un jour il y a du temps pour du ménage à faire...

Le fichier Fantoir est rempli de manière très différente d'une commune à l'autre. Au delà des noms de rues et lieux-dits, on trouve **parfois** une flopée d'autres "noms d'endroits". On a dans Fantoir (France entière) 900 noms de cimetières, 650 noms d'écoles, plus de 1000 noms de parkings. Donc au fil du temps dans BANO, la liste de noms cherchés dans OSM pour être confrontés à Fantoir s'est élargie pour tenir compte de ces thématiques là, pour chaque commune. Sauf qu'en face, Fantoir n'a (souvent) rien comme noms correspondants. Dans ces cas là, les noms trouvés dans OSM et dépourvus de correspondance se retrouvent dans la liste bleue.
Dans cette liste on trouve aussi des noms alternatifs (old_name, alt_name) d'objets OSM qui ont été rapprochés via leur tag name. Dans BANO, on perd le lien entre les objets OSM de départ et les noms, donc il n'est pas possible de dire qu'un nom issu de alt_name correspond à un autre nom issu de name et rapproché. Chaque name vit sa petite vie indépendamment. Pour ces lignes là, pas grand chose à faire, ils restent dans la liste et c'est assumé.
La partie la plus intéressante de la liste bleue consiste en des noms trouvés dans OSM et erronés : souvent une faute de frappe ou d'orthographe, qui a empêché le rapprochement. Ces noms là sont souvent faciles à corriger dans OSM, et permettent ensuite un rapprochement, ce qui supprime la ligne correspondante dans la liste bleue (au profit d'une ligne avec pastille verte).


> des name descriptifs qui remontent, genre _name=voie de service_ ou _name=voie privée_

Si on trouve ce genre d'entrée dans la liste bleue, là il ne s'agit pas de corriger l'orthographe, il s'agit juste de faire le ménage **dans OSM**. Le problème n'est pas que ces noms remontent dans la liste bleue, mais qu'ils soient dans OSM tout court. La présence dans la liste bleue n'est qu'un symptôme.

Pour essayer de résumer : cette liste bleue est hétéroclite car on y ratisse volontairement un peu large. Elle n'a pas vocation a être réduite à zéro, car elle peut comporter des noms tout  fait valides pour OSM mais dépourvus de correspondance dans Fantoir. Son intérêt est surtout d'y détecter des erreurs à corriger dans OSM : fautes d'orthographe ou noms descriptifs.

**Comment by deuzeffe** [comment]
@vdct merci infiniment pour ta longue réponse détaillée et particulièrement instructive, en particulier savoir que Fantoir peut-être lui aussi un vaste ~~foutoir~~ listing au-delà des voies et lieux-dits.
Effectivement, la liste bleue permet de corriger une flopée d'erreur de saisie des `name=` de voies et lieux-dits et c'est déjà un excellent outil !

BTW, pas eu l'occasion de lister tout ce que j'apprécie dans la v3 : 

- beaucoup moins laxiste que la v2 (mode masochiste) ;
- rapidité du chargement des pages communales ;
- tri des colonnes ;
- recherche simple dans les colonnes ;
- les picto ! (made by @Khomille, non ?) ;
- etc. :)

**Comment by vdct** [comment]
@deuzeffe @gendy54 on peut fermer ?

**Comment by deuzeffe** [comment]
@vdct voui. #done
