### ISSUE TITLE
v3 : traitement des nouvelles communes

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#314]
Hello,

Je tombe sur un comportement bizarre : 

- page Top adresses, Saint-Pardoux-le-Lac (**87128**)	**87173B021**	Chatenet Colon, 27 adresses à intégrer -> le calque adresse ouvert dans JOSM est vide<sup>1</sup> :/

![Screenshot_20230806_105010](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/65ff4d6b-ad10-46e5-9c73-3d07f060d102)

- page de la commune, **87128B118**	2019-11-27	Saint-Pardoux	[Lieu-dit] CHATENET COLON	Chatenet Colon	Chatenet-colon, PAS d'adresses à intégrer

![Screenshot_20230806_105059](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/d80aaa95-cac4-4411-96d5-e468b27b5fd4)

Je subodore un "effet de bord" de la création des nouvelles communes (les codes Fantoir sont différents entre Top adresses et page communale) ?

<sup>1</sup> le cadastre n'a pas été importé, mais l'absence de bâti ne gêne pas, puisque je n'ai pas eu de calque vide lorsque j'ai intégré des voies/adresses de lotissements récents pas encore intégrés dans osm.

Cerise (amère) sur le gâteau : la mise à jour BANO de 87128 tourne indéfiniment sans s'arrêter : un rapport avec le lag de replication du jour ou le fait que c'est une nouvelle commune ?

(bon dimanche quand même ! ^^)

**Comment by vdct** [comment]
La cause commune à tout ça semblait être un plantage dans le processus de rapprochement BANO, mais pas lié à la nature de la commune : juste une mise  au carré des codes FANTOIR issus de la BAN, pour laquelle il manquait un peu de fiabilité. Ca m'a l'air résolu mais je te laisse vérifier

**Comment by deuzeffe** [comment]
Effectivement, ça semble s'être arrangé<sup>1</sup> ce matin, merci à toi. J'ai des lignes en double, mais ce n'est pas grave. Je regarde pour ce qui est des autres communes nouvelles du 87. 

Ce qui m'a perturbé, c'est que pour les autres communes traitées au même moment, il n'y avait aucun problème.

<sup>1</sup> malgré un `si depuis JOSM je demande l'ouverture de Pifomètre, il me répond "404 n'est pas un code INSEE de commune"` [mise à jour par Leni](https://lists.openstreetmap.org/pipermail/talk-fr/2023-August/106340.html) et que je confirme pour ce qui est de la v3

**Comment by vdct** [comment]
J'ai fait une modif ce matin pour tenter de fixer ça. cf https://lists.openstreetmap.org/pipermail/talk-fr/2023-August/106343.html

**Comment by deuzeffe** [comment]
Vu.
Les rapprochements BANO se font.

Cependant, j'ai toujours l'alerte 404 pour : 
- Saint-Pardoux-le-Lac 87128 (le tag ref:INSEE est le bon, me semble-t-il)
- Val-d'Issoire 87097 (idem)
- Val-d'Oire-et-Gartempe 87028 (idem)
- et même Aixe-sur-Vienne 87001 qui n'est pas une commune nouvelle (idem)

Pour la config. d'utilsplugin2, j'ai : https://bano.openstreetmap.fr/pifometre_v3/josm.html?lat={#lat}&lon={#lon}
c'est bon ?

**Comment by vdct** [comment]
Je viens de tester toutes les communes et chaque sous-commune (admin_level=9) parmi les 4 et toutes sont ok pour moi. Est-ce que tu peux m'indiquer pour chacune un cadrage qui est ko ? En gros, quel serait l'objet OSM le plus au centre de ta vue JOSM quand ça plante ? Sachant que les coordonnées envoyées à Pifomètre sont celles du centre de ta vue JOSM

**Comment by deuzeffe** [comment]
Oooooooops, c'est normal que tu reproduises pas le bug que je rencontre : il y avait une autre typo. dans les paramètres d'utilplugins2 de mon JOSM... :/ #Javoue

En revanche, les dernières données OSM à jour sont du 07/08/2023 14:02:21 (UTC) : c'est uniquement chez moi ou bien ?

**Comment by vdct** [comment]
> En revanche, les dernières données OSM à jour sont du 07/08/2023 14:02:21 (UTC) : c'est uniquement chez moi ou bien ?

Il y a eu un hoquet côté fourniture en fin d'après-midi, donc je pense que c'était pour tout le monde
=> http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by deuzeffe** [comment]
Mince, j'avais pourtant bien regardé, et pas vu le hoquet :/ Note pour moi-même : ne pas oublier de rafraîchir/vider le cache.
