### ISSUE TITLE
Qualification des numéros: tri par entier naturel

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osm-fr/osm-vs-fantoir#318]
Dans la page "Qualification des numéros d'adresse", actuellement les numéros sont triés par ordre alphabétique, ce qui donne:
* 1
* 1 bis
* 10
* 11
* ...
* 19
* 1A
* 1B
* 1C
* 2
* 20
* ...

Il serait plus pratique de trier ces numéros par entier naturel (puis par lettre), pour obtenir quelque chose du genre:
* 1
* 1 bis
* 1A
* 1B
* 1C
* 2
* 3
* ...
* 9
* 10
* 11
* 12
* ...
* 19
* 20
* 21
* ...

**Comment by FlorentRICHARD44** [comment]
La fonction JavaScript proposée en 1ère solution ici semblerait bien fonctionner https://stackoverflow.com/questions/15478954/sort-array-elements-string-with-numbers-natural-sort

**Comment by vdct** [comment]
Bonjour
Un clic sur le nom de la colonne donne le même résultat

**Comment by FlorentRICHARD44** [comment]
Merci pour la réponse. En effet, je n'avais pas essayé de cliquer sur la colonne dont le tri fonctionne bien.

Est-ce que l'on pourrait avoir ce tri déjà fait par défaut lorsque l'on arrive sur la page? (ce tri naturel me paraitrait plus pertinent que le tri alphabétique, mais si l'alphabétique est plus pertinent pour d'autres, l'utilisation du clic sur la colonne me suffira)

**Comment by FlorentRICHARD44** [comment]
C'est appliqué sur Pifomètre V3 et fonctionnel sur le site
