### ISSUE TITLE
alt_name pas (plus) pris en compte par top_adresses_manquantes

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osm-vs-fantoir#321]
Par exemple 
https://bano.openstreetmap.fr/pifometre/top_adresses_manquantes.html?dept=37&offset=0
indique 'Rue Paul Vaillant Couturier'
alors que je l'ai rajouté en alt_name il y a 12 jours

**Comment by vdct** [comment]
La présence de cette rue dans le tableau n'a pas de lien avec la présence d'un alt_name sans trait d'union, par rapport au name. Le souci vient de la différence d'orthographe entre le nom de la rue dans OSM et dans FANTOIR, où la rue s'appelle 'RUE P V COUTURIER'. Pour faire disparaître la ligne du tableau, il faut forcer la mise en correspondance entre les 2 noms à l'aide du tag ref:FR:FANTOIR qui vaudra ici 372330970

**Comment by iiitomo** [comment]
ok merci
