### ISSUE TITLE
name pas (plus) pris en compte par top_adresses_manquantes

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osm-vs-fantoir#322]
Rue Pierre de Ronsard
apparait dans https://bano.openstreetmap.fr/pifometre/top_adresses_manquantes.html?dept=37&offset=0
alors qu'elle existe depuis 5 ans !

**Comment by vdct** [comment]
Même situation que dans #321 : le nom de rue dans FANTOIR est jste "Rue Ronsard" sans le prénom. Pour forcer le rapprochement il faut ajouter le tag ref:FR:FANTOIR avec comme valeur 370031432

**Comment by iiitomo** [comment]
ok merci, je vais ajouter les ref:fr:FANTOIR alors.
Juste pour mon info: d'où provient le nom de voie affiché dans top_adresses_manquantes ? 
et comment l'outil top_adresses_manquantes arrive-t-il à attribuer le bon FANTOIR (ou pas de FANTOIR) aux voies ?

**Comment by vdct** [comment]
> d'où provient le nom de voie affiché dans top_adresses_manquantes

de la BAN



> comment l'outil top_adresses_manquantes arrive-t-il à attribuer le bon FANTOIR (ou pas de FANTOIR) aux voies

le FANTOIR dans ce cas vient de la BAN aussi. C'est globalement utilisable mais pas parfait

**Comment by iiitomo** [comment]
Merci encore !
Je poursuis mes questions [ICI](https://forum.openstreetmap.fr/t/nom-des-voies-dans-fantoir-vs-ban/17365) sur le forum, car ça peut intéresser d'autres personnes.
