### ISSUE TITLE
Pifocarte/Pifomètre : synchro

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#332]
Bonjour,

Je constate ce que j'interprète comme une mauvaise synchro entre Pifomètre (la base) et Pifocarte (le rendu de la carte, donc)

Exemple : 
- soit la [commune 87001](https://bano.openstreetmap.fr/pifometre/index.html?insee=87001) ;
- soit la relation [Route de Fargeas (9492847)](https://www.openstreetmap.org/relation/9492847), que j'ai mise à jour à la vue de l'horreur que me montrait Pifocarte (cémafôt).

La base étant à jour, la carte me montre ça : 
![Screenshot_20231015_133412](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/cde250dd-0eb3-4e47-a9d8-1f5f9246bb89)

La voie me semble bien à jour quant à son nom et son fantoir (la relation aussi), mais le point adresse pas du tout et la voie n'est pas verte :/ Comme si rien n'avait été mis à jour et que l'horreur (cémafôt) perdurait.

Qu'est-ce que j'ai oublié de faire pour que la carte me montre que ma correction est ok ?

Merci pour la réponse.

**Comment by vdct** [comment]
> Qu'est-ce que j'ai oublié de faire pour que la carte me montre que ma correction est ok ?

Je pense que c'est dû au micmac dans les membres de la relation, où on trouve 2 noms : Route de Fargeas et Pont de Fargeas. Au moment où tu passes ta souris sur un des points d'adresse le nom qu'on cherche à associer est "Pont de..." et non "Route de...". Je pense qu'il faut ôter de la relation le pont, en théorie tous les membres d'une associatedStreet avec le rôle street ont le même nom que la relation elle-même

**Comment by deuzeffe** [comment]
Compris.

Si j'enlève le segment du pont, la voie est discontinue ; si je laisse le segment, j'ai une alerte parce que ce n'est pas le même nom que celui de la relation.

Bon, je vais tester en enlevant le segment du pont.

N'empêche, ce genre de cas n'est sûrement pas exceptionnel sur le terrain et aucune idée comment la modélisation dans osm peut être améliorée.

**Comment by vdct** [comment]
Y a vraiment aucun souci à avoir des discontinuités dans ces relations, elles n'ont pas vocation à faire du parcours de graphe. Et la situation du pont se retrouve assez banalement avec une rue entrecoupée par un rond-point ayant son nom en propre. Donc tu peux y aller :)

**Comment by deuzeffe** [comment]
Voilà, c'est fait et rapproché. Et le résultat est celui attendu \o/
