### ISSUE TITLE
Pifomap : way non pris en compte

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#333]
Hello,

La relation Rue Auguste Renoir : https://www.openstreetmap.org/relation/8220491 (les 3 ways ont bien le même nom/Fantoir qui est aussi celui de la relation, il me semble)
La commune sur Pifomap : https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=87001#map=16.1/45.806879/1.15954

Manifestement, il manque un way (le plus long) à la visualisation.

J'ai loupé quoi pour que la visu. soit conforme aux données en base ?

Merci pour la réponse.

**Comment by vdct** [comment]
J'ai l'impression que c'est à cause de l'extrémité du way au noeud https://www.openstreetmap.org/node/816691118 qui sort de la limite de la commune. Tout ce qui n'est pas strictement inclus dans la commune (comme ici un way à cheval)  n'est pas pris en compte. Pour remédier dans ton cas, soit tu coupes le way à l'intersection de la limite communale, soit tu déplaces le node https://www.openstreetmap.org/node/376739821 pour le fusionner avec le précédent (perso c'est ce que je ferais ici, on n'est pas à une précision millimétrique)

**Comment by deuzeffe** [comment]
Vu, merci. Tu as l’œil dis-donc !
J'ai déplacé le point d'intersection avec la Rue Velasquez pour déplacer la route du bon côté ~~du périph~~ de la limite de commune, en fait ;) et c'est ok, cette fois-ci.
D'ailleurs, suivant ton hypothèse, la dite Rue Velasquez, à cheval sur les 2 communes, devrait être verdie en partie. Or, elle l'est en totalité : les mystères ~~de l'ouest~~ d'osm/pifomap ;)

**Comment by vdct** [comment]
> D'ailleurs, suivant ton hypothèse, la dite Rue Velasquez, à cheval sur les 2 communes, devrait être verdie en partie. Or, elle l'est en totalité : les mystères ~de l'ouest~ d'osm/pifomap ;)

C'est une histoire de priorité : seules les parties strictement à l'intérieur d'Aixe devraient être en vert, s'il existe de telles parties. C'est ce qui s'est passé pour la rue Renoir. Mais il se trouve qu'aucune portion de la rue Velasquez est strictement à l'intérieur de la commune, tous les ways sont chevauchants. Donc ils sont tous à égalité quand on cherche à retenir les meilleurs. Peut-être faudrait-il qu'aucun ne soit en vert, ça alerterait mieux sur leur tracé à cheval

**Comment by vdct** [comment]
> Peut-être faudrait-il qu'aucun ne soit en vert, ça alerterait mieux sur leur tracé à cheval

Bon finalement j'ai pris une autre option : les géométries à cheval sur les communes voisines sont en orange, celles bienincluses dans la commune restent en vert. Donc pour celles en orange, il y a potentiellement un truc à affiner au niveau géométrie

**Comment by deuzeffe** [comment]
Vu. 
Ça peut effectivement aider à améliorer la géométrie des voies. En revanche, lorsque la frontière entre 2 communes suit exactement le milieu de la voie`*`, je crains que ça soit davantage une source de confusion qu'un moyen d'améliorer la géométrie. Dilemme pas simple à résoudre.
`*` il me semble que tu avais montré un tel exemple dans un de tes deux _webinaires_

**Comment by deuzeffe** [comment]
Je rencontre un autre pb. J'ouvre un autre ticket et je ferme celui-ci.
