### ISSUE TITLE
Pifomap : prise en compte des anomalies Pifomètre

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#336]
Hello, 

Soit l'Impasse Nicolas Poussin (870010558) orangée (j'ai tout bien vérifié la fin à la frontière, normalement) 

https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=87001#map=17.91/45.807181/1.16224/0/4

![Screenshot_20231102_124449](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/1533be11-fd03-473e-ba59-ad74be32e55f)

Cette voie est marquée en anomalie dans Pifomètre (Erreur de commune).

![Screenshot_20231102_124931](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/eef464b1-16c7-4867-beac-18436bf5c117)

Effectivement, elle est sur le territoire de la commune limitrophe, où elle est bien verdie.

![Screenshot_20231102_125134](https://github.com/osm-fr/osm-vs-fantoir/assets/36087963/9b8d7fdb-e1a5-4862-a888-c4e57be04976)

Tu en penses quoi ?

**Comment by vdct** [comment]
![Capture d’écran de 2023-11-18 13-15-40](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/296b94c0-c578-45a1-886c-10c4e6aa6cd3)
La voie est référencée dans FANTOIR mais aucune parcelle ne lui est rattachée. Je ne sais pas trop quoi en dire...
En tout cas le fait qu'elle apparaisse en orange dans le Pifomap d'Aixe est "normal" est l'état car toutes les voies qui touchent la limite de commune sont remontées, qu'elles soit dans ou en dehors de la commune. C'est un peu la limite de la visualisation pour l'instant

**Comment by deuzeffe** [comment]
Ok, vu.
 (et compris)
(et désolée pour le lag)
