### ISSUE TITLE
voies_recentes_manquantes: le lien osm.org de la voie n'est pas stable dans le temps

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#339]
Même sans qu'il y ait de modif sur la voie.

Cette page est pratique pour trouver des voies où on peut mettre le noms dans OSM depuis chez soit. Du coup je fais dans l'ordre. Et pour l'avancement (les cas ajoutés (en attente de disparaître à la prochaine MAJ) ou passés) je me base sur les liens osm marqués comme visités.

Ce qu'il se passe c'est que le lien correspond a une adresse sur la voie. Mais elle doit être prise arbitrairement dans l'ordre de chargement de la BD. Et du coup tout les 2 ou 3 jours le lien a de bonnes chances de pointer un autre numéro et donc d'être différent.

En suivant le code, ça viens de la BD, la lat et lon de chaque voie:
https://github.com/osm-fr/osm-vs-fantoir/blob/becd2ea3db24994e3a219db9127ba70306509dc0/voies_recentes_manquantes.html#L108C2-L108C2
↓
https://github.com/osm-fr/osm-vs-fantoir/blob/master/voies_recentes_manquantes_dept.py#L13

**Comment by vdct** [comment]
Je ne soupçonnais pas l'usage que tu expliques. J'ai fait une modif pour essayer de rendre l'URL plus stable au fil du temps, tu diras si ça convient

**Comment by tuxayo** [comment]
> Je ne soupçonnais pas l'usage que tu expliques

C'est la seule manière que j'ai trouvée pour passer en revue une par une les voies manquantes dans OSM sans repasser pleins de fois sur celles qui on besoin d'être faites sur le terrain (divergence de nom et autres). Sauf que ça marche que pour moi. Et si deux personnes font le même département, une personne va devoir se taper une 2è fois toutes les voies que l'autre a déjà évaluées.

Une solution propre et utilisable en masse serait un export utilisable dans ‎MapRoulette https://github.com/osm-fr/bano/issues/349

> J'ai fait une modif pour essayer de rendre l'URL plus stable au fil du temps, tu diras si ça convient

Merci beaucoup! :D J'ai commencé à repasser en revue toutes les voies où le lien est marqué comme visité et je vais voir ce que ça donne en remontant jusqu'à là où j'en était.

**Comment by vdct** [comment]
En fait je ne comprends pas pourquoi tu veux revisiter le lien a posteriori... Une fois tes modifs faites dans OSM la ligne correspondante dans la page des voies manquantes est sensé disparaître dans les 24h grâce à la màj quotidienne de BANO. Mais tu peux aussi forcer toi-même cette mise à jour en allant sur la page Pifomètre de la commune concernée et en cliquant en haut à droite sur le bouton de màj (la flèche noire sur fond bleu). De retour sur la page des voies manquantes, F5 et si la ligne que tu traitais a disparu, c'est signe que le nom de voie est maintenant bien connu d'OSM car BANO ne le mentionnera plus comme manquant. Je ne vois pas ce que tu veux vérifier d'autre ?

**Comment by tuxayo** [comment]
> En fait je ne comprends pas pourquoi tu veux revisiter le lien a posteriori

Oups, je voulais dire "où le lien est marqué comme **non-visité**"

Je repasse sur les voies que normalement j'ai passées mais qui sont pas marquées comme visitées. Pour les revérifier et les marquer comme visitées. Si tout va bien tout mon début de la liste finira par être marqué comme visité et sans trous qui apparaissent au fil des jours comme avant. Comme ça je peux rapidement sauter où j'en suis et si on trou apparaît alors c'est vraiment une voie que j'ai pas examinée.

> De retour sur la page des voies manquantes, F5 et si la ligne que tu traitais a disparu, c'est signe que le nom de voie est maintenant bien connu d'OSM car BANO ne le mentionnera plus comme manquant.

Tiens à propos de ça le "Chemin de la Rabassière" est listé dans https://bano.openstreetmap.fr/pifometre/voies_recentes_manquantes.html?dept=13&offset=0
Alors que dans la commune est bien noté comme rapproché. https://bano.openstreetmap.fr/pifometre/index.html?insee=13041

**Comment by tuxayo** [comment]
Les liens ont l'air d'êtres stables, merci! :D
