### ISSUE TITLE
Pifomap: fond de carte HS

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#340]
Il y bien le rendu BANO mais plus de fond.

Les tuiles font un mélange de 404 et de CORS Missing Allow Origin

**Comment by vdct** [comment]
Je viens de changer de fond en conséquence. A l'avenir l'idée est d'avoir le choix entre plusieurs fonds, ça évitera le souci...

**Comment by tuxayo** [comment]
Merci, ça fonctionne! :D
