### ISSUE TITLE
Pifomap: fond de carte HS

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#341]
À nouveau HS, mais c'est pas comme #340, les tuiles chargent bien (images visibles dans l'outil réseau de Firefox)

https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=13066&ratio=no#map=14.54/43.87116/4.90849

**Comment by vdct** [comment]
La console parle de souci de double header et de CORS. De mon côté je n'ai rien changé donc c'est côté tuiles HOT qu'il y a eu une modif, dont je n'ai aucune maitrise. @cquest j'ai besoin de tes lumières là dessus : est-ce que j'ai quelque chose à (re)configuer côté http sur bano.osm.fr ou bien c'est côté fabrication et publication des tuiles HOT qu'une modif est à faire ?

merci

**Comment by vdct** [comment]
Merci à @cquest qui a corrigé le souci côté CORS. @tuxayo ça devrait à nouveau s'afficher si tu retestes

**Comment by tuxayo** [comment]
Merci, ça marche! :D
