### ISSUE TITLE
Adresses en double dans la relation associatedStreet

### ISSUE THREAD

**Issue by Olyon** [osm-fr/osm-vs-fantoir#342]
Lorsque l'on clique sur "relation" pour ajouter des adresses à une relation associatedStreet existante, si des adresses sont à la fois dans la relation associatedStreet et ont le tag addr:street=* alors on se retrouve avec l'adresse en double dans la relation et addr:street=* n'est pas supprimé.

Exemple avec la Rue de Savoie ici : https://bano.openstreetmap.fr/pifometre/index.html?insee=01072

**Comment by vdct** [comment]
Merci pour le signalement. J'avais repéré une relation avec le même comportement : https://www.openstreetmap.org/relation/15036021 mais pas encore eu le temps de m'y pencher.

**Comment by vdct** [comment]
@Olyon sur les exemples que j'avais noté c'est corrigé. Sur la rue de Savoie ça fonctionne aussi
