### ISSUE TITLE
La pifomap liste une voie non rapporchée dans OSM quand le pifomètre la met comme rapporchée

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#343]
- https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=13118&ratio=no#map=18/43.559045/5.250591
- cliquer sur la voie
- «pas rapproché(e) dans OSM» «Nom OSM : Impasse du Murier» «Nom BAN : Impasse du Murier»
- problème: les noms sont les mêmes donc ça devrait être rappoché
- https://bano.openstreetmap.fr/pifometre/index.html?insee=13118
- rechercher "Impasse du Murier"
- marqué comme rapproché
- c'est juste mais ça confirme un problème sur la page pifomap

**Comment by vdct** [comment]
Merci pour le signalement. Je viens de corriger. Au passage, ça traite aussi le souci que tu avais relevé en fin de discussion dans https://github.com/osm-fr/osm-vs-fantoir/issues/339 :+1:

**Comment by tuxayo** [comment]
Merci  @vdct  c'est en effect corrigé :)

Il y a un truc qui est peut être très proche.

https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=13019&ratio=no#map=17.99/43.439417/5.368656

> Chemin du Jas d'Esquive
> connu(e) seulement d'OSM
> Source : OSM

> 132 Chemin du Jas d’Esquive
> pas rapproché(e) dans OSM
> Nom OSM : 
> Nom BAN : Chemin du Jas d’Esquive

**Comment by vdct** [comment]
Non ici le souci est classique : le nom FANTOIR  a un S final, pas le nom OSM. Soit c'est une faute d'orthographe côté OSM à corriger, soit OSM a raison et dans ce cas il faut ajouter le tag ref:FR:FANTOIR

**Comment by tuxayo** [comment]
Ah oui en effet! C'est juste parce que le pifomètre se base principalement sur le FANTOIR et pas la BAN?

>  Soit c'est une faute d'orthographe côté OSM à corriger, soit OSM a raison et dans ce cas il faut ajouter le tag ref:FR:FANTOIR

Ok donc je faisais bien de pas mettre ref:FR:FANTOIR jusque là sans être sûr de tout ce que ça impliquait même quand c'était évidant que c'est la même voie dans FANTOIR et OSM. Car ça veut dire que OSM à raison alors que là faut voir sur le terrain donc ne rien toucher si j'ai bien compris.
(je me demande si il y a un certain nombre de ref:FR:FANTOIR mis sans être sûr du vrai nom de la voie faute d'avoir compris ça)
