### ISSUE TITLE
Hyperlien vers pifomap avec référence INSEE undefined

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osm-fr/osm-vs-fantoir#344]
Dans la page Pifomètre, l'hyperlien vers la page Pifomap contient une référence avec insee=undefined.
![image](https://github.com/osm-fr/osm-vs-fantoir/assets/12184477/42ea7228-f8b0-4729-8050-683c271c5081)

ce qui amène le message suivant ensuite en arrivant sur la page de pifomap
![image](https://github.com/osm-fr/osm-vs-fantoir/assets/12184477/7375689e-709b-48ef-8a18-981be845944c)

Etapes pour reproduire:
1. Aller sur Pifomètre (sans commune) https://bano.openstreetmap.fr/pifometre/index.html 
2. Renseigner un numéro INSEE dans le champ commune
3. Cliquer sur "Lister" -> l'URL du lien PIFOMAP n'est pas mise à jour

**Comment by vdct** [comment]
Merci beaucoup @FlorentRICHARD44 :+1:
