### ISSUE TITLE
Pifomap: «Chargement...» sans fin et points d'adresses manquants

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#352]
https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=13084&ratio=no#map=17.7/43.716097/5.313266

«Chargement...»  ne fini pas. Et les point d'adresses ne sont pas visibles.

Depuis la nuit dernière.

**Comment by vdct** [comment]
Ici pas de souci :
![image](https://github.com/osm-fr/osm-vs-fantoir/assets/2237260/aa23dbf5-c245-4f01-8004-eb04b3cf74ab)

Il y a eu pas mal de modifs dans différents fichiers ces jours ci, tu as peut-être de mauvaises versions de fichiers en cache. Essaye avec Ctrl+F5 pour forcer le rechargement des fichiers
