### ISSUE TITLE
Erreur 500 pour Saint-Barthélemy-d’Anjou

### ISSUE THREAD

**Issue by Ltrlg** [osm-fr/osm-vs-fantoir#359]
Quand on ouvre [Saint-Barthélemy-d’Anjou](https://bano.openstreetmap.fr/pifometre/?insee=49124), il ne se passe rien. Un tour dans la console révèle que [requete_pifometre_commune.py](https://bano.openstreetmap.fr/pifometre/requete_pifometre_commune.py?insee=49124) retourne une erreur 500.

(Accessoirement, ce serait bien d’afficher une erreur plutôt que de ne rien faire.)

**Comment by vdct** [comment]
Bonjour,
le code attendu par Pifomètre pour une commune est son code INSEE (et non son code postal). Pour Saint-Barthélemy-d'Anjou : https://bano.openstreetmap.fr/pifometre/?insee=49267 qui ce matin fonctionne correctement

**Comment by Ltrlg** [comment]
Ah mince, j’ai confondu. Bah du coup je ferme.
