### ISSUE TITLE
Erreur 500 à la mise à jour des données

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#36]
Sur la [page d'une commune quelconque](https://cadastre.openstreetmap.fr/fantoir/#insee=83116) la mise à jour des données BANO ne fonctionne pas.

La requête AJAX revient immédiatement en erreur 500.

**Comment by tuxayo** [comment]
Infos:
https://lists.openstreetmap.org/pipermail/talk-fr/2017-August/085732.html
https://forum.openstreetmap.fr/viewtopic.php?f=2&t=1187&start=300#p16558

**Comment by tuxayo** [comment]
Problème réglé.

**Comment by tuxayo** [comment]
Même si les MAJ journalières remarchent. Celles à la demande continuent de souffrir du même problème.

**Comment by vdct** [comment]
Entre temps la màj à la demande a disparu dans sa première forme, et vient de revenir dans la v2. Je clos
