### ISSUE TITLE
Mauvais affichage code couleur dans Pifomap

### ISSUE THREAD

**Issue by zorglubu** [osm-fr/osm-vs-fantoir#362]
Bonjour,

J'essaie de repérer les manques d'adresses en utilisant par exemple cette carte :
https://bano.openstreetmap.fr/pifometre/pifomap.html?ratio=A#map=11.73/46.0233/2.5225

Auzances apparaît actuellement en vert foncé et devrait donc avoir 75% d'adresses renseignées, non ?
Or le taux actuel est de 9 %, la couleur devrait être plutôt rouge vif  : https://bano.openstreetmap.fr/pifometre/index.html?insee=23013

C'est un souci que j'ai rencontré plusieurs fois, il doit y avoir une erreur dans le calcul. Merci.

**Comment by vdct** [comment]
> il doit y avoir une erreur dans le calcul.

C'est le moins qu'on puisse dire :laughing: Il y avait une belle erreur (une inversion dans la formule) qui rendait l'affichage bien faux. Merci pour le signalement, ça semble bon maintenant. Je te laisse vérifier.

**Comment by zorglubu** [comment]
ça a l'air bien. Merci !
