### ISSUE TITLE
[Suggestion] Lien direct pifomap de la voie sur la page "voies ou lieux-dits inconnus d'OSM, classés par nombre d'adresses"

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#376]
Salut :) Je me sers de cette page tous les jours dégommer du rouge, ça marche bien pour faire par ordre de priorité.
Un truc qui pourrais accélérer le processus c'est de ne pas devoir passer par la page pifomètre de la commune et chercher dedans le lien pifomap de la voie.
Ça fait des actions en moins et éviter de charger une page qui est assez lourde. (je sais pas si c'est surtout du JS qui bosse ou la requête côté serveur.)

C'est des actions faites à la chaîne quand on cherche une voie ajoutable directement sans besoin de vérifier sur le terrain. Il y a plein de cas où c'est des divergences de noms entre OSM et les autres sources de BANO ou divergence entre BANO et Topo/fantoir. Et là je passe à la suivante dans la liste souvent plusieurs fois avant de trouver.

**Comment by vdct** [comment]
> ne pas devoir passer par la page pifomètre de la commune et chercher dedans le lien pifomap de la voie.

Merci pour la suggestion. En effet le lien est absent et y a pas vraiment de débat, il devrait être là 👍 
Pas sûr de pouvoir faire ça avant le SOTM, mais bientôt

**Comment by tuxayo** [comment]
Par chance quelqu'un d'autre a ajouté le lien pifomap vers la commune :D Et j'ai tenté de compléter dans https://github.com/osm-fr/osm-vs-fantoir/pull/381

**Comment by tuxayo** [comment]
C'est déployé et ça marche trop bien :D
Du coup le workflow passe de 
- aller sur top_adresses_manquantes.html
- trouver la 1re voie non déjà examinée
- ouvrir pifomètre commune
- chercher la voie
- ouvrir lien pifomap
- voir si c'est ajoutable dans OSM sans devoir aller sur le terrain ou si il faut passer. (en général car déjà dans OSM avec un nom un peut différent)
- si on a passé: dans top_adresses_manquantes.html cliquer sur le lien ORG de la voie pour qu'il soit marché comme visité par le navigateur pour pouvoir facilement "trouver la 1re voie non déjà examinée"

à ça:
- aller sur top_adresses_manquantes.html
- trouver la 1re voie non déjà examinée (grâce aux liens pifomap marqués comme visités)
- ouvrir lien pifomap
- voir si c'est ajoutable dans OSM sans devoir aller sur le terrain ou si il faut passer. (en général car déjà dans OSM avec un nom un peut différent)

Et c'est tout :D
(si quelqu'un a d'autres idées sur comment dégommer du rouge le plus efficacement possible c'est très bienvenu :) )


Merci @Khomille pour avoir ajouté le lien où il ne restait plus que les coordonnées de la voie à rajouter. J'avais cherché comment faire pour la 1re partie mais pas trouvé.
