### ISSUE TITLE
Ajouter license

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#38]
Sinon c'est du "all rights reserved" pas défaut.

Si une licence libre copyleft est choisie, attention à ce qu'elle couvre le cas du SaaS (exemple: AGPL vs GPL)

**Comment by jocelynj** [comment]
@vdct : je peux mettre BSD pour la licence ?

**Comment by Jean-BaptisteC** [comment]
La licence à été ajouté, ce ticket peut être clôturé ?

**Comment by vdct** [comment]
Oui en effet
