### ISSUE TITLE
Afficher les communes voisines sans recharger la page

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#380]
Sur pifomap, on est capable d’accéder à n'importe qu'elle commune de France via le bouton dé sans que la page ne soit rechargé.
Il pourrait être intéressant d'utiliser la même méthode lorsqu'on souhaite accéder aux communes voisines.

**Comment by vdct** [comment]
Merci pour l'idée @Jean-BaptisteC 
Fix réalisé par @Khomille et maintenant dispo :+1:

**Comment by gendy54** [comment]
J'ai l'impression qu'on peut clore le ticket ?

**Comment by Jean-BaptisteC** [comment]
Il est déja fermé :)
