### ISSUE TITLE
pifomap: le fond carte n'affiche pas assez bien les noms de voies

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#384]
Souvent je dois aller sur osm.org pour voir le rendu par défaut pour confirmer si une voie ou pas est déjà nommée dans OSM.

Exemple: https://bano.openstreetmap.fr/pifometre/pifomap.html?insee=13047&ratio=no#map=19.62/43.5132178/4.9891034

Le nom La Grande Rue des Fabres n'est jamais rendu dans HOT même si on zoome à fond et qu'on parcours toutes la longueur.
Et en général la longueur et la géométrie des rues fait qu'on ne peux pas facilement trouver le nom sur la couche vectorielle pifomap car c'est écrit une seule fois au milieu. Contrairement à ici ou sa va. (par chance la voie est courte et droite)
Mais même quand le nom tombe par chance là ou on regarde, c'est pas toujours facile de cliquer dessus ou de voir bien l’orthographe en entier à cause des superpositions des données sur la couche vectorielle pifomap. Car en cherchant du rouge on tombe souvent sur des endroits un peu en pagaille ^^"

Ce qui fait que c'est bien plus fiable d'utiliser le fond de carte, mais du coup pas avec le rendu HOT qui souvent n'affiche que difficilement le nom d'une voie. (faut zoomer et se déplacer sur la longueur) Et avec le rendu par défaut osm.org on arrive toujours à régler ces cas. Car les noms s'affichent plus facilement sans zoomer et sont répétés plus souvent. Mais c'est des étapes en plus d'alterner avec osm.org

Est-ce que c'est possible de soit changer le fond par default (pour mettre osm.org ou osm-fr ou autre), soit mettre un sélecteur qui se souvient du choix fait?
C'est pas facile de montrer à des gens la marche à suivre pour dégommer du rouge donc ne pas avoir changer très souvent de fond de carte éviterait de rajouter une étape.

**Comment by vdct** [comment]
Merci pour la suggestion, c'est en ligne cf https://forum.openstreetmap.fr/t/la-gazette-de-pifomap-version-mobile/26190/10 :+1:

**Comment by tuxayo** [comment]
Merci! trop bien, je vais pouvoir encore plus fluidement passer en revue des voies ou lieux-dits inconnus d'OSM :D

**Comment by tuxayo** [comment]
Si quelqu'un passe par ici et que la fonction ne marche pas, c'est car il n'y a pas d'asset versioning dans l'appli, je crois:
https://ana-balica.github.io/2014/02/01/autoversioning-static-assets-in-flask/

J'ai une erreur "Error: Cannot get style of non-existing layer "OSM-standard-tiles"." même en rafraîchissant la page avec ctrl-F5, qui du coup ne doit pas invalider bien tout le cache de la page web.
Ici ça doit faire qu'on est a cheval entre deux versions de l'appli.

contournement du bug: vider le cache de tout le navigateur ou attendre genre deux jours.

(aussi: tant que j'avais pas fait ctrl-F5, le lien pour charger dans JOSM ne marchait pas)

**Comment by tuxayo** [comment]
> J'ai une erreur "Error: Cannot get style of non-existing layer "OSM-standard-tiles"." même en rafraîchissant la page avec ctrl-F5, qui du coup ne doit pas invalider bien tout le cache de la page web.
> Ici ça doit faire qu'on est a cheval entre deux versions de l'appli.

C'est bon plus d'erreur et le changement de fond fonctionne :D Sur un navigateur où j'avais pas manuellement vidé le cache pour tester le fonctionnement réel du pifomètre, celui par défaut pour tout le monde.

Bonus de pouvoir choisir le rendu par default: il est possible de le rafraîchir de force et de voir des modifs 3 min après un changeset.
