### ISSUE TITLE
Retirer le background color dans la légende

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#386]
Avant
![image](https://github.com/user-attachments/assets/4eeccb3f-7258-413d-a60d-9969af32e118)

Après
![image](https://github.com/user-attachments/assets/4a3a3416-911f-48c1-95bc-55b60a35b753)

https://github.com/osm-fr/osm-vs-fantoir/blob/6654605b88ef2a4833c50b4191a2a46418bf5c3c/css/style.css#L813

- https://bano.openstreetmap.fr/pifometre/pifomap.html
- https://bano.openstreetmap.fr/pifometre/stats_dept.html

**Comment by Khomille** [comment]
Sur la carte, les textes en rouge, vert ou bleu sont écrits sur background blanc (enfin, techniquement avec un gros contour blanc).
La légende reflète ce style, c'est son rôle.

**Comment by Jean-BaptisteC** [comment]
Ok, pareil pour l'aide sur stats_dept.html ?

**Comment by Khomille** [comment]
Alors là, c'est un choix esthétique (déjà présent dans Pifomètre v2 avec d'autres couleurs), discutable comme tous les choix esthétiques 😄 C'était pour mieux faire ressortir les intertitres.
