### ISSUE TITLE
Aligner verticalement la pastille avec le texte

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#388]
![image](https://github.com/user-attachments/assets/557c8c71-4643-4c68-89b3-39bc3d02c540)

**Comment by vdct** [comment]
Non, le parti pris actuel est de garder un équilibre entre temps passé, complexité du code (ici css) et donc facilité de maintenance. Inutile d'aller vers ce niveau de détail, en tout cas dans Pifometre/Pifomap
