### ISSUE TITLE
Icones superposées

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#390]
![image](https://github.com/user-attachments/assets/7b510810-87fb-4196-981b-877f1d16d3db)

Réduire la hauteur comme on aurait sur la carte avec un numéro à 2 chiffres ou 3 chiffres peut résoudre le problème

https://bano.openstreetmap.fr/pifometre/numeros.html?insee=57463&fantoir=574636505&source=BAN&tab=0

**Comment by vdct** [comment]
Corrigé par @Khomille dans #399
