### ISSUE TITLE
Barre horizontal de défilement inutile

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#391]
Sur cet page https://bano.openstreetmap.fr/pifometre/numeros.html?insee=57463&fantoir=574636505&source=BAN&tab=0
J'ai une barre de défilement horizontal en bas qui n'a pas beaucoup d’intérêt, elle est causé par le fait que le style `#reponse_et_map` utilise width:100% et margin-left:2%
Passer à width:98% ou supprimer la propriété width peut résoudre le problème mais forcément on perd un peu d'espace entre la tableau et la carte

**Comment by vdct** [comment]
Corrigé par #398
