### ISSUE TITLE
L'export d'avancement par commune n'utilise pas de ; comme séparateur

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#393]
Exemple pour tester:
- https://bano.openstreetmap.fr/pifometre/stats_dept.html#dept=88

**Comment by vdct** [comment]
corrigé par ta PR #395

**Comment by Jean-BaptisteC** [comment]
Le fait d'avoir ajouté `fixes #393` dans la pr, ça ferme automatiquement l'issue :)
