### ISSUE TITLE
L'export csv des voies inconues contient des quotes

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#394]
Dans la colonne commune, chaque commune à des quotes
Exemple pour tester:
- https://bano.openstreetmap.fr/pifometre/voies_recentes_manquantes.html?dept=88&offset=0

Concerne aussi l'export des adresses sans rues

https://github.com/osm-fr/osm-vs-fantoir/blob/becd2ea3db24994e3a219db9127ba70306509dc0/voies_recentes_manquantes_dept.py#L20

**Comment by vdct** [comment]
merci pour le signalement
