### ISSUE TITLE
MàJ fichier Fantoir

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#40]
Fantoir a une màj trimestrielle depuis 2017. 

Dernière en date 06/02/2018 (cf https://www.data.gouv.fr/fr/datasets/fichier-fantoir-des-voies-et-lieux-dits/ )

Prévoir Intégration régulière  à osm vs Fantoir ?

**Comment by deuzeffe** [comment]
Dernière màj 6 août 2018.
(comment ça, j'insiste ? ;-p)

**Comment by vdct** [comment]
La màj de juillet 2019 (dernière dispo à ce jour) est intégrée sur la version "Bano v2", pour l'instant à cette adresse : https://dev.cadastre.openstreetmap.fr/fantoir/

**Comment by deuzeffe** [comment]
Thx a lot beaucoup énormément :-p
