### ISSUE TITLE
[Pifo] Menu burger inopérant sous FF

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#408]
Bonjour,

J'ai tellement bridé mon FF (102.14.0esr pour l'heure) que le nouveau menu burger déroulant est inopérant - le curseur passe bien en mode "Y a un lien là-dessous, clique !" mais le clic ne renvoie rien, snif. Suis-je la seule à ne pas le voir sous FF ?

Sous Chromium, ça donne un machin, "gros" mais bien visible : 
![Screenshot_20240817_160228](https://github.com/user-attachments/assets/1d11736e-f68a-4b39-ad67-ad7492c54db7)

C'est moi ou bien ?
Merci pour la réponse quelle qu'elle soit.

**Comment by tuxayo** [comment]
Est-ce que en navigation privée ça marche? (et que ça ne marche toujours pas en navigation normale)

Si oui alors c'est probablement ce qui est décrit là: https://github.com/osm-fr/osm-vs-fantoir/issues/384#issuecomment-2292803816

**Comment by deuzeffe** [comment]
@tuxayo pas compris quel lien il y a avec "mon" bug :p 
Pour te répondre, c'est inopérant, quelle que soit la fenêtre de FF : normale, privée ou dans un container.

**Comment by Khomille** [comment]
J'ai eu le temps de me pencher sur ce problème ce soir. Aucun rapport avec la suggestion de tuxayo ; c'est ta version de Firefox qui ne savait pas comprendre le code CSS du nouveau menu. Je suppose qu'elle est plus ancienne que la mienne (128.0.3).

Je l'ai réécrit différemment et normalement ça devrait bien s'afficher sur toutes les versions de tous les navigateurs, maintenant.

C'est ok chez toi @deuzeffe ?

**Comment by deuzeffe** [comment]
> J'ai eu le temps de me pencher sur ce problème ce soir. Aucun rapport avec la suggestion de tuxayo ; 

Tu me rassures :)

> c'est ta version de Firefox qui ne savait pas comprendre le code CSS du nouveau menu. Je suppose qu'elle est plus ancienne que la mienne (128.0.3).

Vi... Je ne suis pas encore passée aux versions actuelles en 12x

> Je l'ai réécrit différemment et normalement ça devrait bien s'afficher sur toutes les versions de tous les navigateurs, maintenant.

Merci d'avoir pris le temps d'y avoir consacré un bout de ta soirée.

> C'est ok chez toi @deuzeffe ?

Yep. Ça maaaaaaarche !

Grand merci.
(je ferme)
