### ISSUE TITLE
pifomap: est-ce encore possible de voire la date des données OSM rapprochables avec une commune?

### ISSUE THREAD

**Issue by tuxayo** [osm-fr/osm-vs-fantoir#409]
Avant les mises à jour récentes, on pouvais hover sur le bouton de rapprochement et ça disait la date des données OSM. Ce qui permet de voir que en temps normal, au bout de quelques minutes, on peut rapprocher pour vérifier si des modifs marchent comment attendu. (et être content du voir du rouge disparaître :D)

Ou attendre les fois où il y a quelques heures de retard sur les données.

**Comment by tuxayo** [comment]
Peut être qu'il y a une raison technique pour laquelle c'est pas possible de maintenir cette fonction.

**Comment by Khomille** [comment]
C'était un oubli ! On a changé en coulisses le fonctionnement de cette infobulle sur Pifomètre, et j'ai oublié de faire les mêmes changements sur Pifomap. 

Merci de l'avoir repéré :) 

C'est corrigé.

**Comment by tuxayo** [comment]
wow ça marche! :D

Merci ^^
