### ISSUE TITLE
Problème lors de la mise à jour des données OSM - touche refresh

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#42]
Bonjour,

Le touche refresh me retourne une erreur. "Problème lors de la mise à jour"

Test fait avec http://cadastre.openstreetmap.fr/fantoir/#insee=30276&tab=0

j'ai aussi testé en https. Même problème.

**Comment by vdct** [comment]
Bonjour,
Merci pour le signalement. Sans accès au backend à l'instant je fais le même constat. Je regarde dès que possible.

**Comment by geostonemarten** [comment]
Je ne sais pas si cela a un impact mais j'ai transféré des noms mis à la rue sur les _landuse_ car c'est plus la réalité. (Il peut aussi y avoir une coexistence des deux.)
**landuse=residential + name=Lotissement des Saladelles**
avant **highway=residential + name=Lotissement des Saladelles**

Pour la plupart de ces lotissements il y a aujourd'hui une voie avec le nom du lotissement en question
**landuse=residential + name=Lotissement d'Aou Fare
highway=residential + name=Rue d'Aou Fare**

Je dois encore voir avec l'administration local.

**Comment by Bibi56** [comment]
@geostonemarten ça me semble problématique d'opérer de la sorte car deux lotissements peuvent se toucher. En tant que `landuse` c'est une seule zone. Pour FANTOIR et nous ce sont deux zones.
Si tu mets deux `landuse` identiques côte à côte tu vas avoir des traits de séparation entre deux choses identiques. Pas très logique. Un exemple alternatif avec des `boundary=place` :  les relations [Le Prat](https://www.openstreetmap.org/relation/10060749#map=18/47.78700/-3.48716&layers=N) et [Les Jardins de Vitalis](https://www.openstreetmap.org/relation/10110420#map=18/47.78700/-3.48716&layers=N) ont une frontière commune.

**Comment by vdct** [comment]
> Le touche refresh me retourne une erreur. "Problème lors de la mise à jour"
> 
> Test fait avec http://cadastre.openstreetmap.fr/fantoir/#insee=30276&tab=0
> 
> j'ai aussi testé en https. Même problème.

La touche refresh est à nouveau fonctionnelle suite à https://github.com/osm-fr/osm-vs-fantoir/commit/3e68052da8da0374cf7b3b8c73d0fd9ae262b471
Testée OK sur https://bano.openstreetmap.fr/fantoir/index.html#insee=30276 à l'instant suite à [ce changeset](https://www.openstreetmap.org/changeset/97727151)
