### ISSUE TITLE
doublon de fantoir

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#43]
Bonjour,

je repars sur mon exemple de ce matin mais il y a des choses bizarre dans la liste:

Voies avec adresse(s) numérotée(s) > voies FANTOIR avec rapprochement OSM
302760032M | RUE DU 19 MARS 1962 (X2)

Faux négatif dans les rapprochements. Je pense qu'il faut dédoublonner et donner la priorité au voie avec adresse

Voies avec adresse(s) numérotée(s) > voies FANTOIR sans rapprochement OSM
302760136A | RUE MIREIO
Voies sans adresse(s) numérotée(s) > voies FANTOIR avec rapprochement OSM
302760136A | RUE MIREIO | Rue Mireïo

Voies avec adresse(s) numérotée(s) > voies FANTOIR sans rapprochement OSM
302760040W | RUE DU CANTONNAT | --
Voies sans adresse(s) numérotée(s) > voies FANTOIR avec rapprochement OSM
302760040W | RUE DU CANTONNAT | Rue du Cantonnât

En fait il doit rester 2 voies dans la liste non rapproché car à vérifier avec la collectivité.

C'est potentiellement ce qui pose problème pour le rapprochement

**Comment by vdct** [comment]
Problèmes non constatés dans la nouvelle version deBANO (v2) consultable ici : https://dev.cadastre.openstreetmap.fr/fantoir/#insee=30276&tab=0
