### ISSUE TITLE
Rajouter bouton copie du code Fantoir depuis Pifomap

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#431]
Dans les usages que j'ai, c'est de copier le code Fantoir depuis Pifomap pour le rajouter à la voie.
Pour le nom de voie, il y a le bouton de copie très pratique. J'aimerai le même pour le code Fantoir et éviter de devoir sélectionner puis copier/coller. Ma tendinite du poignet vous remerciera 

![image](https://github.com/user-attachments/assets/df842b4c-4058-4afd-8364-9b0c5657e511)

**Comment by Khomille** [comment]
Bonne idée ! C'est fait :)

![image](https://github.com/user-attachments/assets/7b933e89-bb9b-4c38-a0bf-2fe2a77912e1)

**Comment by gendy54** [comment]
Pour la petite histoire, je viens juste de m'en servir sur la 1ère que je viens de rajouter ce soir ;)
