### ISSUE TITLE
Prendre en compte les voies uniquement BAN dans les listes départementales des voies manquantes

### ISSUE THREAD

**Issue by Ptigrouick** [osm-fr/osm-vs-fantoir#434]
Les listes départementales des voies manquantes ne proposent les voies que si elles sont présentes dans le fichier TOPO. Les voies manquantes présentes seulement dans la BAN ne sont pas listées. Pour trouver les voies BAN manquantes dans OSM il faut parcourir au hasard les pages pifomètre des différentes communes, ce qui est assez fastidieux. Ce serait bien pratique d'avoir soit une liste dédiée pour les voies BAN, soit une liste unique qui contient tout mais avec un bouton TOPO / BAN pour permettre de n'afficher qu'un seul type de signalement.

**Comment by vdct** [comment]
En quoi ce que tu souhaites serait différent de ça :

https://bano.openstreetmap.fr/pifov3-dev/top_adresses_manquantes.html?dept=34&offset=0 ?

**Comment by Ptigrouick** [comment]
En fait je voulais séparer la liste fantoir de la liste purement BAN. Mais je me rends compte que sur la liste top_adresses en utilisant le filtre sur la colonne "code fantoir" avec "34" ou "Voie sans Fantoir" j'obtiens ce que je souhaite. J'y avais même pas pensé avant...
