### ISSUE TITLE
Qualification des adresses absent dans Pifomap

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#436]
Dans Pifometre, on a pas le lien vers "Qualifier les adresses" car voie sans Fantoir alors qu'il y est dans Pifomap.

![image](https://github.com/user-attachments/assets/6b5b2fbd-d9ba-49b7-9e7f-77611af83c39)

![image](https://github.com/user-attachments/assets/4e5954b3-713a-426a-9f6b-fbbafbea76bb)

Mais tu disais: "C'est l'inverse : il ne devrait pas être présenté dans Pifomap car on n'a pas de code Fantoir"
Mais du coup, qu'est ce qui est gênant dans le fait de l'avoir si c'est pour remonter des erreurs ?

**Comment by vdct** [comment]
Voilà, c'est supprimé de Pifomap, ça évitera de faire des signalements qui ne sont pas stockés... merci :)
