### ISSUE TITLE
Pas d'affichage de la barre de recherche sur la page des voies inconnues

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osm-vs-fantoir#437]
Sur la page voies inconnues d'OSM, lorsqu'on charge un département complet, parfois la barre de recherche n'est pas affiché ce qui empêche de pouvoir trier par ordre alphabétique

Reproduit souvent avec le département de la Moselle
https://bano.openstreetmap.fr/pifometre/voies_recentes_manquantes.html?dept=57&offset=0

**Comment by gendy54** [comment]
maintenant que tu le dis, ca m'est arrivé quelques fois sans comprendre si j'avais rêvé ou pas.

**Comment by Khomille** [comment]
Je n'arrive pas à reproduire ce problème d'affichage. 
Est-ce que vous voulez dire que quand on scrolle le tableau, la première ligne d'en-têtes / filtres remonte et disparaît de la page par le haut ?

**Comment by Jean-BaptisteC** [comment]
Non en fait on clique sur afficher après avoir saisi le numéro de département
Et la ligne des recherches n'est pas affichés en haut du tableau alors qu'on est en haut de l'écran
Exemple ci dessous
<img src="https://github.com/user-attachments/assets/2ac0e324-258c-4bd6-a73f-4b27c70853db" height=400/>

**Comment by Khomille** [comment]
Chelou. 
Bon, je viens de faire une correction qui règle le problème de la barre de filtres qui disparaît en haut quand on scrolle. Maintenant elle reste fixe.

Avec un peu de chance, ça résout ton problème au passage ?

**Comment by Jean-BaptisteC** [comment]
Malgré la correction, j'ai toujours le problème que ce soit sur Chrome ou Firefox en mode desktop et mobile.
Mais maintenant, j'ai le problème quand je scroll vers le bas et que je scroll ensuite vers le haut. La ligne de haut n'est pas réaffiché

**Comment by Jean-BaptisteC** [comment]
J'ai l'impression que lorsque on ouvre la page c'est bon, ça a l'air de ne pas fonctionne quand on reclique de nouveau sur le bouton afficher

**Comment by Khomille** [comment]
Ah oui, en effet. J'ai enfin réussi à reproduire le problème en faisant comme ça.
Je vais regarder si on peut y faire quelque chose, merci

**Comment by Khomille** [comment]
On a trouvé, et c'est réparé 👍 (sur d'autres pages aussi d'ailleurs)

**Comment by Jean-BaptisteC** [comment]
Ca fonctionne merci 🙂
