### ISSUE TITLE
Le chargement de la page n'aboutit pas

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/osm-vs-fantoir#46]
Bonjour,

la page de statistiques par département charge indéfiniment :
https://dev.cadastre.openstreetmap.fr/fantoir/stats_dept.html#dept=973

**Comment by vdct** [comment]
@adrienandrem je te laisse tester ? Normalement c'est corrigé. Si c'est ok pour toi tu peux fermer le ticket, sinon commentaires bienvenus.
merci

**Comment by adrienandrem** [comment]
Ça fonctionne parfaitement. Merci !
