### ISSUE TITLE
Relations associatedStreet : ajouter les ways

### ISSUE THREAD

**Issue by vdct** [osm-fr/osm-vs-fantoir#49]
Pour que le srelations associatedStreet soient d'avance plus complètes, ajouter les ways avec le rôle street et le nom de voie correspondant

**Comment by Bibi56** [comment]
Et si possible partir de la relation existante dans OSM ?

**Comment by vdct** [comment]
Oui construire une relation n'a pas de sens quand une existe déjà. Ce ticket n'est valable qu'en cas d'absence de relation sur la voie concernée. L'existence d'une relation dans OSM sera rendue possible par https://github.com/osm-fr/bano/commit/f7093d600cdfdc152ac2aa4fcb131e44e0fae2e3

**Comment by Bibi56** [comment]
Peut-être que lors que cette création de relation il est possible de remonter des incohérences : 
La Rue des Moulins est visiblement plus longue que ne l'indique [OSM](https://www.openstreetmap.org/search?query=Rue%20des%20Moulins%2C%20Mo%C3%ABlan-sur-Mer#map=19/47.81658/-3.63040) et 
https://bano.openstreetmap.fr/fantoir/index.html#insee=29150&tab=1
https://www.openstreetmap.org/way/177521590 : même référence (C 8) mais sans nom or des points adresse en font partie.
Nice to have^^ sinon avec JOSM on voit les incohérences.
Ce serait bien que les relations soient triées : les ways (continus si possible en commençant par ceux proches des plus petits numéros) suivis des points adresse par numéro croissants.

**Comment by vdct** [comment]
Complété par https://github.com/osm-fr/osm-vs-fantoir/issues/113
