### ISSUE TITLE
Générer un message quand le contrôle à distance JOSM n'est pas active

### ISSUE THREAD

**Issue by ray66** [osm-fr/osm-vs-fantoir#50]
Quand on clique sur in lien JOSM et JOSM n'est pas active ou le contrôle à distance n'est pas autorisé, il n'y pas de message pour indiquer ce fait à l’utilisateur. Je propose d'ajouter un message. Voici un exemple de code :  

    $.ajax({url: josm_remote_link, 
       error: function(t){
       if (t.status!=200)
          alert("JOSM remote control did not respond (" + t.status + "). Do you have JOSM running?");
    });

**Comment by vdct** [comment]
Merci pour la suggestion @ray66 
Je viens de publier une version avec cette évolution, tes remarques bienvenues
