### ISSUE TITLE
page principale absente

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#54]
mettre un contenu sur la page principale
http://dev.cadastre.openstreetmap.fr
au moins un lien vers les différentes url dispo sur dev.cadastre*

**Comment by gendy54** [comment]
@Marc-marc-marc Tous les liens sont référencés sur la page Bano [](https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO), faute mieux pour le moment.

**Comment by vdct** [comment]
On pourrait les présenter sur la page principale en effet, ainsi qu'un lien vers le répertoire des exports BANO d'ailleurs. PR bienvenues !

**Comment by gendy54** [comment]
Euh je passe mon tour pour les PR ;)

**Comment by Marc-marc-marc** [comment]
c'était un problème de config, extrait de `/var/log/apache2/cadastre.openstreetmap.fr-access.log` : 

> client denied by server configuration

Corrigé en rajoutant `Require all granted`dans la directive `Directory` de `/etc/apache2/sites-enabled/cadastre.openstreetmap.fr.conf`

Par contre pour le PR de la page elle-même, où la veux-tu ?
Sur le serveur la page est un niveau au dessus de l'arborescence de ce dépôt.
En attendant j'ai fait une [page](http://dev.cadastre.openstreetmap.fr/) à l'arrache, pure texte, directement sur le serveur dev

**Comment by vdct** [comment]
@Marc-marc-marc  Merci. J'ai fait une redirection permanente depuis ta page initiale vers une copie placée dans le dossier racine du dépôt, cf le commit ci-dessus. Donc maintenant on peut faire des PRs pour enrichir et/ou enjoliver cette page de liens

**Comment by gendy54** [comment]
Comment on fait concrètement pour rendre la page plus belle? Ca se passe où? C'est compliqué? Etc...

**Comment by vdct** [comment]
Ca peut se passer dans la page elle même, où tu utilises le langage CSS (https://www.w3schools.com/css/default.asp) pour décrire l'apparence des éléments HTML de la page. Il suffit d'un éditeur de texte et d'un navigateur pour tester le résultat, donc assez abordable si tu veux t'y essayer
