### ISSUE TITLE
Voies inconnues - marqueur sur lien openstreetmap.org

### ISSUE THREAD

**Issue by adrienandrem** [osm-fr/osm-vs-fantoir#59]
Sur la page [Voies récentes inconnues d'OSM](http://dev.cadastre.openstreetmap.fr/fantoir/voies_recentes_manquantes.html), ajouter le marqueur aux liens vers openstreetmap.org  
aiderait lorsque les voies sont proches :

Exemple d'URL :
https://www.openstreetmap.org/?mlat=48.64966&mlon=4.96804#map=19/48.64966/4.96804

**Comment by vdct** [comment]
@adrienandrem je te laisse tester, merci

**Comment by adrienandrem** [comment]
Ça fonctionne, merci !
