### ISSUE TITLE
Connaître l'origine d'un rapprochement

### ISSUE THREAD

**Issue by vdct** [osm-fr/osm-vs-fantoir#6]
Indiquer dans les tabeaux, par ligne, l'origine du rapprochement Fantoir <-> OSM : par algorithme ou via les données Fantoir stockées dans OSM.

**Comment by gendy54** [comment]
Je remonte les vieux tickets.
L'idéal serait de l'intégrer dans l'onglet Pifomètre, mais y a plus beaucoup de place et ca va commencer à être chargé.
Du coup, je propose de l'afficher dans Fantoir brut dans une nouvelle colonne immédiatement à droite de la colonne Rapproché ? pour ne pas interférer avec le code couleur vert et orange qui devrait être encore subdivisé.
Si pas de place, on peut gagner de la place soit en réduisant d'autres colonnes bien larges comme caractère_voie et/ou _caractère_annulation_, soit en supprimant la colonne dept et _code_insee_

**Comment by vdct** [comment]
On n'a pas cette info dans BANO finalement
