### ISSUE TITLE
Codes Fantoir erronés

### ISSUE THREAD

**Issue by gendy54** [osm-fr/osm-vs-fantoir#71]
Salut Vincent,

Dans http://dev.cadastre.openstreetmap.fr/fantoir/fantoir_errone.html, on a pas les codes Fantoir avec le code direction?
Ce serait peut-être pas mal de les rajouter pour les débusquer plus facilement qu'avec une requête Overpass, non?
Je propose de les rajouter dans cette page mais pas mélangé avec les autres Fantoir.

**Comment by vdct** [comment]
Non, les codes Fantoir ne respectant pas le format de 10 caractères sont retoqués avant d'entrer dans BANO, et ici ce sont ceux présents dans BANO qu'on liste. Inutile de faire entrer ces codes dans BANO vu qu'on considère d'avance qu'ils sont non conformes et donc qu'ils ne permettront pas de rapprochement.
Là ce que tu veux ce sont les codes erronés présents dans OSM "tout court". On pourrait les présenter à part sur la page, en indiquant que leur souci est (au moins) le non respect du format, en effet.

**Comment by gendy54** [comment]
C'est en effet ton 2nd paragraphe qui m'intéresse. Juste débusquer les codes Fantoir avec le code direction en trop.

**Comment by Bibi56** [comment]
N'est-ce pas plutôt le boulot d'Osmose ? Rien contre ceinture et bretelles pour autant.

**Comment by gendy54** [comment]
Si ca peut l'être, mais il me semble préférable de réunir au même endroit tout ce qui concerne Fantoir.
