### ISSUE TITLE
Annulation d'entrée(s) FANTOIR

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#72]
Hello,

Dans le descriptif du fichier FANTOIR (https://www.data.gouv.fr/fr/datasets/r/7c52d813-1e98-4772-8a7a-6a01f9d30c6e) on trouve un "champ" Caractère d'annulation (O ou Q) et un pour "Date d'annulation".

Ne serait-il pas intéressant, pour les voies non rapprochées dans un premier temps, de faire figurer cette info. pour affiner l'analyse des non-rapprochements ?

Rq : comme prévu, ce type d'info. n'est pas toujours à jour, ou est plus ou moins fantaisiste... J'en cause avec ma commune.

**Comment by vdct** [comment]
Désolé j'ai pas compris ce que tu proposes :/

**Comment by deuzeffe** [comment]
Laisse tomber, je n'ai pas vérifié qu'en fait, tu nettoyais déjà le Fantoir brut de ces enregistrements là. Tu peux délabéliser l'issue :) 
Mais ça veut dire aussi qu'il faut que j'alerte ma mairie sur encore un autre point...

**Comment by vdct** [comment]
> Laisse tomber, je n'ai pas vérifié qu'en fait, tu nettoyais déjà le Fantoir brut de ces enregistrements là. Tu peux délabéliser l'issue :)

Oui c'est bien le cas ici : https://github.com/osm-fr/bano/blob/packaging/bano/sources/fantoir.py#L22

Allez on ferme alors :)

**Comment by deuzeffe** [comment]
Rhha, mais si tu mets le code dans un autre dépôt, je suis perdue, moi ;-) (déjà fermé :P)
