### ISSUE TITLE
Changement de nom de voie / inverse de "Voie incorporée à une autre"

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#73]
Hello,

Je suis en train de tenter de compléter les adresses sur ma commune à partir de dev.cadastre.../fantoir

Et je n'ai pas trouvé la possibilité de notifier dans la colonne du Statut FANTOIR que la voie change de nom quelque part sur son trajet.

Par ex., il y a une loooongue rue F, qui tournicote. À un virage, elle change de nom en rue B. et à un autre en imp. F (c'est présent au cadastre mais pas dans le fichier FANTOIR. Bouhouhouhou :/). Certes je peux forcer le rapprochement avec le code FANTOIR (ce qui était déjà fait quand on a le code FANTOIR...), mais j'aimerais bien indiquer que la voie a été "splitée" et a changé de nom à l'occasion.

Une idée de signalement (l'inverse de "Voie incorporée à une autre" en somme) ?

(chais pas si mes explications sont très claires...)

**Comment by vdct** [comment]
Pour être sûr de comprendre : dans le cas que tu décris on a 3 voies OSM distinctes, chacune avec son nom (rue F, rue B, impasse F), et dans Fantoir uniquement rue F ? Si c'est ça, ok pour le rapprochement entre les rues F, ok aussi pour trouver de nouveaux intitulés de qualification-signalement. En revanche j'ai pas saisi si tu veux forcer des rapprochements autres, ni comment

**Comment by deuzeffe** [comment]
Oui, on a 3 voies distinctes : 
- rue F, présente au cadastre et dans FANTOIR ; MAIS la recherche des adresses à intégrer via ton interface me renvoie rue B. :/ comme si "quelque chose" n'était pas à jour "quelque part" et je ne sais pas quoi (j'ai bien une idée du suspect, mais bon...) ;
- rue B, présente au cadastre et dans FANTOIR ; c'est là où j'ai forcé le rapprochement ;
- imp F, présente au cadastre et pas dans FANTOIR :/ Donc forcer le rapprochement n'est pas possible :/ 

(j'ai l'impression qu'une image ne serait pas de trop ?)

Dans un premier temps, trouver déjà un intitulé de signalement, ça serait bien, oui.
Dans un second temps, on attendra que DGFIP et consorts se mettent à jour. Si jamais...

**Comment by vdct** [comment]
Ok je vois. Pour les adresses à intégrer, je n'ai qu'une source, un certain "Cadastre" :) Je veux bien au moins vérifier que je n'ai pas de bug dans l'intégration Bano pour les rues F et B, par un lien ici ou en MP

**Comment by vdct** [comment]
Vu ton exemple, est-ce que ce qui manque comme signalement ça serait pas tout simplement : voie présente sur le terrain et absente de FANTOIR ? Ca s'appliquerait ici à l'Impasse F.

**Comment by deuzeffe** [comment]
Bin... Si tu fais une analyse "Voies présentes dans osm mais inconnues au cadastre/fantoir", it makes sens. Sinon, je ne sais pas comment signaler une voie dont ton interface ne montre pas le nom :P

**Comment by vdct** [comment]
Oh là là oui, mon cerveau est resté en vacances :D 
En fait ça revient non pas à proposer une nouvelle entrée dans les signalements, mais à proposer l'onglet "Voies OSM non trouvées dans FANTOIR" ce qui colle avec https://github.com/osm-fr/osm-vs-fantoir/issues/69

**Comment by deuzeffe** [comment]
pi-le po-al ! ;)

**Comment by vdct** [comment]
@deuzeffe maintenant que #69 est dispo, comment fait-on évoluer ce ticket ? Qu'est ce qui reste un besoin, en lien avec ? Merci :)

**Comment by deuzeffe** [comment]
Bin non, plus d'intérêt, il me semble. On feeeeerme ! )
