### ISSUE TITLE
maj plus fréquente du rapprochement des rues

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#77]
Si la maj de la comparaison avec les diff d'osm ne prend pas trop de temps, il serrait agréable d'avoir une maj plus rapide que quotidienne.
il n'est en effet pas rare d'être 2 contributeurs sur le même département ciblant par exemple tous les 2 les voies les plus veilles.
si la maj à partir de n'importe quelle diff est chronophage, peut-être que les diff disposant d'une ref fantoir non rapproché pourrait elle déclencher cette maj, au moins pour le rapprochement de la rue concernée

**Comment by vdct** [comment]
Il existe dans la v1 du site une fonction de màj au niveau de la commune. Cette fonction est pour l'instant désactivée dans la v2 mais répond au besoin. Juste un peu de patience ;)

**Comment by Marc-marc-marc** [comment]
le bouton de la v1 n'est pas idéal pour traquer les rues traité pendant la journée (il est par contre pratique pour vérifier qu'une commune a été entièrement bien fait)
cas d'usage d'hier :
j'en prend une, j'ouvre osm, chouette elle est déjà ajoutée.
j'en prend une autre d'une autre commune que de la précédente, idem
je prend une 3ieme d'une autre commune que les 2 précédentes, idem
bref, j'aurais du faire X fois "rafraîchir la commune" jusqu'à trouver la commune non traitée, je passe régulièrement plus de temps à 23h à trouver un nom de voie manquant qu'à l'ajouter :)

une réaction à partir des diff n'est pas possible ?
si une ref fantoir apparaît dans un diff, déclencher la maj de la voie concernée

autre idée (mais moins pratique, parce que cela implique que le contributeur initial passe sur l'interface bano) : un bouton "traité" comme osmose, cela fait disparaître l'élément jusqu'à vérification lors de l'analyse complète.

**Comment by vdct** [comment]
> le bouton de la v1 n'est pas idéal pour traquer les rues traité pendant la journée (il est par contre pratique pour vérifier qu'une commune a été entièrement bien fait)
> cas d'usage d'hier :
> j'en prend une, j'ouvre osm, chouette elle est déjà ajoutée.
> j'en prend une autre d'une autre commune que de la précédente, idem
> je prend une 3ieme d'une autre commune que les 2 précédentes, idem
> bref, j'aurais du faire X fois "rafraîchir la commune" jusqu'à trouver la commune non traitée, je passe régulièrement plus de temps à 23h à trouver un nom de voie manquant qu'à l'ajouter :)

si une telle situation se produit, c'est un problème de riches : on a tellement de contributeurs sur le sujet que chacun n'arrive pas à se trouver une place pour bosser. Hélas c'est loin d'être le cas général vu le nombre de voies encore à traiter.
Dans un premier temps, à l'échelle d'une commune le rapprochement des rues est à nouveau possible à la demande suite à https://github.com/osm-fr/osm-vs-fantoir/commit/3e68052da8da0374cf7b3b8c73d0fd9ae262b471 Cette fonctionnalité pourra un jour être remplacée par une màj continue au fil des changesets arrivant dans la base OSM de BANO, mais ça n'est pas prioritaire.
