### ISSUE TITLE
Rapprochement non fait dans le listing avec area=yes

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#78]
Bonjour,

Il semble après plusieurs vérification que les rapprochements de nom de voie avec la clé area=yes ne soit pas fait

https://www.openstreetmap.org/way/83292128/history

http://dev.cadastre.openstreetmap.fr/fantoir/#insee=30059&tab=0

300590040P | PL LEDRU ROLLIN

**Comment by vdct** [comment]
C'est peut-être déjà ce qui était signalé ici : https://github.com/osm-fr/bano/issues/154
Merci pour l'exemple qui aidera à investiguer

**Comment by geostonemarten** [comment]
Ah oui en effet. Dans ton process interprètes tu la géométrie pour récupérer du linéaire? Ducoup suivant les conversions en base tu vas avoir du polygon.

**Comment by don-vip** [comment]
je crois que c'est corrigé au titre de https://github.com/osm-fr/bano/issues/154 ?

**Comment by vdct** [comment]
Oui tout à fait, merci :)
La place Ledru Rollin est maintenant rapprochée, sans besoin d'ajouter son ref:FR:FANTOIR
