### ISSUE TITLE
rapprochement autoroute

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#79]
Le rapprochement des autoroutes ne semble pas se faire
ref:FR:FANTOIR=592580005U
http://dev.cadastre.openstreetmap.fr/fantoir/#insee=59258&tab=2
https://www.openstreetmap.org/way/324162654

**Comment by vdct** [comment]
Le minimum pour tout rapprochement, autoroute ou pas, est de s'appuyer sur un tag name=*, qui est absent ici. Donc comportement normal en l'état. Sujet identifié dès le début de BANO : https://github.com/osm-fr/bano/issues/83. A discuter là bas plutôt qu'ici.
