### ISSUE TITLE
Rapprochement des groupes scolaires

### ISSUE THREAD

**Issue by don-vip** [osm-fr/osm-vs-fantoir#80]
31555A091E | GROUP SCOL ANDRE DASTE | https://www.openstreetmap.org/way/516565304

Considérer [amenity=school](https://wiki.openstreetmap.org/wiki/Tag:amenity=school) et/ou [landuse=school](https://wiki.openstreetmap.org/wiki/Tag:landuse=school)

**Comment by don-vip** [comment]
ticket à déplacer dans https://github.com/osm-fr/bano

**Comment by vdct** [comment]
=> https://github.com/osm-fr/bano/issues/168

**Comment by don-vip** [comment]
@vdct depuis quelques mois GitHub permet de [transférer des tickets d'un dépôt vers un autre](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository), sans avoir à recréer. Tu n'avais pas l'option ?

**Comment by vdct** [comment]
@don-vip merci, je me suis posé la question tout à l'heure mais j'aurais dû te la poser, plutôt !
