### ISSUE TITLE
Ajout des noms de voies OSM sans rapprochement mais existante dans OSM

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#81]
Bonjour,

En relation avec ma remarque sur la comparaison des adresses et des potentielles source peut-on déjà ajouter dans le comparatif les voies qui sont déjà renseignées mais pas existante dans la BAN mais renseigné dans OSM (terrain)

**Comment by deuzeffe** [comment]
cf https://github.com/osm-fr/osm-vs-fantoir/issues/69

**Comment by vdct** [comment]
> cf #69

indeed :)
Autant regrouper la discussion là bas
