### ISSUE TITLE
Visualiser les rues rapprochées par la référence FANTOIR

### ISSUE THREAD

**Issue by geostonemarten** [osm-fr/osm-vs-fantoir#82]
Dans les tableaux il serait intéressant de voir les rues qui sont rapprochés en mode forcé avec l'ajout de la référence FANTOIR.

Certains nom sont renseigné en prenant Fantoir en référence absolue et c'est pour moi un point de contrôle pour une vérification terrain ou un contact avec les administration pour faire le point.

**Comment by vdct** [comment]
Je comprends le besoin, cependant le processus de rapprochement ne permet pas de distinguer un mode forcé. 
Et pour la question de fond, à savoir trouver les rues où l'orthographe est celle de Fantoir et où ça ne colle pas avec la réalité du terrain : à mon sens c'est indétectable tout simplement parce que dans une majorité de cas l'orthographe Fantoir est correcte, à la normalisation près.
