### ISSUE TITLE
Afficher la date de création des voies non rapprochées

### ISSUE THREAD

**Issue by don-vip** [osm-fr/osm-vs-fantoir#85]
Exemple:
https://dev.cadastre.openstreetmap.fr/fantoir/#insee=31555&tab=2

Afficher le champ date_creation m'aiderait beaucoup à l'investigation pour savoir si les voies que je trouve pas sont des voies récentes créées en 2019 ou des voies qui ont disparu depuis les années 90 :)

Actuellement je dois aller chercher cette info dans une autre page:
https://dev.cadastre.openstreetmap.fr/fantoir/liste_brute_fantoir.html#insee=31555

**Comment by gendy54** [comment]
Je confirme, c'est bien chiant!
Merci de ce que tu pourras faire.

**Comment by don-vip** [comment]
> Perso c'est pas tant la création qui m'intéresse mais plutôt le critère "Q".

C'est quoi le critère Q ? Perso ce qu'a fait Vincent me convient et le ticket peut être clos.

**Comment by gendy54** [comment]
Le critère Q, c'est que la voie est historisée et ne sert plus.

**Comment by deuzeffe** [comment]
@gendy54 dans les tableaux de rapprochements, il n'y a plus les voies avec critères Q. 

En revanche, tu les trouves dans le fantoir brut (lien FANTOIR dans le bandeau, cf screenshot)
![Screenshot_2020-02-17 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM](https://user-images.githubusercontent.com/36087963/74679815-2cc60600-51bf-11ea-9eac-ffe7b7a75743.png) 

Et comme tu peux trier le fantoir brut lui aussi, tu as les lignes Q et la date d'annulation dans la colonne d'â-côté (cf autre screenshot)
![Screenshot_2020-02-17 Aixe-sur-Vienne - Liste FANTOIR Octobre 2019](https://user-images.githubusercontent.com/36087963/74679929-76aeec00-51bf-11ea-8cb2-8541f048a35d.png)

HTH

**Comment by vdct** [comment]
@gendy54 pour le critère Q @deuzeffe a tout dit. On peut réfléchir au sujet mais dans un ticket dédié. Ici je clos cf le commentaire de @don-vip
