### ISSUE TITLE
Problème de mise à jour de la liste des voies sans adresse, avec rapprochement

### ISSUE THREAD

**Issue by don-vip** [osm-fr/osm-vs-fantoir#86]
Depuis que je me concentre à faire baisser le nombre de voies sans adresse et sans rapprochement à Toulouse, je vois bien ce chiffre baisser sur https://dev.cadastre.openstreetmap.fr/fantoir/#insee=31555&tab=2, mais je ne vois pas le chiffre inverse augmenter, il reste bloqué à 25 sur https://dev.cadastre.openstreetmap.fr/fantoir/#insee=31555&tab=3

Exemple: j'ai rajouté la Promenade Claudius Regaud (**315552126X**) dans ce changeset https://www.openstreetmap.org/changeset/80055224#map=18/43.55532/1.42777

Elle a bien disparu de la liste des vois non rapprochées, mais n'apparaît pas dans la liste des voies rapprochées.

Pourtant dans la liste brute elle est bien marqué rapprochée: https://dev.cadastre.openstreetmap.fr/fantoir/liste_brute_fantoir.html#insee=31555

**Comment by vdct** [comment]
Dans le cas donné en exemple, le rapprochement ne s'est fait qu'avec les données OD, pas avec les données Cadastre. Or la vue "voies rapprochées avec adresses" jusque là on ne montrait que les voies de source Cadastre. En relachant la contrainte (qui n'a plus trop de sens) l'affichage sera plus cohérent normalement

**Comment by don-vip** [comment]
c'est sensé être corrigé avec ton commit ? J'ai toujours le problème.

**Comment by vdct** [comment]
Ah ? Moi je la vois dans l'onglet des voies rapprochées avec adresses (à cause d'une pseudo-adresse issue de l'Open Data... discutable)

**Comment by don-vip** [comment]
> à cause d'une pseudo-adresse issue de l'Open Data

Tu peux détailler ? C'est quoi cette "pseudo-adresse" ?

**Comment by vdct** [comment]
C'est une adresse dont le numero vaut "99999" donc ça ressemble aux adresses en 5000 ou 9000 du Cadastre, des adresses techniques. Il faudrait ne pas en tenir compte, ce qui transformerait cette voie en voie sans adresse. Cans ce but, il y a https://github.com/osm-fr/osm-vs-fantoir/issues/74 (WIP même si aucun commit ne lui est attribué)

**Comment by don-vip** [comment]
OK merci ! Du coup je confirme le fix :)
