### ISSUE TITLE
bano->josm ko Firefox ESR 68.4.1 josm version 15845

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osm-vs-fantoir#88]
Firefox ESR 68.4.1 avec "Blocage de contenu" définit sur "personnalisé : tout désactivé", aucune extension active.
josm version 15845 "activer le contrôle à distance" oui, "actions autorisées" : toutes, nouveau calque : non, confirmation manuel : oui
depuis par ex https://dev.cadastre.openstreetmap.fr/fantoir/index.html#insee=02590&tab=0
le chargement de la page provoque une demande d'autorisation pour "lire la version du protocole", autorisation donnée (si j'ai bien compris, cela permet à la page web de savoir que la télécommande est active").
clic sur le lien "relation", provoque une demandé d'autorisation pour chargée les données, autorisation donnée mais rien ne se charge dans josm (pas de couche supplémentaire, rien dans la couche active)
j'en ai touché un mot à @don-vip pour l'ajout d'un éventuel message d'erreur pouvant expliquer cet activation de la télécommande qui ne produit rien, ili a botté en touche en disant que c'était la faute à FF (qui n'a pas été maj entre le bon fonctionnement il y a quelques jours et aujourd'hui)

**Comment by Marc-marc-marc** [comment]
fonctionne avec josm 15806, je te laisse voir avec don-vip ?

**Comment by vdct** [comment]
Et ça marche comment avec Osmose ? Mêmes symptômes ?

**Comment by Marc-marc-marc** [comment]
pas de soucis, peu importe la version de josm

**Comment by vdct** [comment]
de mon côté aucun problème avec la FF 73.0  et la latest josm 15850 sous ubuntu 18.04

**Comment by vdct** [comment]
Comme discuté sur IRC hier : problème impossible à reproduire avec régularité, et spécifique d'une config temporaire (avec josm latest).
=> Je clos

**Comment by Marc-marc-marc** [comment]
pour mémoire : problème ayant aussi eu lieu entre temps avec la version josm-stable.
mais reproductibilité problématique.
don-vip m'ayant entre temps fournit la commande josm --trace, je rouvrirai si j'arrive à obtenir une trace du problème
