### ISSUE TITLE
Export CSV : champ "statut Fantoir" inexistant  

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#92]
Hello, 

Je me sers de l'outil pour, entre autres, faire le bilan auprès des édiles de ma commune des noms/types de voie à faire modifier auprès de la DGFiP (et affiliés). So, le statut fantoir (même s'il n'est pas encore triable) est une précieuse donnée à récupérer (en semi-automatique). So (bis), est-ce qu'il est possible de l'exporter dans le CSV ? Déjà, un Ok/Nok serait une avancée.

Merci pour la réponse, quelle qu'elle soit.

**Comment by deuzeffe** [comment]
À voir si ça fera partie du panier de cerises sur le gâteau de la v3 ?

**Comment by vdct** [comment]
@deuzeffe  j'ai mis une version en ligne pour le CSV communal, je te laisse tester ?

**Comment by deuzeffe** [comment]
@vdct ça me semble assez... impeccable !
Merci.
(c’était pas franchement pressé, hein)
