### ISSUE TITLE
Onglet 6 - changement de statut : grisé général à tort 

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#94]
Hello,

Comme un mauvais dessin vaut mieux qu'un grand discours : 

- avant : 
![Screenshot_2020-02-21 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM](https://user-images.githubusercontent.com/36087963/75073778-79c91580-54fa-11ea-906f-17f38d7cd57c.png)

- après : 
![Screenshot_2020-02-21 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-2](https://user-images.githubusercontent.com/36087963/75073871-aed56800-54fa-11ea-9c7f-ec7e0479bada.png)

- encore après : 
![Screenshot_2020-02-21 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-3](https://user-images.githubusercontent.com/36087963/75073949-de847000-54fa-11ea-9a46-18dbaa58dd8d.png)

- encore encore après : 
![Screenshot_2020-02-21 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-4](https://user-images.githubusercontent.com/36087963/75074015-007df280-54fb-11ea-9847-02766b38089d.png)

Bref, grisage/dégrisage général à chaque clic ^^

HTH

**Comment by vdct** [comment]
Merci @deuzeffe !
Ca marchait comme prévu.... sauf que le statut FANTOIR ne s'applique pas aux objets de cet onglet, par définition. J'avais répliqué le schéma des autres onglets en oubliant de réfléchir :p 
Donc j'ai finalement supprimé les listes de statut dans cet onglet. On peut réfléchir à d'autres statuts spécifiques, même si en première approche je ne vois pas trop lesquels.
A suivre

**Comment by deuzeffe** [comment]
Damnède, moi qui ai passé la soirée à qualifier les erreurs pour faire le bilan... Bon, j'ai fait un screenshot pour sauvegarder toussa avant de faire un refresh de la page \o/

De ce que j'ai relevé comme erreurs sur ma zone de confort :
- erreurs manuelles de tagging (mauvais type de voie, bout de way oublié dans le renommage, etc.) -> correction aisée qui ne dépend que de moi ;
- voies existantes sur le terrain (survey), mais non présentes dans le cadastre/fantoir (tautologie) : oublie de déclaration municipale à la DGFiP ? -> correction administrative qui dépend de la municipalité ;
- prise en compte du tag old_name=* ; ça ne devrait pas ^^ -> correction (aisée ?) qui dépend du codeur de l'analyse s'il considère que ce détail vaut le coup ;)

HTH

**Comment by vdct** [comment]
Heureusement que tu as fait un screenshot car les statuts sur cet onglet n'étaient pas sauvegardés, tu aurais tout perdu au moindre F5.
Pour le 3e cas il y a ce ticket https://github.com/osm-fr/bano/issues/27 sur lequel le boulot reprend doucement

**Comment by deuzeffe** [comment]
Effectivement, le https://github.com/osm-fr/bano/issues/27 semble plus utile pour traquer les erreurs du pourquoi du non-rapprochement. Si j'ai bien compris, il est à garder ?

Donc, pour les statuts de cet onglet, a minima :
- Erreur de tagging 
- Terrain Ok
- old_name (et ses variantes)
- ...

Enfin, si ça en vaut la peine, hein.

**Comment by vdct** [comment]
Oui, la question est bien "est-ce que ça en vaut la peine". Je propose qu'on réactive le sujet quand https://github.com/osm-fr/bano/issues/27 sera fait, on y verra un peu plus clair.

**Comment by deuzeffe** [comment]
Je ferme ou je laisse ouvert "pour mémoire" ?

**Comment by vdct** [comment]
Je propose qu'on ferme. J'ai crée https://github.com/osm-fr/osm-vs-fantoir/issues/95 pour la suite

**Comment by deuzeffe** [comment]
@vdct Chef ! Oui, chef !
(vu)
