### ISSUE TITLE
Onglet 2 : pas de moyen d'édition disponible

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#96]
Hello,

C'est moi ou la colonne "Édition" est vide ? 
![Screenshot_2020-02-22 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-5](https://user-images.githubusercontent.com/36087963/75099610-e3f9bd00-55c3-11ea-817b-ea56a8f291f5.png)

**Comment by vdct** [comment]
Oui c'est normal (hélas). On parle des voies sans adresse, donc non fournies par le Cadastre. Et non rapprochées d'OSM. Sans cadastre ni OSM, on n'a aucune source géométrique, juste le listing Fantoir. Donc impossible de fournir des liens qui contiennent des coordonnées, pour atterrir sur le bon objet. C'est une régression par rapport à la v1 où le parsing des PDFs du Cadastre nous apportait de l'info sur la géométrie des voies, y compris celles sans adresses...

**Comment by deuzeffe** [comment]
Merci pour ta réponse. Il m'arrive aussi d'oublier de réfléchir (avant de dire... une idiotie, donc ^^). Et merci d'avoir élucider mon interrogation sur l'origine de caractère "sans adresse".
