### ISSUE TITLE
Lieu-dit classé dans "Voies sans adresses"

### ISSUE THREAD

**Issue by deuzeffe** [osm-fr/osm-vs-fantoir#97]
Hello,

Si je lis bien la description du fichier Fantoir, le premier caractère du code Rivoli est :
- A : pour les ensembles immobiliers ;
- B à W : pour les lieux-dits.

Or, dans l'onglet 3, pour ma commune, sont listées : 
- des "voies" en A : ça peut se défendre. J'en retrouve aussi dans l'onglet 1. Ça se défend aussi ;
- et une "voie" (lieu-dit selon son code Rivoli. Et le terrain est d'accord). 

![Screenshot_2020-02-23 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-6](https://user-images.githubusercontent.com/36087963/75107740-f6eeaa80-5620-11ea-8bfe-c0c3de46f72b.png)
- pourtant bien présente dans l'onglet 5 
![Screenshot_2020-02-23 Aixe-sur-Vienne - Correspondance entre FANTOIR et voies OSM-7](https://user-images.githubusercontent.com/36087963/75110896-2e1a8700-5634-11ea-985e-40b79d956547.png)

HTH.

**Comment by vdct** [comment]
Le découpage entre voies et lieux-dits n'est pas *du tout* une science exacte, surtout si on essaie de faire correspondre les concepts d'OSM et de FANTOIR. Il faut se souvenir qu'un usage principal du contenu BANO est de permettre le géocodage, la correspondance entre une adresse (au sens très large) et un (x,y).
BANO se compose de 3 ensembles : 
- les adresses numérotées, ce qui correspond à nos rapprochements de voies avec adresses
- les voies sans adresse numérotée
- les lieux-dits
Le 1er ensemble est assez simple à délimiter : tout ce qui a un addr:housenumber tombe là-dedans, en gros
C'est plus flou pour tracer la limite entre les 2e et 3e ensembles car ni l'un ni l'autre n'ont de n° (je mets de côté les addr:place). La modélisation dans FANTOIR et dans OSM n'étant pas super homogène, on doit pour remplir le 2e ensemble ratisser un peu large, et notamment récupérer des points nommés ayant un ref:FR:FANTOIR renseigné. C'est dans ce cas que tombe ton exemple. Il y a peut-être moyen de mieux filtrer ces points en ajoutant un critère comme : "le point ne doit pas avoir de tag place pour ne pas empiéter sur les rapprochements de lieux-dits", mais je dis ça sans l'avoir trop testé. Le but étant de fournir un référentiel le plus complet possible pour le géocodage, on préfère avoir un point nommé présent 2 fois que 0 dans les résultats, quitte à faire nu peu de ménage ultérieurement dans les fichiers mis à dispo des consommateurs de BANO.

**Comment by vdct** [comment]
Dit autrement : pour détecter les voies sans adresses, on ratisse bien plus large que les voies au sens strict : des équipements, des stations de metro, etc. Et parfois dans le lot il y a des lieux-dits. Donc on peut avoir des codes FANTOIR de lieux-dits (au sens des lieux-dits de FANTOIR) dans l'onglet 3 sans que ce soit un bug. Il faut le voir comme une tolérance, et se dire que la frontière entre les onglets 3 et 5 est poreuse.

**Comment by deuzeffe** [comment]
Merci bien pour ta double (!) explication. J'en retiens que ma remarque n'a qu'une importance limitée (à ma compréhension de la chose). Le tout est de savoir pourquoi ça ne correspond pas à la rigidité de ma vision. Ce qui est chose faite ^^
So, on feeerme !
